// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Int.res.
let result = Int.bitwiseAnd(1, 2)
let result = Int.bitwiseOr(1, 2)
let result = Int.bitwiseXor(1, 2)
let result = Int.shiftLeft(1, 2)
let result = Int.shiftRightUnsigned(1, 2)
let result = Int.shiftRight(1, 2)
let result = Int.bitwiseNot(0)

