let rec path_to_ts (path : Path.t) : string =
  match path with
  | Pident id -> Ident.name id
  | Pdot (p, s, _) ->
    let parent = path_to_ts p in
    parent ^ "." ^ s
  | Papply _ -> "unknown"

let rec type_expr_to_ts (ty : Types.type_expr) : string =
  match ty.desc with
  | Tvar None -> "unknown"
  | Tvar (Some s) -> s
  | Tarrow ({lbl = Nolabel; typ = arg_ty}, ret_ty, _, _) ->
    let arg = type_expr_to_ts arg_ty in
    let ret = type_expr_to_ts ret_ty in
    "(" ^ arg ^ ") => " ^ ret
  | Tarrow ({lbl = Labelled {txt = l}; typ = arg_ty}, ret_ty, _, _) ->
    let arg = type_expr_to_ts arg_ty in
    let ret = type_expr_to_ts ret_ty in
    l ^ ": " ^ arg ^ " => " ^ ret
  | Tarrow ({lbl = Optional {txt = l}; typ = arg_ty}, ret_ty, _, _) ->
    let arg = type_expr_to_ts arg_ty in
    let ret = type_expr_to_ts ret_ty in
    l ^ "?: " ^ arg ^ " => " ^ ret
  | Ttuple tys -> "[" ^ String.concat ", " (List.map type_expr_to_ts tys) ^ "]"
  | Tconstr (path, args, _) ->
    let name = path_to_ts path in
    let name =
      match name with
      | "int" -> "number"
      | "float" -> "number"
      | "string" -> "string"
      | "bool" -> "boolean"
      | "unit" -> "void"
      | "array" -> "Array"
      | "list" -> "Array"
      | "option" -> "unknown"
      | "promise" -> "Promise"
      | _ -> name
    in
    if args = [] then name
    else name ^ "<" ^ String.concat ", " (List.map type_expr_to_ts args) ^ ">"
  | Tlink ty -> type_expr_to_ts ty
  | Tpoly (ty, _) -> type_expr_to_ts ty
  | Tnil -> "undefined"
  | _ -> "unknown"

let rec function_arity (lam : Lam.t) : int option =
  match lam with
  | Lam.Lfunction {arity; _} -> Some arity
  | Lam.Llet (_, _, _, _, body) -> function_arity body
  | _ -> None

let emit_decls ppf (groups : Lam_group.t list) (exports : Ident.t list) =
  let export_set = Set_ident.of_list exports in
  let walk_group (group : Lam_group.t) =
    match group with
    | Lam_group.Single (_, id, lam) when Set_ident.mem export_set id -> (
      let ts_ty =
        match lam with
        | Lam.Llet (_, _, ty, _, _) -> (
          match ty with
          | Some ty -> Some (type_expr_to_ts ty)
          | None -> None)
        | Lam.Lfunction {ty; _} -> (
          match ty with
          | Some ty -> Some (type_expr_to_ts ty)
          | None -> None)
        | _ -> None
      in
      let is_fn = function_arity lam in
      match (is_fn, ts_ty) with
      | Some _, Some ts -> Format.fprintf ppf "export const %s: %s@." id.name ts
      | Some _, None ->
        Format.fprintf ppf "export function %s(...args: unknown[]): unknown@."
          id.name
      | None, Some ts -> Format.fprintf ppf "export const %s: %s@." id.name ts
      | None, None -> Format.fprintf ppf "export const %s: unknown@." id.name)
    | Lam_group.Recursive bindings ->
      List.iter
        (fun (id, lam) ->
          if Set_ident.mem export_set id then
            match function_arity lam with
            | Some _ ->
              Format.fprintf ppf
                "export function %s(...args: unknown[]): unknown@." id.name
            | None -> Format.fprintf ppf "export const %s: unknown@." id.name)
        bindings
    | _ -> ()
  in
  Format.fprintf ppf "// Type declarations generated by ReScript@.@.";
  List.iter walk_group groups
