version: 2
updates:
  # Manage npm dependencies in the top-level package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Manage GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Versions >1.4.3 interfere with caching done by our own CI script,
      # causing the dune binary not to be found anymore.
      - dependency-name: "awalsh128/cache-apt-pkgs-action"
