# Number of days of inactivity before an issue becomes stale
daysUntilStale: 720
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - "PRIORITY:HIGH"
  - bug
  - non-critical-bug
  - security
  - enhancement
  - optimization
  - v8-breaking-changes
  - documentation
  - "need feedback"
  - "GOOD FIRST TASK"
  - "BREAKING CHANGES"
  - APPROVED
  - discussion
  - BUILD
  - "help wanted"
  - "GOOD FOR PR"
  - "TO REPRODUCE"
  - FFI
  - internal
  - ideas
  - playground
  - Syntax
  - test
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
