// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";
import * as JsxRuntime from "react/jsx-runtime";

let Id = {};

function customDouble(foo) {
  return (foo << 1);
}

let Dep = {
  customDouble: customDouble
};

function Hover$HoverInsideModuleWithComponent(props) {
  return null;
}

let HoverInsideModuleWithComponent = {
  x: 2,
  make: Hover$HoverInsideModuleWithComponent
};

function functionWithTypeAnnotation() {
  return 1;
}

function Hover(props) {
  return props.name;
}

function Hover$C2$make2(props) {
  return props.name;
}

let C2 = {
  make2: Hover$C2$make2
};

function log(msg) {
  console.log(msg);
}

let JsLogger = {
  log: log
};

let IdDefinedTwice = {
  y: 20,
  _x: 10
};

let A = {
  x: 13
};

function Hover$Comp(props) {
  return props.children;
}

let Comp = {
  make: Hover$Comp
};

JsxRuntime.jsxs(Hover$Comp, {
  children: [
    JsxRuntime.jsx("div", {}),
    JsxRuntime.jsx("div", {})
  ]
});

JsxRuntime.jsxs(Hover$Comp, {
  children: [
    JsxRuntime.jsx("div", {}),
    JsxRuntime.jsx("div", {})
  ]
});

function _get(r) {
  return r.f + r.i;
}

function withAs(yyy) {
  return yyy + 1 | 0;
}

function fnnxx(b) {
  return b;
}

let AA = {
  fnnxx: fnnxx
};

function arity0a() {
  return () => 3;
}

function arity0b(param, param$1) {
  return 3;
}

function arity0c(param, param$1) {
  return 3;
}

function arity0d() {
  return () => 3;
}

let ModWithDocComment = {
  x: 44
};

let TypeSubstitutionRecords_x1 = {
  content: {
    age: 42
  },
  zzz: ""
};

let TypeSubstitutionRecords_x2 = {
  content: {
    age: 42
  },
  zzz: ""
};

let TypeSubstitutionRecords_y1 = {
  content: {
    age: 42
  },
  zzz: ""
};

let TypeSubstitutionRecords_y2 = {
  content: {
    age: 42
  },
  zzz: ""
};

let TypeSubstitutionRecords = {
  x1: TypeSubstitutionRecords_x1,
  x2: TypeSubstitutionRecords_x2,
  y1: TypeSubstitutionRecords_y1,
  y2: TypeSubstitutionRecords_y2
};

function make(props) {
  Primitive_object.equal(props.n, 10);
  return props.s;
}

let CompV4 = {
  make: make
};

function testUseR(v) {
  return v;
}

let NotShadowed = {
  xx_: 10,
  xx: 10
};

let Shadowed = {
  xx: 10
};

let RecursiveVariants = {};

let abc = 56;

let D;

let cd = customDouble;

let make$1 = Hover;

let num = 34;

let JJ;

let B;

let C;

let Comp1;

let funAlias = fnnxx;

let typeOk = fnnxx;

let typeDuplicate = fnnxx;

let dd = 34;

let docComment1 = 12;

let docComment2 = 12;

let mk = make;

let usr = {
  x: 123,
  y: /* [] */0
};

let x = {
  someField: true
};

let someField = true;

let coolVariant = "CoolVariant";

let payloadVariant = {
  TAG: "InlineRecord",
  field1: 1,
  field2: true
};

let payloadVariant2 = {
  TAG: "Args",
  _0: 1,
  _1: true
};

let recursiveVariant = {
  TAG: "Action1",
  _0: 1
};

let Arr;

export {
  abc,
  Id,
  Dep,
  D,
  cd,
  HoverInsideModuleWithComponent,
  functionWithTypeAnnotation,
  make$1 as make,
  C2,
  num,
  JsLogger,
  JJ,
  IdDefinedTwice,
  A,
  B,
  C,
  Comp,
  Comp1,
  _get,
  withAs,
  AA,
  funAlias,
  typeOk,
  typeDuplicate,
  dd,
  arity0a,
  arity0b,
  arity0c,
  arity0d,
  docComment1,
  docComment2,
  ModWithDocComment,
  TypeSubstitutionRecords,
  CompV4,
  mk,
  testUseR,
  usr,
  NotShadowed,
  Shadowed,
  x,
  someField,
  coolVariant,
  payloadVariant,
  payloadVariant2,
  RecursiveVariants,
  recursiveVariant,
  Arr,
}
/*  Not a pure module */
