// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CoreGen from "./Core.gen";

function null0(x) {
  return x;
}

function null1(x) {
  return x;
}

function nullable0(x) {
  return x;
}

function nullable1(x) {
  return x;
}

function undefined0(x) {
  return x;
}

function dict0(x) {
  return x;
}

function dict1(x) {
  return x;
}

function promise0(x) {
  return x;
}

function promise1(x) {
  return x;
}

function taggedTemplate0(x) {
  return x;
}

function taggedTemplate1(x) {
  return x;
}

function date1(x) {
  return x;
}

function bigint0(x) {
  return x;
}

function stdlibBigInt(x) {
  return x;
}

function regexp1(x) {
  return x;
}

function stdlibArray(x) {
  return x;
}

function map1(x) {
  return x;
}

function weakmap1(x) {
  return x;
}

function set1(x) {
  return x;
}

function weakset1(x) {
  return x;
}

function option0(x) {
  return x;
}

function option1(x) {
  return x;
}

function someFunWithNullThenOptionalArgs(prim0, prim1) {
  return CoreGen.someFunWithNullThenOptionalArgs(prim0, prim1);
}

function someFunWithNullUndefinedArg(prim0, prim1) {
  return CoreGen.someFunWithNullUndefinedArg(prim0, prim1);
}

let $$Map;

let $$Set;

let jsonEncodeString1 = "hello";

let jsonEncodeString2 = "hello";

export {
  null0,
  null1,
  nullable0,
  nullable1,
  undefined0,
  dict0,
  dict1,
  promise0,
  promise1,
  taggedTemplate0,
  taggedTemplate1,
  date1,
  bigint0,
  stdlibBigInt,
  regexp1,
  stdlibArray,
  $$Map,
  $$Set,
  map1,
  weakmap1,
  set1,
  weakset1,
  option0,
  option1,
  someFunWithNullThenOptionalArgs,
  someFunWithNullUndefinedArg,
  jsonEncodeString1,
  jsonEncodeString2,
}
/* ./Core.gen Not a pure module */
