// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ImportJsValueGen from "./ImportJsValue.gen";
import ImportJsValueGen$1 from "./ImportJsValue.gen";

function round(prim) {
  return ImportJsValueGen.round(prim);
}

function round2(prim) {
  return ImportJsValueGen.round2(prim);
}

function area(prim) {
  return ImportJsValueGen.area(prim);
}

function returnMixedArray(prim) {
  return ImportJsValueGen.returnMixedArray();
}

let roundedNumber = ImportJsValueGen.round(1.8);

let areaValue = ImportJsValueGen.area({
  x: 3,
  y: undefined
});

function getAbs(x) {
  let getAbs$1 = x.getAbs;
  return getAbs$1();
}

let AbsoluteValue = {
  getAbs: getAbs
};

function useGetProp(x) {
  return x.getProp() + 1 | 0;
}

function useGetAbs(x) {
  return getAbs(x) + 1 | 0;
}

function useColor(prim) {
  return ImportJsValueGen.useColor(prim);
}

function useEscapedInlineVariant(prim) {
  return ImportJsValueGen.useEscapedInlineVariant((() => {
    switch (prim) {
      case "illegalName" :
        return "Illegal\"Name";
    }
  })());
}

function useUtf8InlineVariant(prim) {
  return ImportJsValueGen.useUtf8InlineVariant((() => {
    switch (prim) {
      case "utf8" :
        return "café\npath\\name";
    }
  })());
}

function higherOrder(prim) {
  return ImportJsValueGen.higherOrder(prim);
}

let returnedFromHigherOrder = ImportJsValueGen.higherOrder((prim0, prim1) => prim0 + prim1 | 0);

function convertVariant(prim) {
  return ImportJsValueGen.convertVariant(prim);
}

function polymorphic(prim) {
  return ImportJsValueGen.polymorphic(prim);
}

let $$default = ImportJsValueGen$1;

export {
  round,
  round2,
  area,
  returnMixedArray,
  roundedNumber,
  areaValue,
  AbsoluteValue,
  useGetProp,
  useGetAbs,
  useColor,
  useEscapedInlineVariant,
  useUtf8InlineVariant,
  higherOrder,
  returnedFromHigherOrder,
  convertVariant,
  polymorphic,
  $$default as default,
}
/* roundedNumber Not a pure module */
