// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ImportHookDefaultGen from "./ImportHookDefault.gen";
import ImportHookDefaultGen$1 from "./ImportHookDefault.gen";

let make = ImportHookDefaultGen.make;

let make2 = ImportHookDefaultGen$1;

let MM = {
  make2: make2
};

export {
  make,
  MM,
}
/* make Not a pure module */
