// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JSXV4Gen from "./JSXV4.gen";

function JSXV4$CompV4(props) {
  return props.x + props.y;
}

let CompV4 = {
  make: JSXV4$CompV4
};

let make = JSXV4Gen.make;

let JSXV4$CompV4$jsx = true;

export {
  CompV4,
  make,
  JSXV4$CompV4,
  JSXV4$CompV4$jsx,
}
/* make Not a pure module */
