// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

function convert(p) {
  return p.then(param => Promise.resolve({
    result: param.s
  }));
}

function barx(xOpt, param) {
  let x = xOpt !== undefined ? xOpt : Promise.resolve("a");
  return Primitive_object.equal(x, x);
}

export {
  convert,
  barx,
}
/* No side effect */
