// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DaxSh from "dax-sh";
import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";

let binPaths = await import(Nodepath.resolve(Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url)), "../../../cli/common/bins.js"));

function commands(workingDirectory) {
  let build = async () => {
    await DaxSh.$`${binPaths.rescript_exe} build`.cwd(workingDirectory);
  };
  let install = async () => {
    await DaxSh.$`npm install`.cwd(workingDirectory);
  };
  return {
    rescript: {
      build: build
    },
    npm: {
      install: install
    }
  };
}

export {
  binPaths,
  commands,
}
/* binPaths Not a pure module */
