(rule
 (target platform.ml)
 (enabled_if
  (= %{os_type} Win32))
 (action
  (copy platform_windows.ml platform.ml)))

(rule
 (target platform.ml)
 (enabled_if
  (<> %{os_type} Win32))
 (action
  (copy platform_unix.ml platform.ml)))

(library
 (name rewatch_ocaml_lib)
 (wrapped false)
 (modules
  cli
  config
  platform_common
  platform
  process
  source
  graph
  package_metadata
  build_artifacts
  toolchain
  compiler_info
  warning_state
  output
  build
  format)
 (libraries unix yojson str spawn cmdliner))

(executable
 (name rescript_ocaml)
 (modules rescript_ocaml)
 (libraries rewatch_ocaml_lib))

(test
 (name unit_tests)
 (modules unit_tests platform_windows)
 (libraries rewatch_ocaml_lib))

(test
 (name cli_tests)
 (modules cli_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name config_tests)
 (modules config_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name package_metadata_tests)
 (modules package_metadata_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name source_tests)
 (modules source_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name compiler_info_tests)
 (modules compiler_info_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name warning_state_tests)
 (modules warning_state_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name output_tests)
 (modules output_tests)
 (libraries rewatch_ocaml_lib))

(test
 (name toolchain_tests)
 (modules toolchain_tests platform_windows)
 (libraries rewatch_ocaml_lib))
