// Generated by ReScript, PLEASE EDIT WITH CARE

export interface user {
  readonly name: string;
  readonly age: number;
}

export interface userWithRename {
  readonly user_name: string;
  readonly user_age: number;
  readonly type: string;
}

export interface User {
  readonly name: string;
  readonly age: number;
}

export function add(a: number, b: number): number;

export function greet(name: string): string;

export function identity<A>(x: A): A;

export function processOption(opt: number | undefined): number;

export function createUser(name: string, age: number): user;

export function asyncFetch(url: string): Promise<string>;

export const myNumber: number;

export const myString: string;