// Generated by ReScript, PLEASE EDIT WITH CARE


function add(a, b) {
  return a + b | 0;
}

function greet(name) {
  return "Hello, " + name;
}

function identity(x) {
  return x;
}

async function asyncIdentity(x) {
  return x;
}

function processOption(opt) {
  if (opt !== undefined) {
    return opt;
  } else {
    return 0;
  }
}

let myNumber = 42;

let myString = "hello";

export {
  add,
  greet,
  identity,
  asyncIdentity,
  processOption,
  myNumber,
  myString,
}
/* No side effect */
