// Generated by ReScript, PLEASE EDIT WITH CARE


function makeSet() {
  return (new Set());
}

function makeMap() {
  return (new Map());
}

function getIterator(_arr) {
  return (_arr[Symbol.iterator]());
}

function makeObservable() {
  return null;
}

function testSubscribe(obs) {
  return obs.subscribe(value => {
    console.log(value);
  });
}

async function testForEach(obs) {
  return await obs.forEach(n => {
    console.log("value:", n);
  });
}

async function testToPromise(obs) {
  let result = await obs.toPromise();
  if (result !== undefined) {
    console.log("got:", result);
  } else {
    console.log("none");
  }
}

export {
  makeSet,
  makeMap,
  getIterator,
  makeObservable,
  testSubscribe,
  testForEach,
  testToPromise,
}
/* No side effect */
