// Generated by ReScript, PLEASE EDIT WITH CARE


function MakeShowable(M) {
  return M;
}

function MakeComparable(M) {
  return M;
}

function MakePair(Left) {
  return Right => {
    let showPair = (l, r) => "(" + Left.show(l) + ", " + Right.show(r) + ")";
    return {
      showPair: showPair
    };
  };
}

function MakeTriple(A) {
  return B => (C => {
    let showTriple = (x, y, z) => "(" + A.show(x) + ", " + B.show(y) + ", " + C.show(z) + ")";
    return {
      showTriple: showTriple
    };
  });
}

function showable(show) {
  return {
    show: show
  };
}

function comparable(compare) {
  return {
    compare: compare
  };
}

function hashable(hash, eq) {
  return {
    hash: hash,
    eq: eq
  };
}

function show(s) {
  return s;
}

let stringShowable = {
  show: show
};

let intComparable = {
  compare: (a, b) => a - b | 0
};

function useShowable(m, x) {
  return m.show(x);
}

export {
  MakeShowable,
  MakeComparable,
  MakePair,
  MakeTriple,
  showable,
  comparable,
  hashable,
  stringShowable,
  intComparable,
  useShowable,
}
/* No side effect */
