// Generated by ReScript, PLEASE EDIT WITH CARE


let Inner = {
  value: 42
};

function add(a, b) {
  return a + b | 0;
}

function multiply(a, b) {
  return a * b | 0;
}

let $$Math = {
  add: add,
  multiply: multiply
};

function greet(name) {
  return "Hello, " + name;
}

let Nested = {
  greet: greet
};

let Outer = {
  Nested: Nested
};

function make(rawEmail) {
  if (rawEmail.includes("@")) {
    return rawEmail;
  }
}

function toString(email) {
  return email;
}

let Email = {
  make: make,
  toString: toString
};

function make$1(id) {
  return id;
}

function toInt(id) {
  return id;
}

let UserId = {
  make: make$1,
  toInt: toInt
};

let sum = 3;

let greeting = "Hello, World";

let validEmail = make("test@example.com");

let useInner = 42;

export {
  Inner,
  $$Math,
  Outer,
  Email,
  UserId,
  useInner,
  sum,
  greeting,
  validEmail,
}
/* validEmail Not a pure module */
