// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

declare namespace Inner {
  type t = number;
}
export type Inner = {
  value: Inner.t;
};
export const Inner: Inner;

export type Math = {
  add: (arg0: number, arg1: number) => number;
  multiply: (arg0: number, arg1: number) => number;
};
export const $$Math: Math;

declare namespace Outer {
  namespace Nested {
    type t = string;
  }
  type Nested = {
    greet: (arg0: Outer.Nested.t) => string;
  };
}
export type Outer = {
  Nested: Outer.Nested;
};
export const Outer: Outer;

declare namespace Email {
  type t = rescript.opaque<
  "Modules.Email.t",
  [],
  string
>;
}
export type Email = {
  make: (arg0: string) => rescript.option<Email.t>;
  toString: (arg0: Email.t) => string;
};
export const Email: Email;

declare namespace UserId {
  type t = rescript.opaque<
  "Modules.UserId.t",
  [],
  number
>;
}
export type UserId = {
  make: (arg0: number) => UserId.t;
  toInt: (arg0: UserId.t) => number;
};
export const UserId: UserId;

export const useInner: Inner.t;

export const sum: number;

export const greeting: string;

export const validEmail: rescript.option<Email.t>;
