// Generated by ReScript, PLEASE EDIT WITH CARE


function validate(s) {
  return s;
}

function getValue(s) {
  return s;
}

let defaultUser = {
  user_name: "Anonymous",
  user_age: 0
};

export {
  defaultUser,
  validate,
  getValue,
}
/* No side effect */
