// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export interface User {
  readonly user_name: string;
  readonly user_age: number;
}

export type status =
  | "Active"
  | "Inactive"
  | "pending_review";

export type result2 =
  | { readonly TAG: "Ok2"; readonly _0: number }
  | { readonly TAG: "Error2"; readonly _0: string };

export type event =
  | {
    readonly TAG: "Click";
    readonly x: number;
    readonly y: number;
  }
  | {
    readonly TAG: "KeyPress";
    readonly key: string;
    readonly shift: boolean;
  }
  | "NoData";

export type action =
  | { readonly type: "Navigate"; readonly _0: string }
  | "Submit";

export type stringOrInt =
  | string
  | number;

export type valid = rescript.opaque<"Types.valid", []>;

export type invalid = rescript.opaque<"Types.invalid", []>;

export type validated<S> = rescript.opaque<"Types.validated", [S], string>;

export const defaultUser: User;

export function validate(s: validated<invalid>): validated<valid>;

export function getValue<S>(s: validated<S>): string;
