// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Globals$TestModule from "test-module/src/Globals.js";

export function copy(
  params: Globals$TestModule.URLSearchParams.t,
): Globals$TestModule.URLSearchParams.t;
