// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Types from "./Types.d.ts";

export function createUser(name: string, age: number): Types.User;

export function greetUser(user: Types.User): string;

export function getDefaultUser(param: void): Types.User;