// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Types from "./Types.js";

export function createUser(name: string, age: number): Types.user;

export function greetUser(user: Types.user): string;

export function getDefaultUser(): Types.user;