// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Types from "./Types.js";

export function createUser(name: string, age: number): Types.User;

export function greetUser(user: Types.User): string;

export function getDefaultUser(): Types.User;