#!/usr/bin/env node

// @ts-check

"use strict";

const child_process = require("child_process");
const { bsc_exe } = require("./bin_path.js");

const delegate_args = process.argv.slice(2);

try {
  child_process.execFileSync(bsc_exe, delegate_args, { stdio: "inherit" });
} catch (e) {
  if (e.code === "ENOENT") {
    console.error(String(e));
  }
  process.exit(2);
}
