#!/usr/bin/env node

// @ts-check

"use strict";

const child_process = require("node:child_process");
const { rescript_tools_exe } = require("./bin_path.js");

const args = process.argv.slice(2);

child_process.spawnSync(rescript_tools_exe, args, { stdio: "inherit" });
