#!/usr/bin/env node

// @ts-check

"use strict";

const child_process = require("node:child_process");
const { rewatch_exe } = require("./bin_path.js");

const args = process.argv.slice(2);

child_process.spawnSync(rewatch_exe, args, { stdio: "inherit" });
