// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

let eq = Primitive_object.equal;

Test.run([
  [
    "Stdlib_StringTests.res",
    3,
    20,
    47
  ],
  "String.equal optimization"
], false, eq, false);

Test.run([
  [
    "Stdlib_StringTests.res",
    5,
    13,
    32
  ],
  "String.asIterable"
], Array.from("abc"), eq, [
  "a",
  "b",
  "c"
]);

export {
  eq,
}
/*  Not a pure module */
