// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

let eq = Primitive_object.equal;

let nan = NaN;

let infinity = Number.POSITIVE_INFINITY;

let neg_infinity = Number.NEGATIVE_INFINITY;

Test.run([
  [
    "Stdlib_FloatTests.res",
    6,
    20,
    27
  ],
  "clamp"
], Stdlib_Float.clamp(undefined, undefined, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    7,
    20,
    35
  ],
  "clamp - < min"
], Stdlib_Float.clamp(4.3, undefined, 4.1), eq, 4.3);

Test.run([
  [
    "Stdlib_FloatTests.res",
    8,
    20,
    35
  ],
  "clamp - > min"
], Stdlib_Float.clamp(4.1, undefined, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    9,
    20,
    35
  ],
  "clamp - < max"
], Stdlib_Float.clamp(undefined, 4.3, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    10,
    20,
    35
  ],
  "clamp - > max"
], Stdlib_Float.clamp(undefined, 4.1, 4.2), eq, 4.1);

Test.run([
  [
    "Stdlib_FloatTests.res",
    11,
    20,
    42
  ],
  "clamp - < min, < max"
], Stdlib_Float.clamp(4.3, 4.5, 4.2), eq, 4.3);

Test.run([
  [
    "Stdlib_FloatTests.res",
    12,
    20,
    42
  ],
  "clamp - < min, > max"
], Stdlib_Float.clamp(4.3, 4.1, 4.2), eq, 4.3);

Test.run([
  [
    "Stdlib_FloatTests.res",
    13,
    20,
    42
  ],
  "clamp - > min, < max"
], Stdlib_Float.clamp(4.1, 4.5, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    14,
    20,
    42
  ],
  "clamp - > min, > max"
], Stdlib_Float.clamp(4.1, 4.1, 4.2), eq, 4.1);

Test.run([
  [
    "Stdlib_FloatTests.res",
    15,
    20,
    33
  ],
  "clamp - nan"
], Number.isNaN(Stdlib_Float.clamp(4.1, 4.3, nan)), eq, true);

Test.run([
  [
    "Stdlib_FloatTests.res",
    16,
    20,
    38
  ],
  "clamp - infinity"
], Stdlib_Float.clamp(4.1, 4.3, infinity), eq, 4.3);

Test.run([
  [
    "Stdlib_FloatTests.res",
    17,
    20,
    39
  ],
  "clamp - -infinity"
], Stdlib_Float.clamp(4.1, 4.3, neg_infinity), eq, 4.1);

Test.run([
  [
    "Stdlib_FloatTests.res",
    18,
    20,
    37
  ],
  "clamp - min nan"
], Stdlib_Float.clamp(nan, undefined, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    19,
    20,
    37
  ],
  "clamp - max nan"
], Stdlib_Float.clamp(undefined, nan, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    20,
    20,
    46
  ],
  "clamp - min nan, max nan"
], Stdlib_Float.clamp(nan, nan, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    21,
    20,
    42
  ],
  "clamp - min infinity"
], Stdlib_Float.clamp(infinity, undefined, 4.2), eq, infinity);

Test.run([
  [
    "Stdlib_FloatTests.res",
    22,
    20,
    42
  ],
  "clamp - max infinity"
], Stdlib_Float.clamp(undefined, infinity, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    23,
    20,
    43
  ],
  "clamp - min -infinity"
], Stdlib_Float.clamp(neg_infinity, undefined, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    24,
    20,
    43
  ],
  "clamp - max -infinity"
], Stdlib_Float.clamp(undefined, neg_infinity, 4.2), eq, neg_infinity);

Test.run([
  [
    "Stdlib_FloatTests.res",
    26,
    13,
    49
  ],
  "clamp - min infinity, max infinity"
], Stdlib_Float.clamp(infinity, infinity, 4.2), eq, infinity);

Test.run([
  [
    "Stdlib_FloatTests.res",
    32,
    13,
    50
  ],
  "clamp - min -infinity, max infinity"
], Stdlib_Float.clamp(neg_infinity, infinity, 4.2), eq, 4.2);

Test.run([
  [
    "Stdlib_FloatTests.res",
    38,
    13,
    50
  ],
  "clamp - min infinity, max -infinity"
], Stdlib_Float.clamp(infinity, neg_infinity, 4.2), eq, infinity);

Test.run([
  [
    "Stdlib_FloatTests.res",
    44,
    13,
    51
  ],
  "clamp - min -infinity, max -infinity"
], Stdlib_Float.clamp(neg_infinity, neg_infinity, 4.2), eq, neg_infinity);

Test.run([
  [
    "Stdlib_FloatTests.res",
    50,
    20,
    46
  ],
  "Float.equal optimization"
], false, eq, false);

export {
  eq,
  nan,
  infinity,
  neg_infinity,
}
/* nan Not a pure module */
