// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

let eq = Primitive_object.equal;

Test.run([
  [
    "Stdlib_ListTests.res",
    3,
    20,
    40
  ],
  "includes - present"
], Stdlib_List.includes({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 2), eq, true);

Test.run([
  [
    "Stdlib_ListTests.res",
    4,
    20,
    40
  ],
  "includes - missing"
], Stdlib_List.includes({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 4), eq, false);

Test.run([
  [
    "Stdlib_ListTests.res",
    5,
    20,
    38
  ],
  "includes - empty"
], Stdlib_List.includes(/* [] */0, 1), eq, false);

let item = {
  language: "ReScript"
};

let items = {
  hd: item,
  tl: /* [] */0
};

Test.run([
  [
    "Stdlib_ListTests.res",
    11,
    22,
    46
  ],
  "includes - same object"
], Stdlib_List.includes(items, item), eq, true);

Test.run([
  [
    "Stdlib_ListTests.res",
    13,
    15,
    53
  ],
  "includes - structurally equal object"
], Stdlib_List.includes(items, {
  language: "ReScript"
}), eq, false);

export {
  eq,
}
/*  Not a pure module */
