// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./Test.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

let eq = Primitive_object.equal;

let someString = "hello";

let createdDict = {
  name: "hello",
  age: "what",
  more: "stuff",
  otherStr: someString
};

let intDict = {
  one: 1,
  two: 2,
  three: 3
};

function inferDictByPattern(dict) {
  if (dict.one === 1 && dict.three === 3 && dict.four === 4) {
    dict["five"] = 5;
    return;
  }
  if (dict.two !== 1) {
    console.log("not one");
  } else {
    console.log("two");
  }
}

function constrainedAsDict(dict) {
  if (dict.one !== 1) {
    console.log("not one");
  } else {
    console.log("one");
  }
}

let PatternMatching = {
  inferDictByPattern: inferDictByPattern,
  constrainedAsDict: constrainedAsDict
};

Test.run([
  [
    "Stdlib_DictTests.res",
    39,
    20,
    26
  ],
  "make"
], {}, eq, {});

Test.run([
  [
    "Stdlib_DictTests.res",
    41,
    20,
    31
  ],
  "fromArray"
], Object.fromEntries([[
    "foo",
    "bar"
  ]]), eq, {foo: "bar"});

Test.run([
  [
    "Stdlib_DictTests.res",
    44,
    13,
    27
  ],
  "fromIterable"
], Object.fromEntries([
  [
    "foo",
    "bar"
  ],
  [
    "baz",
    "qux"
  ]
]), eq, {foo: "bar", baz: "qux"});

let target = {
  a: 1,
  b: 2
};

let result = Object.assign(target, {
  b: 3
}, {
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    58,
    15,
    57
  ],
  "assignMany copies from sources to target"
], result, eq, {
  a: 1,
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    67,
    22,
    49
  ],
  "assignMany mutates target"
], result === target, eq, true);

let target$1 = {
  a: 1,
  b: 2
};

let result$1 = Object.assign({}, target$1, {
  b: 3,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    78,
    15,
    54
  ],
  "concat copies into a fresh dictionary"
], result$1, eq, {
  a: 1,
  b: 3,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    88,
    15,
    47
  ],
  "concat leaves target unchanged"
], target$1, eq, {
  a: 1,
  b: 2
});

Test.run([
  [
    "Stdlib_DictTests.res",
    96,
    22,
    57
  ],
  "concat returns a fresh dictionary"
], result$1 === target$1, eq, false);

let target$2 = {
  a: 1,
  b: 2
};

let result$2 = Object.assign({}, target$2, {
  b: 3
}, {
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    107,
    15,
    58
  ],
  "concatMany copies into a fresh dictionary"
], result$2, eq, {
  a: 1,
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    117,
    15,
    51
  ],
  "concatMany leaves target unchanged"
], target$2, eq, {
  a: 1,
  b: 2
});

Test.run([
  [
    "Stdlib_DictTests.res",
    125,
    22,
    61
  ],
  "concatMany returns a fresh dictionary"
], result$2 === target$2, eq, false);

let first = {
  a: 1,
  b: 2
};

let last = {
  b: 4,
  c: 0
};

let result$3 = Object.assign({}, first, {
  b: 3
}, last);

Test.run([
  [
    "Stdlib_DictTests.res",
    140,
    15,
    57
  ],
  "concatAll copies into a fresh dictionary"
], result$3, eq, {
  a: 1,
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    150,
    15,
    56
  ],
  "concatAll leaves first source unchanged"
], first, eq, {
  a: 1,
  b: 2
});

Test.run([
  [
    "Stdlib_DictTests.res",
    159,
    15,
    56
  ],
  "concatAll leaves later source unchanged"
], last, eq, {
  b: 4,
  c: 0
});

Test.run([
  [
    "Stdlib_DictTests.res",
    167,
    22,
    60
  ],
  "concatAll returns a fresh dictionary"
], result$3 === first, eq, false);

Test.run([
  [
    "Stdlib_DictTests.res",
    171,
    13,
    66
  ],
  "concatAll with empty array returns empty dictionary"
], Object.assign({}), eq, {});

let foo = {
  a: 1,
  b: 2
};

let baz = {
  b: 4,
  c: 5
};

let result$4 = Object.assign({}, foo, {
  b: 3
}, baz, {
  d: 6
});

Test.run([
  [
    "Stdlib_DictTests.res",
    189,
    15,
    53
  ],
  "dict spread respects overwrite order"
], result$4, eq, {
  a: 1,
  b: 4,
  c: 5,
  d: 6
});

Test.run([
  [
    "Stdlib_DictTests.res",
    200,
    15,
    58
  ],
  "dict spread leaves first source unchanged"
], foo, eq, {
  a: 1,
  b: 2
});

Test.run([
  [
    "Stdlib_DictTests.res",
    209,
    15,
    58
  ],
  "dict spread leaves later source unchanged"
], baz, eq, {
  b: 4,
  c: 5
});

let foo$1 = {
  a: 1
};

let result$5 = Object.assign({}, foo$1);

Test.run([
  [
    "Stdlib_DictTests.res",
    223,
    22,
    55
  ],
  "dict spread clone copies values"
], result$5, eq, foo$1);

Test.run([
  [
    "Stdlib_DictTests.res",
    224,
    22,
    68
  ],
  "dict spread clone returns a fresh dictionary"
], result$5 === foo$1, eq, false);

Test.run([
  [
    "Stdlib_DictTests.res",
    228,
    13,
    35
  ],
  "getUnsafe - existing"
], Object.fromEntries([[
      "foo",
      "bar"
    ]])["foo"], eq, "bar");

Test.run([
  [
    "Stdlib_DictTests.res",
    234,
    13,
    34
  ],
  "getUnsafe - missing"
], ({})["foo"], eq, undefined);

let dict = {
  key1: false,
  key2: undefined
};

Test.run([
  [
    "Stdlib_DictTests.res",
    246,
    22,
    38
  ],
  "has - existing"
], "key1" in dict, eq, true);

Test.run([
  [
    "Stdlib_DictTests.res",
    247,
    22,
    43
  ],
  "has - existing None"
], "key2" in dict, eq, true);

Test.run([
  [
    "Stdlib_DictTests.res",
    248,
    22,
    37
  ],
  "has - missing"
], "key3" in dict, eq, false);

Test.run([
  [
    "Stdlib_DictTests.res",
    249,
    22,
    39
  ],
  "has - prototype"
], "toString" in dict, eq, true);

Test.run([
  [
    "Stdlib_DictTests.res",
    251,
    15,
    51
  ],
  "has - parantesis in generated code"
], typeof ("key1" in dict), eq, "boolean");

let Has = {
  dict: dict
};

let three = 3;

export {
  eq,
  someString,
  createdDict,
  three,
  intDict,
  PatternMatching,
  Has,
}
/*  Not a pure module */
