// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Setup from "../src/Setup.mjs";
import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";
import * as Nodetest from "node:test";

let repo = Nodepath.resolve(Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url)), "../repos/deno/single-project");

let commands = await Setup.commands(repo, "deno");

Nodetest.describe("A single ReScript project using deno as package manager", () => {
  Nodetest.before(async () => await commands.deno.install());
  Nodetest.beforeEach(async () => await commands.git.checkout());
  Nodetest.test("should clean", async () => await commands.rescript.clean());
  Nodetest.test("should build", async () => await commands.rescript.build());
});

export {
  repo,
  commands,
}
/* repo Not a pure module */
