// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(request) {
  if (request.method !== "Post") {
    return 0;
  }
  if (request.headers.Authorization !== "Token") {
    return 0;
  }
  let match = request.body._0;
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return 0;
  }
  let match$1 = match.request;
  if (typeof match$1 !== "string") {
    return 0;
  }
  if (match$1 !== "READ") {
    return 0;
  }
  let match$2 = match.payload;
  if (typeof match$2 !== "object" || match$2 === null || Array.isArray(match$2)) {
    return 0;
  }
  let match$3 = match$2["list-a"];
  if (typeof match$3 !== "object" || match$3 === null || Array.isArray(match$3)) {
    return 0;
  }
  let tmp = match$3.last_known_events;
  if (typeof tmp === "object" && tmp !== null && !Array.isArray(tmp) && request.url.includes("/todo/events")) {
    return 1;
  } else {
    return 0;
  }
}

export {
  classify,
}
/* No side effect */
