// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Stdlib_Map from "@rescript/runtime/lib/es6/Stdlib_Map.js";


let loadStaticFiles: () => Promise<string[]> = (() => Promise.resolve(["public/foo.js", "dist/bar.js"]));

async function test(): Promise<Stdlib_Map.t<string, string>> {
  let files = await loadStaticFiles();
  return new Map(files.map((f: string): [string, string] => [
    f.startsWith("public/") ? f.slice(7) : f,
    f
  ]));
}

let isDev: boolean = true;

export {
  isDev,
  loadStaticFiles,
  test,
}
/* No side effect */
