// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
declare namespace Inner {
  type t = number;
}
export type Inner = {
  value: Inner.t;
};

export type Math = {
  add: (arg0: number, arg1: number) => number;
  multiply: (arg0: number, arg1: number) => number;
};

declare namespace Outer {
  namespace Nested {
    type t = string;
  }
  type Nested = {
    greet: (arg0: Outer.Nested.t) => string;
  };
}
export type Outer = {
  Nested: Outer.Nested;
};

declare namespace Email {
  type t = rescript.opaque<
  "Modules.Email.t",
  [],
  string
>;
}
export type Email = {
  make: (arg0: string) => rescript.option<Email.t>;
  toString: (arg0: Email.t) => string;
};

declare namespace UserId {
  type t = rescript.opaque<
  "Modules.UserId.t",
  [],
  number
>;
}
export type UserId = {
  make: (arg0: number) => UserId.t;
  toInt: (arg0: UserId.t) => number;
};

export type ExtendedMath = {
  add: (arg0: number, arg1: number) => number;
  multiply: (arg0: number, arg1: number) => number;
  subtract: (arg0: number, arg1: number) => number;
  divide: (arg0: number, arg1: number) => number;
};

export interface Printable<T> {
  readonly toString: (arg0: T) => string;
}

declare namespace PrintableInt {
  type t = number;
}
export type PrintableInt = {
  toString: (arg0: PrintableInt.t) => string;
};

declare namespace Outer2 {
  namespace Token {
    type t = rescript.opaque<
  "Modules.Outer2.Token.t",
  [],
  string
>;
  }
  type Token = {
    create: (arg0: string) => Outer2.Token.t;
    value: (arg0: Outer2.Token.t) => string;
  };
}
export type Outer2 = {
  Token: Outer2.Token;
};

let Inner: Inner = {
  value: 42
};

function add(a: number, b: number): number {
  return a + b | 0;
}

function multiply(a: number, b: number): number {
  return a * b | 0;
}

let $$Math: Math = {
  add: add,
  multiply: multiply
};

function greet(name: Outer.Nested.t): string {
  return "Hello, " + name;
}

let Nested: Outer.Nested = {
  greet: greet
};

let Outer: Outer = {
  Nested: Nested
};

function make(rawEmail: string): rescript.option<Email.t> {
  if (rawEmail.includes("@")) {
    return rawEmail as Email.t;
  }
}

function toString(email: Email.t): string {
  return email;
}

let Email: Email = {
  make: make,
  toString: toString
};

function make$1(id: number): UserId.t {
  return id as UserId.t;
}

function toInt(id: UserId.t): number {
  return id;
}

let UserId: UserId = {
  make: make$1,
  toInt: toInt
};

function subtract(a: number, b: number): number {
  return a - b | 0;
}

let divide = Primitive_int.div;

let ExtendedMath: ExtendedMath = {
  add: add,
  multiply: multiply,
  subtract: subtract,
  divide: divide
};

function toString$1(x: number): string {
  return x.toString();
}

let PrintableInt: PrintableInt = {
  toString: toString$1
};

function create(s: string): Outer2.Token.t {
  return ("token:" + s) as Outer2.Token.t;
}

function value(t: Outer2.Token.t): string {
  return t;
}

let Token: Outer2.Token = {
  create: create,
  value: value
};

let Outer2: Outer2 = {
  Token: Token
};

let sum: number = 3;

let greeting: string = "Hello, World";

let validEmail: rescript.option<Email.t> = make("test@example.com");

let diff: number = 5;

let product: number = 12;

let intString: string = (42).toString();

let token: Outer2.Token.t = "token:secret" as Outer2.Token.t;

let useInner: Inner.t = 42 as Inner.t;

export {
  Inner,
  $$Math,
  Outer,
  Email,
  UserId,
  ExtendedMath,
  PrintableInt,
  Outer2,
  useInner,
  sum,
  greeting,
  validEmail,
  diff,
  product,
  intString,
  token,
}
/* validEmail Not a pure module */
