// Generated by ReScript, PLEASE EDIT WITH CARE
import type * as rescript from "@rescript/runtime/types";



let myDict: rescript.dict<number> = {
  pi: 3.14
};

let myList: rescript.list<number> = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

let myOption: rescript.option<string> = "hello";

let myResult: rescript.result<number, string> = {
  TAG: "Ok",
  _0: 42
};

let myNull: rescript.null_<number> = 42;

let myNullable: rescript.nullable<string> = "hello";

let jsNull: rescript.null_<number> = 42;

let jsNullable: rescript.nullable<string> = "hello";

export {
  myList,
  myOption,
  myResult,
  myDict,
  myNull,
  myNullable,
  jsNull,
  jsNullable,
}
/* No side effect */
