// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.js";

function createUser(name: string, age: number): Types.user {
  return {
    user_name: name,
    user_age: age
  };
}

function greetUser(user: Types.user): string {
  return "Hello, " + user.user_name;
}

function getDefaultUser(): Types.user {
  return Types.defaultUser;
}

export {
  createUser,
  greetUser,
  getDefaultUser,
}
/* No side effect */
