// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dep01 from "@testrepo/dep01/src/Dep01.mjs";
import * as InternalDep from "./InternalDep.mjs";

console.log("01");

Dep01.log();

console.log(InternalDep.value);

let $$Array;

export {
  $$Array,
}
/*  Not a pure module */
