(env
 (_
  (flags
   (:standard -w +a-4-42-40-9-48-70))))

; The browser profile builds the playground compiler; this rule pair generates a module from platform/{native,playground}.

(rule
 (target ext_platform_primitives.ml)
 (enabled_if
  (= %{profile} browser))
 (action
  (copy
   platform/playground/ext_platform_primitives.ml
   ext_platform_primitives.ml)))

(rule
 (target ext_platform_primitives.ml)
 (enabled_if
  (<> %{profile} browser))
 (action
  (copy
   platform/native/ext_platform_primitives.ml
   ext_platform_primitives.ml)))

(library
 (name ext)
 (wrapped false)
 (instrumentation
  (backend bisect_ppx))
 (foreign_stubs
  (language c)
  (names ext_platform_primitives_stubs)))
