graph TD
    annotations[annotations L2]
    annotations --> solver.incorrect_dead_decls
    annotations --> liveness.annotated_roots
    exc_refs.exception_decls[exc_refs.exception_decls L3]
    exc_refs.exception_decls --> exc_refs.resolved_refs
    type_deps.same_path_refs[type_deps.same_path_refs L4]
    type_deps.same_path_refs --> type_deps.u1
    file_collection[file_collection L0]
    file_collection --> file_data_collection
    decl_refs.value_decl_refs[decl_refs.value_decl_refs L7]
    decl_refs.value_decl_refs --> decl_refs.with_value_refs
    type_deps.combined_refs_to[type_deps.combined_refs_to L7]
    type_deps.combined_refs_to --> type_deps.all_type_refs_from
    type_deps.all_type_refs_from[type_deps.all_type_refs_from L8]
    type_deps.all_type_refs_from --> liveness.type_refs_from
    type_deps.impl_needing_path2[type_deps.impl_needing_path2 L4]
    type_deps.impl_needing_path2 --> type_deps.impl_to_intf_refs_path2
    exc_refs.resolved_refs_from[exc_refs.resolved_refs_from L5]
    exc_refs.resolved_refs_from --> liveness.value_refs_from
    exc_refs.resolved_refs[exc_refs.resolved_refs L4]
    exc_refs.resolved_refs --> exc_refs.resolved_refs_from
    type_deps.impl_to_intf_refs_path2[type_deps.impl_to_intf_refs_path2 L5]
    type_deps.impl_to_intf_refs_path2 --> type_deps.u2
    file_deps_map[file_deps_map L2]
    decl_refs.with_value_refs[decl_refs.with_value_refs L8]
    decl_refs.with_value_refs --> decl_refs.combined
    type_deps.u1[type_deps.u1 L5]
    type_deps.u1 --> type_deps.u2
    cross_file_items[cross_file_items L2]
    cross_file_items --> exception_refs_collection
    decl_refs.decls_by_file[decl_refs.decls_by_file L3]
    decl_refs.decls_by_file --> decl_refs.type_decl_refs
    decl_refs.decls_by_file --> decl_refs.value_decl_refs
    type_deps.impl_to_intf_refs[type_deps.impl_to_intf_refs L4]
    type_deps.impl_to_intf_refs --> type_deps.u1
    solver.issues_by_file[solver.issues_by_file L17]
    solver.issues_by_file --> solver.modules_with_reported
    liveness.annotated_roots[liveness.annotated_roots L3]
    liveness.annotated_roots --> liveness.all_roots
    solver.incorrect_dead_decls[solver.incorrect_dead_decls L16]
    type_deps.intf_to_impl_refs[type_deps.intf_to_impl_refs L4]
    type_deps.intf_to_impl_refs --> type_deps.combined_refs_to
    type_deps.decl_by_path[type_deps.decl_by_path L3]
    type_deps.decl_by_path --> type_deps.intf_to_impl_refs
    type_deps.decl_by_path --> type_deps.impl_to_intf_refs_path2
    type_deps.decl_by_path --> type_deps.impl_needing_path2
    type_deps.decl_by_path --> type_deps.impl_to_intf_refs
    type_deps.decl_by_path --> type_deps.same_path_refs
    type_deps.u2[type_deps.u2 L6]
    type_deps.u2 --> type_deps.combined_refs_to
    solver.live_decls[solver.live_decls L15]
    solver.live_decls --> solver.incorrect_dead_decls
    solver.live_decls --> solver.modules_with_live
    type_deps.impl_decls[type_deps.impl_decls L3]
    type_deps.impl_decls --> type_deps.impl_needing_path2
    type_deps.impl_decls --> type_deps.impl_to_intf_refs
    liveness.all_roots[liveness.all_roots L12]
    liveness.all_roots --> liveness.live
    solver.dead_modules[solver.dead_modules L17]
    solver.dead_modules --> solver.dead_module_issues
    liveness.external_type_refs[liveness.external_type_refs L10]
    liveness.external_type_refs --> liveness.externally_referenced
    decl_refs.combined[decl_refs.combined L12]
    decl_refs.combined --> liveness.edges
    type_refs_from[type_refs_from L2]
    type_refs_from --> liveness.type_refs_from
    liveness.type_refs_from[liveness.type_refs_from L9]
    liveness.type_refs_from --> liveness.external_type_refs
    liveness.type_refs_from --> decl_refs.type_decl_refs
    solver.dead_decls_by_file[solver.dead_decls_by_file L16]
    solver.dead_decls_by_file --> solver.issues_by_file
    liveness.external_value_refs[liveness.external_value_refs L7]
    liveness.external_value_refs --> liveness.externally_referenced
    liveness.value_refs_from[liveness.value_refs_from L6]
    liveness.value_refs_from --> liveness.external_value_refs
    liveness.value_refs_from --> decl_refs.value_decl_refs
    value_refs_from[value_refs_from L2]
    value_refs_from --> liveness.value_refs_from
    solver.modules_with_dead[solver.modules_with_dead L16]
    solver.modules_with_dead --> solver.dead_modules
    solver.dead_decls[solver.dead_decls L15]
    solver.dead_decls --> solver.dead_decls_by_file
    solver.dead_decls --> solver.modules_with_dead
    exception_refs_collection[exception_refs_collection L3]
    exception_refs_collection --> exc_refs.resolved_refs
    type_deps.intf_decls[type_deps.intf_decls L3]
    type_deps.intf_decls --> type_deps.intf_to_impl_refs
    file_data_collection[file_data_collection L1]
    file_data_collection --> files
    file_data_collection --> file_deps_map
    file_data_collection --> cross_file_items
    file_data_collection --> type_refs_from
    file_data_collection --> value_refs_from
    file_data_collection --> annotations
    file_data_collection --> decls
    solver.dead_module_issues[solver.dead_module_issues L19]
    decl_refs.with_type_refs[decl_refs.with_type_refs L11]
    decl_refs.with_type_refs --> decl_refs.combined
    solver.modules_with_live[solver.modules_with_live L16]
    solver.modules_with_live --> solver.dead_modules
    decl_refs.type_decl_refs[decl_refs.type_decl_refs L10]
    decl_refs.type_decl_refs --> decl_refs.with_type_refs
    files[files L2]
    solver.modules_with_reported[solver.modules_with_reported L18]
    solver.modules_with_reported --> solver.dead_module_issues
    liveness.externally_referenced[liveness.externally_referenced L11]
    liveness.externally_referenced --> liveness.all_roots
    liveness.edges[liveness.edges L13]
    liveness.edges --> liveness.live
    liveness.live[liveness.live L14]
    liveness.live --> solver.live_decls
    liveness.live --> solver.dead_decls
    decls[decls L2]
    decls --> solver.live_decls
    decls --> solver.dead_decls
    decls --> liveness.annotated_roots
    decls --> liveness.external_type_refs
    decls --> liveness.external_value_refs
    decls --> decl_refs.with_type_refs
    decls --> decl_refs.with_value_refs
    decls --> decl_refs.decls_by_file
    decls --> exc_refs.exception_decls
    decls --> type_deps.intf_decls
    decls --> type_deps.impl_decls
    decls --> type_deps.decl_by_path

