// Generated by ReScript, PLEASE EDIT WITH CARE


function Abstract_component_test$PolyVariantLowerBound$make(props) {
  let x = props.x;
  if (x === "a") {
    return "A";
  } else if (x === "b") {
    return "B";
  } else {
    return "other";
  }
}

let PolyVariantLowerBound = {
  make: Abstract_component_test$PolyVariantLowerBound$make
};

function Abstract_component_test$GenericRenderProp$make(props) {
  return props.render(props.x);
}

let GenericRenderProp = {
  make: Abstract_component_test$GenericRenderProp$make
};

export {
  PolyVariantLowerBound,
  GenericRenderProp,
  Abstract_component_test$PolyVariantLowerBound$make,
  Abstract_component_test$GenericRenderProp$make,
}
/* No side effect */
