// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function makeContainer(text) {
  let container = document.createElement("div");
  container.className = "container";
  let title = document.createElement("div");
  title.className = "containerTitle";
  title.innerText = text;
  let content = document.createElement("div");
  content.className = "containerContent";
  container.appendChild(title);
  container.appendChild(content);
  document.body.appendChild(container);
  return content;
}

function Gpr_3987_test$Gpr3987ReproOk$make(props) {
  return null;
}

let Gpr3987ReproOk = {
  make: Gpr_3987_test$Gpr3987ReproOk$make
};

JsxRuntime.jsx(Gpr_3987_test$Gpr3987ReproOk$make, {
  value: "test",
  onChange: (param, param$1) => {}
});

function Gpr_3987_test$Gpr3987ReproOk2$make(props) {
  return null;
}

let Gpr3987ReproOk2 = {
  make: Gpr_3987_test$Gpr3987ReproOk2$make
};

JsxRuntime.jsx(Gpr_3987_test$Gpr3987ReproOk2$make, {
  value: "test",
  onChange: (param, param$1) => {}
});

function Gpr_3987_test$Gpr3987ReproError$make(props) {
  return null;
}

let Gpr3987ReproError = {
  make: Gpr_3987_test$Gpr3987ReproError$make
};

JsxRuntime.jsx(Gpr_3987_test$Gpr3987ReproError$make, {
  value: "test",
  onChange: (param, param$1) => {}
});

export {
  makeContainer,
  Gpr3987ReproOk,
  Gpr3987ReproOk2,
  Gpr3987ReproError,
  Gpr_3987_test$Gpr3987ReproOk$make,
  Gpr_3987_test$Gpr3987ReproOk2$make,
  Gpr_3987_test$Gpr3987ReproError$make,
}
/*  Not a pure module */
