// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Foo from "Foo";

let React = {};

let Test = {};

function test(className) {
  return Foo;
}

let Gpr_3695_test$Test = Foo;

export {
  React,
  Test,
  test,
  Gpr_3695_test$Test,
}
/* Gpr_3695_test$Test Not a pure module */
