// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Issue_7917_test$M(props) {
  return null;
}

let M = {
  make: Issue_7917_test$M
};

function Issue_7917_test(props) {
  let __component = props.component;
  let __component_value = __component !== undefined ? __component : M;
  return JsxRuntime.jsx(__component_value.make, {});
}

let make = Issue_7917_test;

export {
  make,
  Issue_7917_test$M,
}
/* react/jsx-runtime Not a pure module */
