// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(param) {
  return React.createElement(make, {
    foo: param.foo - 1 | 0
  });
}

let Recursive_explicit_component_test$SelfCreateElement = make;

let SelfCreateElement = {
  make: Recursive_explicit_component_test$SelfCreateElement
};

function other(param) {
  return param.foo.toString();
}

function Recursive_explicit_component_test$RawSiblingCreateElement(props) {
  return React.createElement(other, {
    foo: props.foo
  });
}

let RawSiblingCreateElement = {
  other: other,
  make: Recursive_explicit_component_test$RawSiblingCreateElement
};

function make$1(props) {
  if (props.foo <= 0) {
    return null;
  } else {
    return React.createElement(make$1, {
      foo: props.foo - 1 | 0
    });
  }
}

let Recursive_explicit_component_test$ComponentWithProps = make$1;

let ComponentWithProps = {
  make: Recursive_explicit_component_test$ComponentWithProps
};

let componentWithPropsElement = React.createElement(Recursive_explicit_component_test$ComponentWithProps, {
  foo: 1
});

export {
  SelfCreateElement,
  RawSiblingCreateElement,
  ComponentWithProps,
  componentWithPropsElement,
}
/* componentWithPropsElement Not a pure module */
