// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as A from "./A.js";

export type element = number;

export function sortedLengthAuxMore(
  xs: element[],
  prec: element,
  acc: number,
  len: number,
): number;

export function sortedLengthAuxLess(
  xs: element[],
  prec: element,
  acc: number,
  len: number,
): number;

export function strictlySortedLength(xs: element[]): number;

export function isSortedAux(
  a: element[],
  i: number,
  last_bound: number,
): boolean;

export function isSorted(a: A.t<element>): boolean;

export const cutoff: number;

export function merge(
  src: element[],
  src1ofs: number,
  src1len: number,
  src2: A.t<element>,
  src2ofs: number,
  src2len: number,
  dst: A.t<element>,
  dstofs: number,
): void;

export function union(
  src: element[],
  src1ofs: number,
  src1len: number,
  src2: A.t<element>,
  src2ofs: number,
  src2len: number,
  dst: A.t<element>,
  dstofs: number,
): number;

export function intersect(
  src: element[],
  src1ofs: number,
  src1len: number,
  src2: A.t<element>,
  src2ofs: number,
  src2len: number,
  dst: A.t<element>,
  dstofs: number,
): number;

export function diff(
  src: element[],
  src1ofs: number,
  src1len: number,
  src2: A.t<element>,
  src2ofs: number,
  src2len: number,
  dst: A.t<element>,
  dstofs: number,
): number;

export function insertionSort(
  src: element[],
  srcofs: number,
  dst: A.t<element>,
  dstofs: number,
  len: number,
): void;

export function sortTo(
  src: element[],
  srcofs: number,
  dst: A.t<element>,
  dstofs: number,
  len: number,
): void;

export function stableSortInPlace(a: element[]): void;

export function stableSort(a: A.t<element>): A.t<element>;

export function binarySearchAux(
  arr: element[],
  lo: number,
  hi: number,
  key: element,
): number;

export function binarySearch(sorted: element[], key: element): number;