// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as A from "./A.js";
import type * as C from "./C.js";
import type * as N from "./N.js";

export type key = string;

export type seed = number;

export type t = N.t<void, void, key>;

export function hash(s: key): seed;

export function copyBucket(
  h_buckets: A.t<C.opt<N.bucket<key>>>,
  ndata_tail: A.t<C.opt<N.bucket<key>>>,
  old_bucket: C.opt<N.bucket<key>>,
): void;

export function tryDoubleResize<A, B>(h: C.container<A, B, N.bucket<key>>): void;

export function removeBucket<A, B, C, D, E>(
  h: C.container<A, B, C>,
  h_buckets: D,
  i: E,
  key: key,
  prec: N.bucket<key>,
  cell: N.bucket<key>,
): void;

export function remove<A, B>(
  h: C.container<A, B, N.bucket<key>>,
  key: key,
): void;

export function addBucket<A, B, C>(
  h: C.container<A, B, C>,
  key: key,
  cell: N.bucket<key>,
): void;

export function add<A, B>(h: C.container<A, B, N.bucket<key>>, key: key): void;

export function memInBucket(key: key, cell: N.bucket<key>): boolean;

export function has<A, B>(
  h: C.container<A, B, N.bucket<key>>,
  key: key,
): boolean;

export function make<A>(hintSize: number): C.container<void, void, A>;

export function clear<A, B, C>(arg0: C.container<A, B, C>): void;

export function size<A, B, C>(h: C.container<A, B, C>): number;

export function forEach<A, B, C>(
  arg0: N.t<A, B, C>,
  arg1: (arg0: C) => void,
): void;

export function reduce<A, B, C, D>(
  arg0: N.t<A, B, C>,
  arg1: D,
  arg2: (arg0: D, arg1: C) => D,
): D;

export function logStats<A, B, C>(arg0: N.t<A, B, C>): void;

export function toArray<A, B, C>(arg0: N.t<A, B, C>): C[];

export function copy<A, B, C>(arg0: N.t<A, B, C>): N.t<A, B, C>;

export function getBucketHistogram<A, B, C>(arg0: N.t<A, B, C>): number[];

export function isEmpty<A, B, C>(arg0: C.container<A, B, C>): boolean;

export function fromArray(
  arr: A.t<key>,
): C.container<void, void, N.bucket<key>>;

export function mergeMany<A, B>(
  h: C.container<A, B, N.bucket<key>>,
  arr: A.t<key>,
): void;

export function forEachU<A, B, C>(
  arg0: N.t<A, B, C>,
  arg1: (arg0: C) => void,
): void;

export function reduceU<A, B, C, D>(
  arg0: N.t<A, B, C>,
  arg1: D,
  arg2: (arg0: D, arg1: C) => D,
): D;