// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as A from "./A.js";
import type * as C from "./C.js";

export interface bucket<A> {
  key: A;
  next: C.opt<bucket<A>>;
}

export type t<Hash, Eq, A> = C.container<Hash, Eq, bucket<A>>;

export function copy<A, B, C>(x: t<A, B, C>): t<A, B, C>;

export function copyBuckets<A>(
  buckets: C.opt<bucket<A>>[],
): A.t<C.opt<bucket<A>>>;

export function copyBucket<A>(c: C.opt<bucket<A>>): C.opt<bucket<A>>;

export function copyAuxCont<A>(c: C.opt<bucket<A>>, prec: bucket<A>): void;

export function bucketLength<A>(
  accu: number,
  buckets: C.opt<bucket<A>>,
): number;

export function doBucketIter<A>(
  f: (arg0: A) => void,
  buckets: C.opt<bucket<A>>,
): void;

export function forEach<A, B, C>(
  h: C.container<A, B, bucket<C>>,
  f: (arg0: C) => void,
): void;

export function fillArray<A>(i: number, arr: A.t<A>, cell: bucket<A>): number;

export function toArray<A, B, C>(h: C.container<A, B, bucket<C>>): A.t<C>;

export function doBucketFold<A, B>(
  f: (arg0: A, arg1: B) => A,
  b: C.opt<bucket<B>>,
  accu: A,
): A;

export function reduce<A, B, C, D>(
  h: C.container<A, B, bucket<C>>,
  init: D,
  f: (arg0: D, arg1: C) => D,
): D;

export function getMaxBucketLength<A, B, C>(
  h: C.container<A, B, bucket<C>>,
): number;

export function getBucketHistogram<A, B, C>(
  h: C.container<A, B, bucket<C>>,
): A.t<number>;

export function logStats<A, B, C>(h: C.container<A, B, bucket<C>>): void;