// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as A from "./A.js";
import type * as Belt_Id from "./Belt_Id.js";
import type * as N from "./N.js";

export type id<Key, Id> = Belt_Id.comparable<Key, Id>;

export type cmp<Key, Id> = Belt_Id.cmp<Key, Id>;

export interface t<K, V, Id> {
  readonly cmp: cmp<K, Id>;
  data: N.t<K, V>;
}

export function removeMutateAux<A, B, C>(
  nt: N.node<A, B>,
  x: A,
  cmp: Belt_Id.cmp<A, C>,
): N.t<A, B>;

export function remove<A, B, C>(d: t<A, B, C>, k: A): void;

export function removeArrayMutateAux<A, B, C>(
  t: N.node<A, B>,
  xs: A.t<A>,
  i: number,
  len: number,
  cmp: Belt_Id.cmp<A, C>,
): rescript.option<N.node<A, B>>;

export function removeMany<A, B, C>(d: t<A, B, C>, xs: A.t<A>): void;

export function updateDone<A, B, C>(
  t: N.t<A, B>,
  x: A,
  f: (arg0: rescript.option<B>) => rescript.option<B>,
  cmp: Belt_Id.cmp<A, C>,
): N.t<A, B>;

export function update<A, B, C>(
  t: t<A, B, C>,
  x: A,
  f: (arg0: rescript.option<B>) => rescript.option<B>,
): void;

export function make<A, B, C>(id: id<A, B>): t<A, C, B>;

export function clear<A, B, C>(m: t<A, B, C>): void;

export function isEmpty<A, B, C>(d: t<A, B, C>): boolean;

export function minKey<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function minKeyUndefined<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function maxKey<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function maxKeyUndefined<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function minimum<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function minUndefined<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function maximum<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function maxUndefined<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function forEach<A, B, C>(
  d: t<A, B, C>,
  f: (arg0: A, arg1: B) => void,
): void;

export function reduce<A, B, C, D>(
  d: t<A, B, C>,
  acc: D,
  cb: (arg0: D, arg1: A, arg2: B) => D,
): D;

export function every<A, B, C>(
  d: t<A, B, C>,
  p: (arg0: A, arg1: B) => boolean,
): boolean;

export function some<A, B, C>(
  d: t<A, B, C>,
  p: (arg0: A, arg1: B) => boolean,
): boolean;

export function size<A, B, C>(d: t<A, B, C>): number;

export function toList<A, B, C>(d: t<A, B, C>): rescript.list<[A, B]>;

export function toArray<A, B, C>(d: t<A, B, C>): [A, B][];

export function keysToArray<A, B, C>(d: t<A, B, C>): A[];

export function valuesToArray<A, B, C>(d: t<A, B, C>): B[];

export function checkInvariantInternal<A, B, C>(d: t<A, B, C>): void;

export function cmp<A, B, C, D, E>(
  m1: t<A, B, C>,
  m2: t<A, D, E>,
  cmp: (arg0: B, arg1: D) => number,
): number;

export function eq<A, B, C, D, E>(
  m1: t<A, B, C>,
  m2: t<A, D, E>,
  cmp: (arg0: B, arg1: D) => boolean,
): boolean;

export function map<A, B, C, D>(
  m: t<A, B, C>,
  f: (arg0: B) => D,
): t<A, D, C>;

export function mapWithKey<A, B, C, D>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => D,
): t<A, D, C>;

export function get_<A, B, C>(m: t<A, B, C>, x: A): rescript.option<B>;

export function getUndefined<A, B, C>(m: t<A, B, C>, x: A): rescript.option<B>;

export function getWithDefault<A, B, C>(m: t<A, B, C>, x: A, def: B): B;

export function getOrThrow<A, B, C>(m: t<A, B, C>, x: A): B;

export function getExn<A, B, C>(arg0: t<A, B, C>, arg1: A): B;

export function has<A, B, C>(m: t<A, B, C>, x: A): boolean;

export function fromArray<A, B, C>(
  data: [A, B][],
  id: id<A, C>,
): t<A, B, C>;

export function set_<A, B, C>(m: t<A, B, C>, e: A, v: B): void;

export function mergeManyAux<A, B, C>(
  t: N.t<A, B>,
  xs: A.t<[A, B]>,
  cmp: N.cmp<A, C>,
): N.t<A, B>;

export function mergeMany<A, B, C>(d: t<A, B, C>, xs: A.t<[A, B]>): void;

export function cmpU<A, B, C, D, E>(
  arg0: t<A, B, C>,
  arg1: t<A, D, E>,
  arg2: (arg0: B, arg1: D) => number,
): number;

export function eqU<A, B, C, D, E>(
  arg0: t<A, B, C>,
  arg1: t<A, D, E>,
  arg2: (arg0: B, arg1: D) => boolean,
): boolean;

export function everyU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): boolean;

export function forEachU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => void,
): void;

export function mapU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: (arg0: B) => D,
): t<A, D, C>;

export function mapWithKeyU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => D,
): t<A, D, C>;

export function reduceU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: D,
  arg2: (arg0: D, arg1: A, arg2: B) => D,
): D;

export function someU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): boolean;

export function updateU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: A,
  arg2: (arg0: rescript.option<B>) => rescript.option<B>,
): void;