// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as Dom_storage2 from "./Dom_storage2.js";

export type t = Dom_storage2.t;

export function getItem(s: string, obj: t): rescript.option<string>;

export function setItem(k: string, v: string, obj: t): void;

export function removeItem(s: string, obj: t): void;

export function key(i: number, obj: t): rescript.option<string>;