// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export interface cell<A> {
  readonly content: A;
  next: rescript.option<cell<A>>;
}

export interface t<A> {
  length: number;
  first: rescript.option<cell<A>>;
  last: rescript.option<cell<A>>;
}

export function create_queue<A>(): t<A>;

export function push_back<A>(q: t<A>, v: A): void;

export function is_empty_queue<A>(q: t<A>): boolean;

export function unsafe_pop<A>(q: t<A>): A;

export function rotl32(x: number, n: number): number;

export function hash_mix_int(h: number, d: number): number;

export function hash_final_mix(h: number): number;

export function hash_mix_string(h: number, s: string): number;

export function hash<A>(
  count: number,
  _limit: A,
  seed: number,
  obj: any,
): number;