// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as Lazy from "./Lazy.js";
import type * as Primitive_js_extern from "./Primitive_js_extern.js";

export type date = Date;

export type null<A> = Primitive_js_extern.null<A>;

export type undefined<A> = Primitive_js_extern.undefined<A>;

export type nullable<A> = Primitive_js_extern.nullable<A>;

export type lazy_t<A> = Lazy.t<A>;

export function panic<A>(arg0: string): A;

export function assertEqual<A>(a: A, b: A): void;