// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as Stdlib_Symbol from "./Stdlib_Symbol.js";

export type t = 
  | "undefined"
  | "symbol"
  | "bigint"
  | "object"
  | "function"
  | "string"
  | "number"
  | "boolean";

declare namespace Classify {
  type function = rescript.opaque<"Stdlib_Type.Classify.function", []>;
  type object = rescript.opaque<"Stdlib_Type.Classify.object", []>;
  type t = | { readonly TAG: "Bool"; readonly _0: boolean } | "Null" | "Undefined" | { readonly TAG: "String"; readonly _0: string } | { readonly TAG: "Number"; readonly _0: number } | { readonly TAG: "Object"; readonly _0: Classify.object } | { readonly TAG: "Function"; readonly _0: Classify.function } | { readonly TAG: "Symbol"; readonly _0: Stdlib_Symbol.t } | { readonly TAG: "BigInt"; readonly _0: bigint };
}
export type Classify = {
  _internalClass: (arg0: A) => string;
  _asBool: (arg0: A) => boolean;
  _asString: (arg0: A) => string;
  _asFloat: (arg0: A) => number;
  _asObject: (arg0: A) => Classify.object;
  _asFunction: (arg0: A) => Classify.function;
  _asSymbol: (arg0: A) => Stdlib_Symbol.t;
  _asBigInt: (arg0: A) => bigint;
  classify: (arg0: any) => Classify.t;
};
export const Classify: Classify;