// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export type t = unknown;

export type error = rescript.opaque<"Stdlib_Exn.error", []>;

export type eval_error = rescript.opaque<"Stdlib_Exn.eval_error", []>;

export type range_error = rescript.opaque<"Stdlib_Exn.range_error", []>;

export type reference_error = rescript.opaque<"Stdlib_Exn.reference_error", []>;

export type syntax_error = rescript.opaque<"Stdlib_Exn.syntax_error", []>;

export type type_error = rescript.opaque<"Stdlib_Exn.type_error", []>;

export type uri_error = rescript.opaque<"Stdlib_Exn.uri_error", []>;

export function asJsExn(exn: exn): rescript.option<t>;

export function raiseError<A>(str: string): A;

export function raiseEvalError<A>(str: string): A;

export function raiseRangeError<A>(str: string): A;

export function raiseReferenceError<A>(str: string): A;

export function raiseSyntaxError<A>(str: string): A;

export function raiseTypeError<A>(str: string): A;

export function raiseUriError<A>(str: string): A;