// Generated by ReScript, PLEASE EDIT WITH CARE

export type Constants = {
  e: number;
  ln2: number;
  ln10: number;
  log2e: number;
  log10e: number;
  pi: number;
  sqrt1_2: number;
  sqrt2: number;
};
export const Constants: Constants;

export type Int = {
  abs: (arg0: number) => number;
  clz32: (arg0: number) => number;
  imul: (arg0: number, arg1: number) => number;
  min: (arg0: number, arg1: number) => number;
  minMany: (arg0: number[]) => number;
  max: (arg0: number, arg1: number) => number;
  maxMany: (arg0: number[]) => number;
  pow: (arg0: number, exp: number) => number;
  sign: (arg0: number) => number;
  floor: (arg0: number) => number;
  ceil: (arg0: number) => number;
  random: (arg0: number, arg1: number) => number;
};
export const Int: Int;