// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export type t<A> = rescript.option<A>;

export function filter<A>(opt: t<A>, p: (arg0: A) => boolean): t<A>;

export function forEach<A>(opt: t<A>, f: (arg0: A) => void): void;

export function getOrThrow<A>(x: t<A>, message?: string): A;

export function getExn<A>(arg0: t<A>, message?: string): A;

export function mapOr<A, B>(opt: t<A>, default_: B, f: (arg0: A) => B): B;

export function mapWithDefault<A, B>(
  arg0: t<A>,
  arg1: B,
  arg2: (arg0: A) => B,
): B;

export function map<A, B>(opt: t<A>, f: (arg0: A) => B): t<B>;

export function flatMap<A, B>(opt: t<A>, f: (arg0: A) => t<B>): t<B>;

export function getOr<A>(opt: t<A>, default_: A): A;

export function getWithDefault<A>(arg0: t<A>, arg1: A): A;

export function orElse<A>(opt: t<A>, other: t<A>): t<A>;

export function isSome<A>(x: t<A>): boolean;

export function isNone<A>(x: t<A>): boolean;

export function equal<A, B>(
  a: t<A>,
  b: t<B>,
  eq: (arg0: A, arg1: B) => boolean,
): boolean;

export function compare<A, B>(
  a: t<A>,
  b: t<B>,
  cmp: (arg0: A, arg1: B) => number,
): number;

export function all<A>(options: t<A>[]): t<A[]>;

export function all2<A, B>(param: [t<A>, t<B>]): t<[A, B]>;

export function all3<A, B, C>(param: [t<A>, t<B>, t<C>]): t<[A, B, C]>;

export function all4<A, B, C, D>(
  param: [t<A>, t<B>, t<C>, t<D>],
): t<[A, B, C, D]>;

export function all5<A, B, C, D, E>(
  param: [t<A>, t<B>, t<C>, t<D>, t<E>],
): t<[A, B, C, D, E]>;

export function all6<A, B, C, D, E, F>(
  param: [t<A>, t<B>, t<C>, t<D>, t<E>, t<F>],
): t<[A, B, C, D, E, F]>;