// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactAriaComponents from "react-aria-components";

let x = ReactAriaComponents.useTableOptions().selectionMode;

export {
  x,
}
/* x Not a pure module */
