// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

async function loadCondANone() {
  let M = await import("./cond_a_none.mjs");
  return M.A.u;
}

async function raisesAssertFailure(load) {
  try {
    await load();
    return false;
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "Assert_failure") {
      return true;
    }
    throw exn;
  }
}

Mocha.describe("Cond_a_load_test", () => {
  Mocha.test("cond_a loads as a module whose body throws Assert_failure", async () => {
    let ok = await raisesAssertFailure(() => import("./cond_a.mjs").then(m => m.u));
    if (!ok) {
      return Pervasives.failwith("cond_a did not throw Assert_failure on load");
    }
  });
  Mocha.test("cond_a_none loads as a module whose body throws Assert_failure", async () => {
    let ok = await raisesAssertFailure(loadCondANone);
    if (!ok) {
      return Pervasives.failwith("cond_a_none did not throw Assert_failure on load");
    }
  });
});

export {
  loadCondANone,
  raisesAssertFailure,
}
/*  Not a pure module */
