// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptSchema from "rescript-schema/src/S.mjs";

let schema = S$RescriptSchema.schema(s => ({
  foo: s.m(S$RescriptSchema.string)
}));

let foo = S$RescriptSchema.parseOrThrow("{ \"foo\": \"bar\" }", schema);

console.log(foo);

export {
  schema,
  foo,
}
/* schema Not a pure module */
