// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Sury from "sury";

let schema = Sury.$res_schema(s => ({
  foo: s.m(Sury.string)
}));

let foo = S.parseOrThrow(`{ "foo": "bar" }`, schema);

console.log(foo);

export {
  schema,
  foo,
}
/* schema Not a pure module */
