// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_Option = require("rescript/lib/js/Belt_Option.js");

function testTuple(param) {
  return param[0] + param[1] | 0;
}

function computeArea(param) {
  return (param[0] * param[1] | 0) * Belt_Option.mapWithDefault(param[2], 1, n => n) | 0;
}

function computeAreaWithIdent(param) {
  return (param[0] * param[1] | 0) * Belt_Option.mapWithDefault(param[2], 1, n => n) | 0;
}

function computeAreaNoConverters(param) {
  return param[0] * param[1] | 0;
}

function coord2d(x, y) {
  return [
    x,
    y,
    undefined
  ];
}

function getFirstName(param) {
  return param[0].name;
}

function marry(first, second) {
  return [
    first,
    second
  ];
}

function changeSecondAge(param) {
  let second = param[1];
  return [
    param[0],
    {
      name: second.name,
      age: second.age + 1 | 0
    }
  ];
}

let origin = [
  0,
  0,
  0
];

exports.testTuple = testTuple;
exports.origin = origin;
exports.computeArea = computeArea;
exports.computeAreaWithIdent = computeAreaWithIdent;
exports.computeAreaNoConverters = computeAreaNoConverters;
exports.coord2d = coord2d;
exports.getFirstName = getFirstName;
exports.marry = marry;
exports.changeSecondAge = changeSecondAge;
/* No side effect */
