// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "@rescript/belt/lib/es6/src/Belt_Id.mjs";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.mjs";

function cmp(t1, t2) {
  if (t1.TAG === "Leaf") {
    if (t2.TAG === "Leaf") {
      return Primitive_string.compare(t1._0, t2._0);
    } else {
      return 1;
    }
  } else if (t2.TAG === "Leaf") {
    return -1;
  } else {
    return AComparable.cmp(t1._0, t2._0);
  }
}

let A = {
  cmp: cmp
};

let AComparable = Belt_Id.MakeComparable(A);

let X0 = {};

let Y0 = {};

function f(x) {
  return x + 1 | 0;
}

let X1 = {
  f: f
};

function f$1(x) {
  return x + 2 | 0;
}

let Y1 = {
  f: f$1
};

let X;

export {
  A,
  AComparable,
  X,
  X0,
  Y0,
  X1,
  Y1,
}
/* AComparable Not a pure module */
