// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as Belt_Id from "./Belt_Id.js";
import type * as Dict from "./Dict.js";

export type id<Key, Id> = Belt_Id.comparable<Key, Id>;

export type cmp<Key, Id> = Belt_Id.cmp<Key, Id>;

export interface t<K, V, Id> {
  readonly cmp: cmp<K, Id>;
  readonly data: Dict.t<K, V, Id>;
}

export function fromArray<A, B, C>(
  data: [A, B][],
  id: id<A, C>,
): t<A, B, C>;

export function remove<A, B, C>(m: t<A, B, C>, x: A): t<A, B, C>;

export function removeMany<A, B, C>(m: t<A, B, C>, x: A[]): t<A, B, C>;

export function set_<A, B, C>(m: t<A, B, C>, key: A, d: B): t<A, B, C>;

export function mergeMany<A, B, C>(
  m: t<A, B, C>,
  e: [A, B][],
): t<A, B, C>;

export function update<A, B, C>(
  m: t<A, B, C>,
  key: A,
  f: (arg0: rescript.option<B>) => rescript.option<B>,
): t<A, B, C>;

export function split<A, B, C>(
  m: t<A, B, C>,
  x: A,
): [[t<A, B, C>, t<A, B, C>], rescript.option<B>];

export function merge<A, B, C, D, E>(
  s1: t<A, B, C>,
  s2: t<A, D, C>,
  f: (arg0: A, arg1: rescript.option<B>, arg2: rescript.option<D>) => rescript.option<E>,
): t<A, E, C>;

export function make<A, B, C>(id: id<A, B>): t<A, C, B>;

export function isEmpty<A, B, C>(map: t<A, B, C>): boolean;

export function findFirstBy<A, B, C>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => boolean,
): rescript.option<[A, B]>;

export function forEach<A, B, C>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => void,
): void;

export function reduce<A, B, C, D>(
  m: t<A, B, C>,
  acc: D,
  f: (arg0: D, arg1: A, arg2: B) => D,
): D;

export function every<A, B, C>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => boolean,
): boolean;

export function some<A, B, C>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => boolean,
): boolean;

export function keep<A, B, C>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => boolean,
): t<A, B, C>;

export function partition<A, B, C>(
  m: t<A, B, C>,
  p: (arg0: A, arg1: B) => boolean,
): [t<A, B, C>, t<A, B, C>];

export function map<A, B, C, D>(
  m: t<A, B, C>,
  f: (arg0: B) => D,
): t<A, D, C>;

export function mapWithKey<A, B, C, D>(
  m: t<A, B, C>,
  f: (arg0: A, arg1: B) => D,
): t<A, D, C>;

export function size<A, B, C>(map: t<A, B, C>): number;

export function toList<A, B, C>(map: t<A, B, C>): rescript.list<[A, B]>;

export function toArray<A, B, C>(m: t<A, B, C>): [A, B][];

export function keysToArray<A, B, C>(m: t<A, B, C>): A[];

export function valuesToArray<A, B, C>(m: t<A, B, C>): B[];

export function minKey<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function minKeyUndefined<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function maxKey<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function maxKeyUndefined<A, B, C>(m: t<A, B, C>): rescript.option<A>;

export function minimum<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function minUndefined<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function maximum<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function maxUndefined<A, B, C>(m: t<A, B, C>): rescript.option<[A, B]>;

export function get_<A, B, C>(map: t<A, B, C>, x: A): rescript.option<B>;

export function getUndefined<A, B, C>(map: t<A, B, C>, x: A): rescript.option<B>;

export function getWithDefault<A, B, C>(map: t<A, B, C>, x: A, def: B): B;

export function getOrThrow<A, B, C>(map: t<A, B, C>, x: A): B;

export function getExn<A, B, C>(arg0: t<A, B, C>, arg1: A): B;

export function has<A, B, C>(map: t<A, B, C>, x: A): boolean;

export function checkInvariantInternal<A, B, C>(m: t<A, B, C>): void;

export function eq<A, B, C>(
  m1: t<A, B, C>,
  m2: t<A, B, C>,
  veq: (arg0: B, arg1: B) => boolean,
): boolean;

export function cmp<A, B, C>(
  m1: t<A, B, C>,
  m2: t<A, B, C>,
  vcmp: (arg0: B, arg1: B) => number,
): number;

export function getData<A, B, C>(m: t<A, B, C>): Dict.t<A, B, C>;

export function getId<A, B, C>(m: t<A, B, C>): id<A, C>;

export function packIdData<A, B, C>(
  id: id<A, B>,
  data: Dict.t<A, C, B>,
): t<A, C, B>;

export function cmpU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: t<A, B, C>,
  arg2: (arg0: B, arg1: B) => number,
): number;

export function eqU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: t<A, B, C>,
  arg2: (arg0: B, arg1: B) => boolean,
): boolean;

export function everyU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): boolean;

export function findFirstByU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): rescript.option<[A, B]>;

export function forEachU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => void,
): void;

export function keepU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): t<A, B, C>;

export function mapU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: (arg0: B) => D,
): t<A, D, C>;

export function mapWithKeyU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => D,
): t<A, D, C>;

export function mergeU<A, B, C, D, E>(
  arg0: t<A, B, C>,
  arg1: t<A, D, C>,
  arg2: (arg0: A, arg1: rescript.option<B>, arg2: rescript.option<D>) => rescript.option<E>,
): t<A, E, C>;

export function partitionU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): [t<A, B, C>, t<A, B, C>];

export function reduceU<A, B, C, D>(
  arg0: t<A, B, C>,
  arg1: D,
  arg2: (arg0: D, arg1: A, arg2: B) => D,
): D;

export function someU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: (arg0: A, arg1: B) => boolean,
): boolean;

export function updateU<A, B, C>(
  arg0: t<A, B, C>,
  arg1: A,
  arg2: (arg0: rescript.option<B>) => rescript.option<B>,
): t<A, B, C>;