// Generated by ReScript, PLEASE EDIT WITH CARE

export type t = char;

export function escaped(param: t): string;

export function lowercase_ascii(c: t): t;

export function uppercase_ascii(c: t): t;

export function compare(c1: t, c2: t): number;

export function equal(c1: t, c2: t): boolean;