// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as Stdlib_Symbol from "./Stdlib_Symbol.js";
import type * as Stdlib_Type from "./Stdlib_Type.js";

export type symbol = Stdlib_Symbol.t;

export type obj_val = Stdlib_Type.Classify.object;

export type undefined_val = rescript.opaque<"Js_types.undefined_val", []>;

export type null_val = rescript.opaque<"Js_types.null_val", []>;

export type function_val = Stdlib_Type.Classify.function;

export type t$Undefined = "Undefined";
export type t$Null = "Null";
export type t$Boolean = "Boolean";
export type t$Number = "Number";
export type t$String = "String";
export type t$Function = "Function";
export type t$Object = "Object";
export type t$Symbol = "Symbol";
export type t$BigInt = "BigInt";
export type t<_ extends undefined_val | null_val | boolean | number | string | function_val | obj_val | symbol | bigint> =
  | t$Undefined
  | t$Null
  | t$Boolean
  | t$Number
  | t$String
  | t$Function
  | t$Object
  | t$Symbol
  | t$BigInt;

export type tagged_t =
  | "JSFalse"
  | "JSTrue"
  | "JSNull"
  | "JSUndefined"
  | { readonly TAG: "JSNumber"; readonly _0: number }
  | { readonly TAG: "JSString"; readonly _0: string }
  | { readonly TAG: "JSFunction"; readonly _0: function_val }
  | { readonly TAG: "JSObject"; readonly _0: obj_val }
  | { readonly TAG: "JSSymbol"; readonly _0: symbol }
  | { readonly TAG: "JSBigInt"; readonly _0: bigint };

export function classify<A>(x: A): tagged_t;

export function test<A, A>(x: A, v: t<A>): boolean;