// Generated by ReScript, PLEASE EDIT WITH CARE

export type shape =
  | "Function"
  | "Lazy"
  | "Class"
  | { readonly TAG: "Module"; readonly _0: [shape, string][] }
  | { readonly TAG: "Value"; readonly _0: any };

export function init(loc: [string, number, number], shape: shape): any;

export function update(shape: shape, o: any, n: any): void;