// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export type t = rescript.opaque<"Stdlib_Intl_Segments.t", []>;

export interface segmentData {
  readonly segment: string;
  readonly index: number;
  readonly isWordLike: rescript.option<boolean>;
  readonly input: string;
}