// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";
import type * as Stdlib_Intl_Common from "./Stdlib_Intl_Common.js";

export type t = rescript.opaque<"Stdlib_Intl_Collator.t", []>;

export type usage = 
  | "search"
  | "sort";

export type sensitivity = 
  | "variant"
  | "accent"
  | "case"
  | "base";

export type caseFirst = 
  | "lower"
  | "false"
  | "upper";

export interface options {
  readonly localeMatcher?: rescript.option<Stdlib_Intl_Common.localeMatcher>;
  readonly usage?: rescript.option<usage>;
  readonly sensitivity?: rescript.option<sensitivity>;
  readonly ignorePunctuation?: rescript.option<boolean>;
  readonly numeric?: rescript.option<boolean>;
  readonly caseFirst?: rescript.option<caseFirst>;
}

export interface resolvedOptions {
  readonly locale: string;
  readonly usage: usage;
  readonly sensitivity: sensitivity;
  readonly ignorePunctuation: boolean;
  readonly collation: "compat" | "stroke" | "zhuyin" | "trad" | "eor" | "default" | "pinyin" | "dict" | "phonebk" | "phonetic" | "unihan" | "emoji";
  readonly numeric?: rescript.option<boolean>;
  readonly caseFirst?: rescript.option<caseFirst>;
}

export interface supportedLocalesOptions {
  readonly localeMatcher: Stdlib_Intl_Common.localeMatcher;
}