// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export type t<A> = AsyncIterator<A>;

export interface value<A> {
  readonly done: boolean;
  readonly value: rescript.option<A>;
}

export function value<A>(v: A): value<A>;

export function done<A>(finalValue?: A): value<A>;

export function forEach<A>(
  iterator: t<A>,
  f: (arg0: rescript.option<A>) => void,
): Promise<void>;

export function make<Value>(arg0: () => Promise<value<Value>>): t<Value>;