// Generated by ReScript, PLEASE EDIT WITH CARE

import type * as rescript from "@rescript/runtime/types";

export type timeoutId = rescript.opaque<"Stdlib_Global.timeoutId", []>;

export type intervalId = rescript.opaque<"Stdlib_Global.intervalId", []>;

export type TimeoutId = {
};
export const TimeoutId: TimeoutId;

export type IntervalId = {
};
export const IntervalId: IntervalId;