// Generated by ReScript, PLEASE EDIT WITH CARE


function Alias_default_value_test$C0(props) {
  let __b = props.b;
  let __a = props.a;
  let __a_value = __a !== undefined ? __a : 2;
  let __b_value = __b !== undefined ? __b : (__a_value << 1);
  return __a_value + __b_value | 0;
}

let C0 = {
  make: Alias_default_value_test$C0
};

function Alias_default_value_test$C1(props) {
  let __foo = props.foo;
  if (__foo !== undefined) {
    return __foo;
  } else {
    return "";
  }
}

let C1 = {
  make: Alias_default_value_test$C1
};

function Alias_default_value_test$C2(props) {
  let __a = props.a;
  let __foo = props.foo;
  let __foo_value = __foo !== undefined ? __foo : "";
  let __a_value = __a !== undefined ? __a : __foo_value;
  return __foo_value + __a_value + props.b;
}

let C2 = {
  make: Alias_default_value_test$C2
};

function Alias_default_value_test$C3(props) {
  let __text = props.text;
  if (__text !== undefined) {
    return __text;
  } else {
    return "Test";
  }
}

let C3 = {
  make: Alias_default_value_test$C3
};

function Alias_default_value_test$C4(props) {
  return props.a;
}

let C4 = {
  make: Alias_default_value_test$C4
};

function Alias_default_value_test$C6(props) {
  return props.comp.xx;
}

let C6 = {
  make: Alias_default_value_test$C6
};

function Alias_default_value_test$C7(props) {
  'use memo';
  let username = props.username;
  let count = props.count;
  let times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  let name = username !== undefined && username !== "" ? username : "Anonymous";
  return `Hello ` + name + `, you clicked me ` + times;
}

let C7 = {
  make: Alias_default_value_test$C7
};

function Alias_default_value_test$C8(props) {
  'use memo';
  return props.count;
}

let C8 = {
  make: Alias_default_value_test$C8
};

export {
  Alias_default_value_test$C0,
  Alias_default_value_test$C1,
  Alias_default_value_test$C2,
  Alias_default_value_test$C3,
  Alias_default_value_test$C4,
  Alias_default_value_test$C6,
  Alias_default_value_test$C7,
  Alias_default_value_test$C8,
}
/* No side effect */
