// Generated by ReScript, PLEASE EDIT WITH CARE


function Alias_default_value_test$C0$make(props) {
  let __b = props.b;
  let __a = props.a;
  let __a_value = __a !== undefined ? __a : 2;
  let __b_value = __b !== undefined ? __b : (__a_value << 1);
  return __a_value + __b_value | 0;
}

let C0 = {
  make: Alias_default_value_test$C0$make
};

function Alias_default_value_test$C1$make(props) {
  let __foo = props.foo;
  if (__foo !== undefined) {
    return __foo;
  } else {
    return "";
  }
}

let C1 = {
  make: Alias_default_value_test$C1$make
};

function Alias_default_value_test$C2$make(props) {
  let __a = props.a;
  let __foo = props.foo;
  let __foo_value = __foo !== undefined ? __foo : "";
  let __a_value = __a !== undefined ? __a : __foo_value;
  return __foo_value + __a_value + props.b;
}

let C2 = {
  make: Alias_default_value_test$C2$make
};

function Alias_default_value_test$C3$make(props) {
  let __text = props.text;
  if (__text !== undefined) {
    return __text;
  } else {
    return "Test";
  }
}

let C3 = {
  make: Alias_default_value_test$C3$make
};

function Alias_default_value_test$C4$make(props) {
  return props.a;
}

let C4 = {
  make: Alias_default_value_test$C4$make
};

function Alias_default_value_test$C6$make(props) {
  return props.comp.xx;
}

let C6 = {
  make: Alias_default_value_test$C6$make
};

function Alias_default_value_test$C7$make(props) {
  'use memo';
  let username = props.username;
  let count = props.count;
  let times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  let name = username !== undefined && username !== "" ? username : "Anonymous";
  return `Hello ` + name + `, you clicked me ` + times;
}

let C7 = {
  make: Alias_default_value_test$C7$make
};

function Alias_default_value_test$C8$make(props) {
  'use memo';
  return props.count;
}

let C8 = {
  make: Alias_default_value_test$C8$make
};

export {
  C0,
  C1,
  C2,
  C3,
  C4,
  C6,
  C7,
  C8,
  Alias_default_value_test$C0$make,
  Alias_default_value_test$C1$make,
  Alias_default_value_test$C2$make,
  Alias_default_value_test$C3$make,
  Alias_default_value_test$C4$make,
  Alias_default_value_test$C6$make,
  Alias_default_value_test$C7$make,
  Alias_default_value_test$C8$make,
}
/* No side effect */
