// Generated by ReScript, PLEASE EDIT WITH CARE


function useABC(x) {
  if (x === "b") {
    return 2;
  } else if (x === "c") {
    return 3;
  } else {
    return 1;
  }
}

function fromString(s) {
  switch (s) {
    case "a" :
    case "b" :
    case "c" :
      return useABC(s);
    default:
      return 0;
  }
}

function useNums(x) {
  if (x === 2) {
    return 20;
  } else {
    return 10;
  }
}

function fromInt(i) {
  if (i !== 2 && i !== 1) {
    return 0;
  } else {
    return useNums(i);
  }
}

function useSingle(x) {
  return x + " world!";
}

function fromString2(s) {
  if (s === "hello") {
    return useSingle(s);
  } else {
    return "unknown";
  }
}

export {
  useABC,
  fromString,
  useNums,
  fromInt,
  useSingle,
  fromString2,
}
/* No side effect */
