// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as AllowMutationPrivateRecord from "./allowMutationPrivateRecord.mjs";

Mocha.describe("AllowMutationPrivateRecord_test", () => {
  Mocha.test("mutates a mutable field exposed by an @allowMutation private record", () => {
    let item = AllowMutationPrivateRecord.make(1);
    item.value = 2;
    Test_utils.eq("File \"allowMutationPrivateRecord_test.res\", line 8, characters 7-14", item.value, 2);
    Test_utils.eq("File \"allowMutationPrivateRecord_test.res\", line 9, characters 7-14", AllowMutationPrivateRecord.value(item), 2);
    Test_utils.eq("File \"allowMutationPrivateRecord_test.res\", line 10, characters 7-14", item.name, "stable");
  });
});

/*  Not a pure module */
