// Generated by ReScript, PLEASE EDIT WITH CARE


function mo(prim0, prim1) {
  return {
    objectMode: false,
    name: prim0,
    someOther: true
  };
}

let options = {
  objectMode: false,
  name: "foo",
  someOther: true
};

function shouldNotFail(objectMode, name) {
  return 3;
}

let x = somescope.somefn({foo:true});

let y = somescope.stringfn(`\x61\u0062`);

export {
  mo,
  options,
  shouldNotFail,
  x,
  y,
}
/* x Not a pure module */
