// Generated by ReScript, PLEASE EDIT WITH CARE


function u(x, y) {
  return x + y | 0;
}

function max2(x, y) {
  return x + y;
}

let hh = 1 + 2;

function f(x) {
  des(x, () => {
    console.log("hei");
  });
}

let h = 3;

export {
  u,
  h,
  max2,
  hh,
  f,
}
/* No side effect */
