// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as Belt_MutableQueue from "@rescript/runtime/lib/es6/Belt_MutableQueue.mjs";
import * as Belt_MutableStack from "@rescript/runtime/lib/es6/Belt_MutableStack.mjs";

function inOrder(v) {
  let current = v;
  let s = Belt_MutableStack.make();
  let q = Belt_MutableQueue.make();
  while (Stdlib_Option.isSome(current)) {
    let v$1 = current;
    Belt_MutableStack.push(s, v$1);
    current = v$1.left;
  };
  while (!Belt_MutableStack.isEmpty(s)) {
    current = Primitive_option.some(Belt_MutableStack.popOrThrow(s));
    let v$2 = current;
    Belt_MutableQueue.add(q, v$2.value);
    current = v$2.right;
    while (Stdlib_Option.isSome(current)) {
      let v$3 = current;
      Belt_MutableStack.push(s, v$3);
      current = v$3.left;
    };
  };
  return Belt_MutableQueue.toArray(q);
}

function inOrder3(v) {
  let current = v;
  let s = Belt_MutableStack.make();
  let q = Belt_MutableQueue.make();
  while (Stdlib_Option.isSome(current)) {
    let v$1 = current;
    Belt_MutableStack.push(s, v$1);
    current = v$1.left;
  };
  Belt_MutableStack.dynamicPopIter(s, popped => {
    Belt_MutableQueue.add(q, popped.value);
    let current = popped.right;
    while (Stdlib_Option.isSome(current)) {
      let v = current;
      Belt_MutableStack.push(s, v);
      current = v.left;
    };
  });
  return Belt_MutableQueue.toArray(q);
}

function n(l, r, a) {
  return {
    value: a,
    left: l,
    right: r
  };
}

let test1 = {
  value: 1,
  left: {
    value: 2,
    left: {
      value: 4,
      left: undefined,
      right: undefined
    },
    right: {
      value: 5,
      left: undefined,
      right: undefined
    }
  },
  right: {
    value: 3,
    left: undefined,
    right: undefined
  }
};

Mocha.describe("Bs_stack_test", () => {
  Mocha.test("tree in-order traversal", () => {
    Test_utils.eq("File \"bs_stack_test.res\", line 79, characters 7-14", inOrder(Primitive_option.some(test1)), [
      4,
      2,
      5,
      1,
      3
    ]);
    Test_utils.eq("File \"bs_stack_test.res\", line 80, characters 7-14", inOrder3(Primitive_option.some(test1)), [
      4,
      2,
      5,
      1,
      3
    ]);
  });
});

let S;

let Q;

export {
  S,
  Q,
  inOrder,
  inOrder3,
  n,
  test1,
}
/*  Not a pure module */
