// Generated by ReScript, PLEASE EDIT WITH CARE


function readUnary(value) {
  let match = value._0;
  return match[0] + match[1] | 0;
}

function readBinary(value) {
  return value._0 + value._1 | 0;
}

function readPoly(value) {
  return value.VAL[0] + value.VAL[1] | 0;
}

let unary = {
  TAG: "Unary",
  _0: [
    1,
    2
  ]
};

let binary = {
  TAG: "Binary",
  _0: 1,
  _1: 2
};

let polyUnary = {
  NAME: "UnaryTuple",
  VAL: [
    1,
    2
  ]
};

let polyBinary = {
  NAME: "BinaryArgs",
  VAL: [
    1,
    2
  ]
};

export {
  unary,
  binary,
  readUnary,
  readBinary,
  polyUnary,
  polyBinary,
  readPoly,
}
/* No side effect */
