// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as Cross_module_inline_export from "./cross_module_inline_export.mjs";

let mapped = 3;

let flatMapped = 4;

let nested = Primitive_option.some(undefined);

let mappedNested = Primitive_option.some(Primitive_option.valFromOption(nested));

function mapValue(opt) {
  if (opt !== undefined) {
    return Primitive_option.some((x => x + 1 | 0)(Primitive_option.valFromOption(opt)));
  }
}

function flatMapValue(opt) {
  if (opt !== undefined) {
    let x = Primitive_option.valFromOption(opt);
    return x + 2 | 0;
  }
}

function forEachValue(opt, f) {
  if (opt !== undefined) {
    return f(Primitive_option.valFromOption(opt));
  }
}

let visited = [];

visited.push(4);

let fromOrdinary = Cross_module_inline_export.ordinary(3, x => x + 1 | 0);

Mocha.describe("cross-module inline opt-in", () => {
  Mocha.test("Option helpers", () => {
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 21, characters 7-14", mapped, 3);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 22, characters 7-14", flatMapped, 4);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 23, characters 7-14", mappedNested, Primitive_option.some(undefined));
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 24, characters 7-14", mapValue(2), 3);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 25, characters 7-14", mapValue(undefined), undefined);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 26, characters 7-14", flatMapValue(2), 4);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 27, characters 7-14", flatMapValue(undefined), undefined);
    visited.push(5);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 29, characters 7-14", visited, [
      4,
      5
    ]);
  });
  Mocha.test("only marked exports are inlined", () => {
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 32, characters 7-14", 4, 4);
    Test_utils.eq("File \"cross_module_inline_opt_in_test.res\", line 33, characters 7-14", fromOrdinary, 4);
  });
});

let fromExport = 4;

export {
  mapped,
  flatMapped,
  nested,
  mappedNested,
  mapValue,
  flatMapValue,
  forEachValue,
  visited,
  fromExport,
  fromOrdinary,
}
/*  Not a pure module */
