// Generated by ReScript, PLEASE EDIT WITH CARE


let $count = 3;

let record$ = {
  count$: 1,
  $count: $count
};

let sum$ = 1 + $count | 0;

let update$ = {
  count$: 5,
  $count: $count
};

function fn$(count$, inc$) {
  return count$ + inc$ | 0;
}

let $ = 1 + $count | 0;

function $$(value$) {
  console.log(value$);
  return value$ + $count | 0;
}

let call$$ = $$($);

let count$ = 1;

export {
  count$,
  $count,
  record$,
  sum$,
  update$,
  fn$,
  $,
  $$,
  call$$,
}
/* call$$ Not a pure module */
