// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Early_return_helper from "./early_return_helper.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

function choose(x) {
  if (x > 0) {
    return 42;
  }
  return 7;
}

function alwaysReturn(x) {
  return x;
}

function identity(x) {
  return x;
}

function inLoops(target) {
  for (let i = 0; i <= 3; ++i) {
    let j = 0;
    loop_0: while (j < 3) {
      j = j + 1 | 0;
      switch (target) {
        case "first" :
          return i + j | 0;
        case "second" :
          if (i === 2) {
            return 20;
          }
          break;
        case "third" :
          continue loop_0;
        default:
          break loop_0;
      }
    };
  }
  return 99;
}

async function returnAsync(early) {
  if (early) {
    return await Promise.resolve(42);
  }
  return 7;
}

function getGadt(v) {
  return v._0;
}

let OperandFailure = /* @__PURE__ */Primitive_exceptions.create("Early_return_test.OperandFailure");

function inTry(fail) {
  try {
    if (!fail) {
      return 42;
    }
    throw {
      RE_EXN_ID: OperandFailure,
      Error: new Error()
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === OperandFailure) {
      return 7;
    }
    throw exn;
  }
}

Mocha.describe("Early_return_test", () => {
  Mocha.test("early and implicit results", () => {
    Test_utils.eq("File \"early_return_test.res\", line 77, characters 7-14", 42, getGadt({
      TAG: "Int",
      _0: 42
    }));
    Test_utils.eq("File \"early_return_test.res\", line 78, characters 7-14", "ok", getGadt({
      TAG: "String",
      _0: "ok"
    }));
    Test_utils.eq("File \"early_return_test.res\", line 79, characters 7-14", 42, choose(1));
    Test_utils.eq("File \"early_return_test.res\", line 80, characters 7-14", 7, choose(0));
    Test_utils.eq("File \"early_return_test.res\", line 81, characters 7-14", 42, identity(42));
    Test_utils.eq("File \"early_return_test.res\", line 82, characters 7-14", "ok", identity("ok"));
  });
  Mocha.test("calls preserve the callee's return boundary", () => {
    Test_utils.eq("File \"early_return_test.res\", line 86, characters 7-14", 43, alwaysReturn(42) + 1 | 0);
    Test_utils.eq("File \"early_return_test.res\", line 87, characters 7-14", 43, Early_return_helper.first(1) + 1 | 0);
    Test_utils.eq("File \"early_return_test.res\", line 88, characters 7-14", 8, Early_return_helper.first(0) + 1 | 0);
    let outer = () => {
      let inner = () => "inner";
      Test_utils.eq("File \"early_return_test.res\", line 91, characters 9-16", "inner", inner());
      return 42;
    };
    Test_utils.eq("File \"early_return_test.res\", line 94, characters 7-14", 42, outer());
    Test_utils.eq("File \"early_return_test.res\", line 95, characters 7-14", 43, (() => 42)() + 1 | 0);
  });
  Mocha.test("return from nested loops and switches", () => {
    Test_utils.eq("File \"early_return_test.res\", line 99, characters 7-14", 1, inLoops("first"));
    Test_utils.eq("File \"early_return_test.res\", line 100, characters 7-14", 20, inLoops("second"));
    Test_utils.eq("File \"early_return_test.res\", line 101, characters 7-14", 99, inLoops("third"));
    Test_utils.eq("File \"early_return_test.res\", line 102, characters 7-14", 99, inLoops("other"));
  });
  Mocha.test("return in while conditions stays in the source function", () => {
    let f = limit => {
      let i = 0;
      while (true) {
        if (i === limit) {
          return i;
        }
        if (i >= 3) {
          break;
        }
        i = i + 1 | 0;
        continue;
      };
      return 99;
    };
    Test_utils.eq("File \"early_return_test.res\", line 119, characters 7-14", 2, f(2));
    Test_utils.eq("File \"early_return_test.res\", line 120, characters 7-14", 99, f(5));
    let outerBreak = early => {
      let i = 0;
      loop_0: while (i < 5) {
        i = i + 1 | 0;
        while (true) {
          if (i === 2) {
            break loop_0;
          }
          if (early) {
            return 42;
          }
          break;
        };
      };
      return i;
    };
    Test_utils.eq("File \"early_return_test.res\", line 139, characters 7-14", 2, outerBreak(false));
    Test_utils.eq("File \"early_return_test.res\", line 140, characters 7-14", 42, outerBreak(true));
  });
  Mocha.test("return is not caught but operand exceptions are", () => {
    Test_utils.eq("File \"early_return_test.res\", line 144, characters 7-14", 42, inTry(false));
    Test_utils.eq("File \"early_return_test.res\", line 145, characters 7-14", 7, inTry(true));
  });
  Mocha.test("expression position preserves evaluation and skips later effects", () => {
    let seen = /* [] */0;
    let effect = n => {
      seen = {
        hd: n,
        tl: seen
      };
      return n;
    };
    let f = early => {
      let first = effect(1);
      let tmp;
      if (early) {
        return effect(2);
      }
      tmp = effect(3);
      effect(4);
      return first + tmp | 0;
    };
    Test_utils.eq("File \"early_return_test.res\", line 168, characters 7-14", 2, f(true));
    Test_utils.eq("File \"early_return_test.res\", line 169, characters 7-14", {
      hd: 2,
      tl: {
        hd: 1,
        tl: /* [] */0
      }
    }, seen);
    seen = /* [] */0;
    Test_utils.eq("File \"early_return_test.res\", line 171, characters 7-14", 4, f(false));
    Test_utils.eq("File \"early_return_test.res\", line 172, characters 7-14", {
      hd: 4,
      tl: {
        hd: 3,
        tl: {
          hd: 1,
          tl: /* [] */0
        }
      }
    }, seen);
  });
  Mocha.test("return from for-of closes the iterator", () => {
    let closed = false;
    let values = (onClose => (function* () {
        try { yield 1; yield 2; }
        finally { onClose(); }
      })());
    let f = () => {
      for (let value of values(() => {
          closed = true;
        })) {
        return value;
      }
      return 0;
    };
    Test_utils.eq("File \"early_return_test.res\", line 189, characters 7-14", 1, f());
    Test_utils.eq("File \"early_return_test.res\", line 190, characters 7-14", true, closed);
  });
  Mocha.test("short circuit and unit return", () => {
    let seen = 0;
    let f = enabled => {
      let tmp = false;
      if (enabled) {
        return 42;
        tmp = undefined;
      }
      return 7;
    };
    let stop = () => {};
    stop();
    Test_utils.eq("File \"early_return_test.res\", line 206, characters 7-14", 0, seen);
    Test_utils.eq("File \"early_return_test.res\", line 207, characters 7-14", 42, f(true));
    Test_utils.eq("File \"early_return_test.res\", line 208, characters 7-14", 7, f(false));
  });
  Mocha.test("async returns", async () => {
    Test_utils.eq("File \"early_return_test.res\", line 212, characters 7-14", 42, await returnAsync(true));
    return Test_utils.eq("File \"early_return_test.res\", line 213, characters 7-14", 7, await returnAsync(false));
  });
});

export {
  choose,
  alwaysReturn,
  identity,
  inLoops,
  returnAsync,
  getGadt,
  OperandFailure,
  inTry,
}
/*  Not a pure module */
