// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let v = (Number.EPSILON?Number.EPSILON:2.220446049250313e-16);

Mocha.describe("Epsilon_test", () => {
  Mocha.test("epsilon", () => Test_utils.eq("File \"epsilon_test.res\", line 8, characters 7-14", Number.EPSILON, v));
  Mocha.test("raw_epsilon", () => Test_utils.eq("File \"epsilon_test.res\", line 11, characters 7-14", 2.220446049250313e-16, v));
});

export {
  v,
}
/* v Not a pure module */
