// Generated by ReScript, PLEASE EDIT WITH CARE


let X = {};

let process = globalThis.process;

let proc = process;

let Global = {};

let $$parseInt = parseInt;

export {
  X,
  process,
  proc,
  Global,
  $$parseInt,
}
/* process Not a pure module */
