// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(S) {
  let opt_get = (f, i) => f[i];
  return {
    opt_get: opt_get
  };
}

function opt_get(f, i) {
  return f[i];
}

let Int_arr = {
  opt_get: opt_get
};

function f(v) {
  return [
    v[0],
    v[1]
  ];
}

export {
  Make,
  Int_arr,
  f,
}
/* No side effect */
