// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";

let oppHeroes = {
  hd: 0,
  tl: /* [] */0
};

let huntGrootCondition = false;

if (Stdlib_List.length(/* [] */0) > 0) {
  let x = Stdlib_List.filter(oppHeroes, h => Stdlib_List.headExn(/* [] */0) <= 1000);
  huntGrootCondition = Stdlib_List.length(x) === 0;
}

let huntGrootCondition2 = true;

if (Stdlib_List.length(/* [] */0) < 0) {
  let x$1 = Stdlib_List.filter(oppHeroes, h => Stdlib_List.headExn(/* [] */0) <= 1000);
  huntGrootCondition2 = Stdlib_List.length(x$1) === 0;
}

Mocha.describe("Gpr_2608_test", () => {
  Mocha.test("huntGroot conditions", () => {
    Test_utils.eq("File \"gpr_2608_test.res\", line 21, characters 7-14", huntGrootCondition, false);
    Test_utils.eq("File \"gpr_2608_test.res\", line 22, characters 7-14", huntGrootCondition2, true);
  });
});

let nearestGroots = /* [] */0;

export {
  nearestGroots,
  oppHeroes,
  huntGrootCondition,
  huntGrootCondition2,
}
/* huntGrootCondition Not a pure module */
