// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";

let b = Stdlib_Array.equal([
  1,
  2,
  3
], [
  1,
  2,
  3
], (prim0, prim1) => prim0 === prim1);

let A;

export {
  A,
  b,
}
/* b Not a pure module */
