// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

if (!Primitive_object.equal("", "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      2,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal("", "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      3,
      2
    ],
    Error: new Error()
  };
}

if (!Primitive_object.equal("", "")) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_974_test.res",
      4,
      2
    ],
    Error: new Error()
  };
}

/*  Not a pure module */
