// Generated by ReScript, PLEASE EDIT WITH CARE


let calls = {
  contents: 0
};

function guard() {
  calls.contents = calls.contents + 1 | 0;
  return false;
}

function both_guards_run() {
  calls.contents = 0;
  if (guard()) {
    
  } else {
    guard();
  }
  return calls.contents;
}

let constant_guard = "right";

export {
  constant_guard,
  calls,
  guard,
  both_guards_run,
}
/* No side effect */
