// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return "one";
}

function keep() {
  return "one-keep";
}

let One = {
  make: make,
  keep: keep
};

function keep$1() {
  return "two-keep";
}

function make$1() {
  return "two";
}

function keep$2() {
  return "two-inner-keep";
}

let Inner = {
  make: make$1,
  keep: keep$2
};

let Two = {
  keep: keep$1,
  Inner: Inner
};

function keep$3() {
  return "three-inner-keep";
}

function make$2() {
  return "three";
}

function keep$4() {
  return "three-deep-keep";
}

let Deep = {
  make: make$2,
  keep: keep$4
};

let Inner$1 = {
  keep: keep$3,
  Deep: Deep
};

let Three = {
  Inner: Inner$1
};

function $$switch() {
  return "keyword";
}

function $plus() {
  return "dollar";
}

let Escaped = {
  $$switch: $$switch,
  $plus: $plus
};

function $plus$1() {
  return "operator";
}

let Operator = {
  $plus: $plus$1
};

function make$3() {
  return "nested";
}

let B = {
  make: make$3
};

function B$make() {
  return "exotic";
}

let Ambiguous = {
  B: B,
  B$make: B$make
};

function value() {
  return "recursive";
}

let RecursiveB = {
  value: value
};

function make$4() {
  return "recursive";
}

let RecursiveA = {
  make: make$4
};

function make$5() {
  return "typed";
}

let Typed = {
  make: make$5
};

function make$6() {
  return "coerced";
}

let Coerced = {
  make: make$6
};

let Included = {
  make: make,
  keep: keep
};

let Aliased;

let Coerced$make = Coerced.make;

let Typed$make = Typed.make;

let RecursiveA$make = RecursiveA.make;

let Ambiguous$B$make = B.make;

let Operator$$plus = Operator.$plus;

let Escaped$$plus = $plus;

let Escaped$switch = $$switch;

let Three$Inner$Deep$make = Three.Inner.Deep.make;

let Two$Inner$make = Inner.make;

let One$make = make;

export {
  One,
  Two,
  Three,
  Escaped,
  Operator,
  Ambiguous,
  RecursiveA,
  RecursiveB,
  Typed,
  Coerced,
  Included,
  Aliased,
  Coerced$make,
  Typed$make,
  RecursiveA$make,
  Ambiguous$B$make,
  Operator$$plus,
  Escaped$$plus,
  Escaped$switch,
  Three$Inner$Deep$make,
  Two$Inner$make,
  One$make,
}
/* No side effect */
