// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

let f8 = import("a").then(m => m.default);

let f9 = import("b").then(m => m.default);

let f10 = import("m").then(m => m.Math.floor);

let f11 = import("m").then(m => (prim0 => m.sum(...prim0)));

let f12 = import("m").then(m => (prim0 => Primitive_option.fromNullable(m.getUser(prim0))));

export {
  f8,
  f9,
  f10,
  f11,
  f12,
}
/* f11 Not a pure module */
