// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MyCssCss from "./myCss.css" with {"type": "c\\x73s", "some-identifier": "y\\x65p"};
import MyJsonJson from "./myJson.json" with {"type": "j\\x73on", "some-identifier": "y\\x65p"};

let myJson = MyJsonJson;

console.log(myJson);

let buttonCss = MyCssCss.button;

console.log(buttonCss);

export {
  myJson,
  buttonCss,
}
/* myJson Not a pure module */
