// Generated by ReScript, PLEASE EDIT WITH CARE

import A from "a";

let a = import("a").then(m => m.default);

let b = A;

let c = import("./export_keyword.mjs").then(m => m.$$case);

export {
  a,
  b,
  c,
}
/* b Not a pure module */
