// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";

let recorded = [];

let equalish = Primitive_object.equal;

function copy(a) {
  return a.slice();
}

function helper(x, y) {
  return Primitive_object.equal(x, y.slice());
}

function effA(_n) {
  while (true) {
    let n = _n;
    recorded.push("a");
    if (n <= 0) {
      return [n];
    }
    _n = n - 1 | 0;
    continue;
  };
}

function effB(_n) {
  while (true) {
    let n = _n;
    recorded.push("b");
    if (n <= 0) {
      return [n];
    }
    _n = n - 1 | 0;
    continue;
  };
}

let x = effA(0);

let y = effB(0);

Primitive_object.equal(x, y.slice());

export {
  recorded,
  equalish,
  copy,
  helper,
  effA,
  effB,
}
/* x Not a pure module */
