// Generated by ReScript, PLEASE EDIT WITH CARE


let N = {};

console.log([
  3e-6,
  3e-6
]);

let x = true;

function N1(funarg) {
  return {};
}

let h = "hello";

let hh = "hellohello";

export {
  x,
  N,
  N1,
  h,
  hh,
}
/*  Not a pure module */
