// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let recorded = [];

function log(x) {
  recorded.push(x);
  return x;
}

function lastOnly(_a, _b, _c, d) {
  return Math.max(d, 0);
}

function applyFirst(k, a, _b, _c) {
  return k(a);
}

Mocha.describe("Inline_unused_arg_order_test", () => {
  Mocha.test("unused arguments before a primitive", () => {
    recorded.splice(0, recorded.length);
    log(1);
    log(2);
    log(3);
    let r = Math.max(log(4), 0);
    Test_utils.eq("File \"inline_unused_arg_order_test.res\", line 22, characters 7-14", r, 4);
    Test_utils.eq("File \"inline_unused_arg_order_test.res\", line 23, characters 7-14", recorded, [
      1,
      2,
      3,
      4
    ]);
  });
  Mocha.test("unused arguments before an application", () => {
    recorded.splice(0, recorded.length);
    log(2);
    log(3);
    let r = Math.abs(log(1));
    Test_utils.eq("File \"inline_unused_arg_order_test.res\", line 29, characters 7-14", r, 1);
    Test_utils.eq("File \"inline_unused_arg_order_test.res\", line 30, characters 7-14", recorded, [
      2,
      3,
      1
    ]);
  });
});

export {
  recorded,
  log,
  lastOnly,
  applyFirst,
}
/*  Not a pure module */
