// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function upperRange(value) {
  return value >= 2147483645;
}

function lowerRange(value) {
  return value < -2147483645;
}

function recordRange(value) {
  return value.status >= 2147483645;
}

function tupleRange(value) {
  if (value[0] >= 2147483645) {
    return value[1];
  } else {
    return false;
  }
}

function variantRange(value) {
  return value._0 >= 2147483645;
}

function arrayRange(value) {
  if (value.length !== 1) {
    return false;
  }
  let match = value[0];
  return match >= 2147483645;
}

function callRange(value) {
  let match = value();
  return match >= 2147483645;
}

function guardedRange(value, enabled) {
  if (value >= 2147483645) {
    return enabled;
  } else {
    return false;
  }
}

function bothRanges(value) {
  if (value >= -2147483645) {
    if (value >= 2147483645) {
      return 1;
    } else {
      return 0;
    }
  } else {
    return -1;
  }
}

function separateCases(value) {
  if (value >= -2147483645) {
    if (value < 2147483645) {
      return 0;
    }
    switch (value) {
      case 2147483645 :
        return 4;
      case 2147483646 :
        return 5;
      case 2147483647 :
        return 6;
    }
  } else {
    switch (value) {
      case -2147483648 :
        return 1;
      case -2147483647 :
        return 2;
      case -2147483646 :
        return 3;
    }
  }
}

let samples = [
  [
    -2147483648,
    true,
    false,
    1
  ],
  [
    -2147483647,
    true,
    false,
    2
  ],
  [
    -2147483646,
    true,
    false,
    3
  ],
  [
    -2147483645,
    false,
    false,
    0
  ],
  [
    -1,
    false,
    false,
    0
  ],
  [
    0,
    false,
    false,
    0
  ],
  [
    1,
    false,
    false,
    0
  ],
  [
    2147483644,
    false,
    false,
    0
  ],
  [
    2147483645,
    false,
    true,
    4
  ],
  [
    2147483646,
    false,
    true,
    5
  ],
  [
    2147483647,
    false,
    true,
    6
  ]
];

Mocha.describe("Int_range_boundary_test", () => {
  Mocha.test("integer ranges at both 32-bit limits", () => {
    samples.forEach(param => {
      let upper = param[2];
      let lower = param[1];
      let value = param[0];
      Test_utils.eq("File \"int_range_boundary_test.res\", line 91, characters 11-18", value >= 2147483645, upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 92, characters 11-18", value < -2147483645, lower);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 93, characters 11-18", bothRanges(value), lower ? -1 : (
          upper ? 1 : 0
        ));
    });
  });
  Mocha.test("upper-limit ranges in nested patterns and function results", () => {
    samples.forEach(param => {
      let upper = param[2];
      let value = param[0];
      Test_utils.eq("File \"int_range_boundary_test.res\", line 101, characters 11-18", recordRange({
        status: value
      }), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 102, characters 11-18", tupleRange([
        value,
        true
      ]), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 103, characters 11-18", tupleRange([
        value,
        false
      ]), false);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 104, characters 11-18", variantRange({
        TAG: "Status",
        _0: value
      }), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 105, characters 11-18", arrayRange([value]), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 106, characters 11-18", arrayRange([
        value,
        value
      ]), false);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 107, characters 11-18", arrayRange([]), false);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 108, characters 11-18", callRange(() => value), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 109, characters 11-18", guardedRange(value, true), upper);
      Test_utils.eq("File \"int_range_boundary_test.res\", line 110, characters 11-18", guardedRange(value, false), false);
    });
  });
  Mocha.test("distinct actions at both 32-bit limits", () => {
    samples.forEach(param => Test_utils.eq("File \"int_range_boundary_test.res\", line 118, characters 11-18", separateCases(param[0]), param[3]));
  });
});

export {
  upperRange,
  lowerRange,
  recordRange,
  tupleRange,
  variantRange,
  arrayRange,
  callRange,
  guardedRange,
  bothRanges,
  separateCases,
  samples,
}
/*  Not a pure module */
