// Generated by ReScript, PLEASE EDIT WITH CARE


function Issue_8385_optional_args_typecheck$A(props) {
  return null;
}

let A = {
  make: Issue_8385_optional_args_typecheck$A
};

export {
  A,
}
/* No side effect */
