// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let jsonNull = null;

let jsonArray = ["a", "b"];

let jsonObject = {"key": "value"};

let jsonString = "hello";

let jsonNumber = 42;

let jsonBool = true;

Mocha.describe("JSONSwitchNullCheck_test", () => {
  Mocha.describe("JSON direct switch with Null - should NOT match Object", () => {
    Mocha.test("switch null { | Object(_) => Object | Array(_) => Array | _ => default }", () => {
      let result;
      if (Array.isArray(jsonNull)) {
        result = "Array";
      } else if (jsonNull !== null && !Array.isArray(jsonNull)) {
        switch (typeof jsonNull) {
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 26, characters 11-18", result, "default");
    });
    Mocha.test("switch null { | Object(_) => Object | String(_) => String | _ => default }", () => {
      let result;
      if (jsonNull !== null && !Array.isArray(jsonNull)) {
        switch (typeof jsonNull) {
          case "string" :
            result = "String";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 39, characters 11-18", result, "default");
    });
    Mocha.test("switch null { | Object(_) => Object | Number(_) => Number | _ => default }", () => {
      let result;
      if (jsonNull !== null && !Array.isArray(jsonNull)) {
        switch (typeof jsonNull) {
          case "number" :
            result = "Number";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 52, characters 11-18", result, "default");
    });
    Mocha.test("switch null { | Object(_) => Object | Array(_) => Array | String(_) => String | _ => default }", () => {
      let result;
      if (Array.isArray(jsonNull)) {
        result = "Array";
      } else if (jsonNull !== null && !Array.isArray(jsonNull)) {
        switch (typeof jsonNull) {
          case "string" :
            result = "String";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 66, characters 11-18", result, "default");
    });
  });
  Mocha.describe("JSON direct switch with Array - should NOT match Object", () => {
    Mocha.test("switch array { | Object(_) => Object | String(_) => String | _ => default }", () => {
      let result;
      if (jsonArray !== null && !Array.isArray(jsonArray)) {
        switch (typeof jsonArray) {
          case "string" :
            result = "String";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 81, characters 11-18", result, "default");
    });
    Mocha.test("switch array { | Object(_) => Object | Number(_) => Number | _ => default }", () => {
      let result;
      if (jsonArray !== null && !Array.isArray(jsonArray)) {
        switch (typeof jsonArray) {
          case "number" :
            result = "Number";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 94, characters 11-18", result, "default");
    });
    Mocha.test("switch array { | Object(_) => Object | Boolean(_) => Boolean | _ => default }", () => {
      let result;
      if (jsonArray !== null && !Array.isArray(jsonArray)) {
        switch (typeof jsonArray) {
          case "boolean" :
            result = "Boolean";
            break;
          case "object" :
            result = "Object";
            break;
          default:
            result = "default";
        }
      } else {
        result = "default";
      }
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 107, characters 11-18", result, "default");
    });
  });
  Mocha.describe("JSON switch - correct positive cases", () => {
    Mocha.test("switch object { | Object(_) => Object | _ => default }", () => {
      let result;
      result = typeof jsonObject === "object" && jsonObject !== null && !Array.isArray(jsonObject) ? "Object" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 120, characters 11-18", result, "Object");
    });
    Mocha.test("switch array { | Array(_) => Array | _ => default }", () => {
      let result;
      result = Array.isArray(jsonArray) ? "Array" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 131, characters 11-18", result, "Array");
    });
    Mocha.test("switch string { | String(_) => String | _ => default }", () => {
      let result;
      result = typeof jsonString === "string" ? "String" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 142, characters 11-18", result, "String");
    });
    Mocha.test("switch number { | Number(_) => Number | _ => default }", () => {
      let result;
      result = typeof jsonNumber === "number" ? "Number" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 153, characters 11-18", result, "Number");
    });
    Mocha.test("switch bool { | Boolean(_) => Boolean | _ => default }", () => {
      let result;
      result = typeof jsonBool === "boolean" ? "Boolean" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 164, characters 11-18", result, "Boolean");
    });
    Mocha.test("switch null { | Null => Null | _ => default }", () => {
      let result;
      result = jsonNull === null ? "Null" : "default";
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 175, characters 11-18", result, "Null");
    });
    Mocha.test("switch null { | Null => Null | Object(_) => Object | _ => default }", () => {
      let result;
      result = jsonNull === null ? "Null" : (
          typeof jsonNull === "object" && !Array.isArray(jsonNull) ? "Object" : "default"
        );
      Test_utils.eq("File \"JSONSwitchNullCheck_test.res\", line 187, characters 11-18", result, "Null");
    });
  });
});

export {
  jsonNull,
  jsonArray,
  jsonObject,
  jsonString,
  jsonNumber,
  jsonBool,
}
/*  Not a pure module */
