// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Jsx_optional_props_test$ComponentWithOptionalProps(props) {
  return null;
}

let ComponentWithOptionalProps = {
  make: Jsx_optional_props_test$ComponentWithOptionalProps
};

let _element = JsxRuntime.jsx(Jsx_optional_props_test$ComponentWithOptionalProps, {
  i: 1,
  s: "test",
  element: JsxRuntime.jsx("div", {})
});

let Jsx_optional_props_test$ComponentWithOptionalProps$jsx = true;

export {
  ComponentWithOptionalProps,
  _element,
  Jsx_optional_props_test$ComponentWithOptionalProps,
  Jsx_optional_props_test$ComponentWithOptionalProps$jsx,
}
/* _element Not a pure module */
