// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SomeRuntime from "some-runtime";

let Elements = {};

let MyJsx = {
  Elements: Elements
};

function Jsx_preserve_custom_runtime$Comp(props) {
  return <div
    title={props.title}
  />;
}

let Comp = {
  make: Jsx_preserve_custom_runtime$Comp
};

let memoComp = SomeRuntime.memo(Jsx_preserve_custom_runtime$Comp);

let TopMemo = {
  make: memoComp
};

let topMemo = <TopMemo.make
  title={"tm"}
/>;

let fragment = <>
  <span />
  <b />
</>;

let keyed = <div
  key={"k"}
>
  <span />
  <b />
</div>;

export {
  MyJsx,
  Comp,
  memoComp,
  TopMemo,
  topMemo,
  fragment,
  keyed,
}
/* memoComp Not a pure module */
