// Generated by ReScript, PLEASE EDIT WITH CARE


function doStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidString"
    };
  }
}

function doNextStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidNext"
    };
  }
}

function getXWithResult(s) {
  let y = doStuffWithResult(s);
  if (y.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: y._0
    };
  }
  let y$1 = y._0;
  let x = doNextStuffWithResult(y$1);
  if (x.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: x._0 + y$1
    };
  } else {
    return {
      TAG: "Error",
      _0: x._0
    };
  }
}

let x = getXWithResult("s");

let someResult;

someResult = x.TAG === "Ok" ? x._0 : (
    x._0 === "InvalidNext" ? "nope!" : "nope"
  );

function doStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
  
}

function doNextStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
  
}

function getXWithOption(s) {
  let y = doStuffWithOption(s);
  if (y === undefined) {
    return;
  }
  let x = doNextStuffWithOption(y);
  if (x !== undefined) {
    return x + y;
  }
  
}

let x$1 = getXWithOption("s");

let someOption = x$1 !== undefined ? x$1 : "nope";

async function doStuffResultAsync(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: {
        s: "hello"
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "FetchError"
    };
  }
}

async function decodeResAsync(res) {
  let match = res.s;
  if (match === "s") {
    return {
      TAG: "Ok",
      _0: res.s
    };
  } else {
    return {
      TAG: "Error",
      _0: "DecodeError"
    };
  }
}

async function getXWithResultAsync(s) {
  let res = await doStuffResultAsync(s);
  if (res.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: res._0
    };
  }
  let res$1 = res._0;
  console.log(res$1.s);
  let x = await decodeResAsync(res$1);
  if (x.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: x._0
    };
  } else {
    return {
      TAG: "Error",
      _0: x._0
    };
  }
}

export {
  doStuffWithResult,
  doNextStuffWithResult,
  getXWithResult,
  someResult,
  doStuffWithOption,
  doNextStuffWithOption,
  getXWithOption,
  someOption,
  doStuffResultAsync,
  decodeResAsync,
  getXWithResultAsync,
}
/* x Not a pure module */
