// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.mjs";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Limits_test", () => {
  Mocha.test("max_int", () => Test_utils.eq("File \"limits_test.res\", line 5, characters 27-34", Stdlib_Int.Constants.maxValue, 2147483647));
  Mocha.test("min_int", () => Test_utils.eq("File \"limits_test.res\", line 6, characters 27-34", Stdlib_Int.Constants.minValue, -2147483648));
});

/*  Not a pure module */
