// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.mjs";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Loop_control_test", () => {
  Mocha.test("while loop break and continue", () => {
    let values = /* [] */0;
    let i = 0;
    while (i < 6) {
      i = i + 1 | 0;
      if (i === 2) {
        continue;
      }
      if (i === 5) {
        break;
        
      }
      values = {
        hd: i,
        tl: values
      };
    };
    Test_utils.eq("File \"loop_control_test.res\", line 23, characters 7-14", [
      1,
      3,
      4
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("switch inside while targets the loop", () => {
    let values = /* [] */0;
    let i = 0;
    while (i < 6) {
      i = i + 1 | 0;
      let match = i;
      if (match !== 2) {
        if (match !== 5) {
          values = {
            hd: i,
            tl: values
          };
        } else {
          break;
          
        }
      } else {
        continue;
      }
    };
    Test_utils.eq("File \"loop_control_test.res\", line 40, characters 7-14", [
      1,
      3,
      4
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("string switch inside while targets the loop via JS switch", () => {
    let values = /* [] */0;
    let i = 0;
    loop_0: while (i < 6) {
      i = i + 1 | 0;
      let match = i;
      let state = match !== 2 ? (
          match !== 5 ? "keep" : "stop"
        ) : "skip";
      switch (state) {
        case "skip" :
          continue loop_0;
        case "stop" :
          break loop_0;
          default:
          values = {
            hd: i,
            tl: values
          };
      }
    };
    Test_utils.eq("File \"loop_control_test.res\", line 64, characters 7-14", [
      1,
      3,
      4
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("for loop break and continue", () => {
    let values = /* [] */0;
    for (let i = 0; i <= 5; ++i) {
      if (i === 1) {
        continue;
      }
      if (i === 4) {
        break;
        
      }
      values = {
        hd: i,
        tl: values
      };
    }
    Test_utils.eq("File \"loop_control_test.res\", line 82, characters 7-14", [
      0,
      2,
      3
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("braced break expression in value position compiles", () => {
    let reached = false;
    while (true) {
      break;
      
    };
    Test_utils.eq("File \"loop_control_test.res\", line 95, characters 7-14", false, reached);
  });
  Mocha.test("braced continue expression in value position compiles", () => {
    let values = /* [] */0;
    for (let i = 0; i <= 3; ++i) {
      if (i === 1) {
        continue;
      }
      values = {
        hd: i,
        tl: values
      };
    }
    Test_utils.eq("File \"loop_control_test.res\", line 111, characters 7-14", [
      0,
      2,
      3
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("switch inside for targets the loop", () => {
    let values = /* [] */0;
    for (let i = 0; i <= 5; ++i) {
      if (i !== 1) {
        if (i !== 4) {
          values = {
            hd: i,
            tl: values
          };
        } else {
          break;
          
        }
      } else {
        continue;
      }
    }
    Test_utils.eq("File \"loop_control_test.res\", line 125, characters 7-14", [
      0,
      2,
      3
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
  Mocha.test("string switch inside for targets the loop via JS switch", () => {
    let values = /* [] */0;
    loop_1: for (let i = 0; i <= 5; ++i) {
      let state = i !== 1 ? (
          i !== 4 ? "keep" : "stop"
        ) : "skip";
      switch (state) {
        case "skip" :
          continue loop_1;
        case "stop" :
          break loop_1;
          default:
          values = {
            hd: i,
            tl: values
          };
      }
    }
    Test_utils.eq("File \"loop_control_test.res\", line 146, characters 7-14", [
      0,
      2,
      3
    ], Belt_List.toArray(Belt_List.reverse(values)));
  });
});

/*  Not a pure module */
