// Generated by ReScript, PLEASE EDIT WITH CARE


let M = {
  x: 1
};

let N = {
  x: ""
};

function G($star) {
  return {
    y: 1
  };
}

let A = {
  y: 1
};

let y = 1;

export {
  M,
  N,
  G,
  A,
  y,
}
/* No side effect */
