// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";

function length(param) {
  return 3;
}

Mocha.describe("Module_test", () => {
  Mocha.test("list_length", () => Test_utils.eq("File \"module_test.res\", line 8, characters 31-38", 2, Stdlib_List.length({
    hd: 1,
    tl: {
      hd: 2,
      tl: /* [] */0
    }
  })));
  Mocha.test("length", () => Test_utils.eq("File \"module_test.res\", line 9, characters 26-33", 3, 3));
});

export {
  length,
}
/*  Not a pure module */
