// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.mjs";

function f(x) {
  return x;
}

let XX = {
  make: Stdlib_Array.make,
  fromInitializer: Stdlib_Array.fromInitializer,
  equal: Stdlib_Array.equal,
  compare: Stdlib_Array.compare,
  isEmpty: Stdlib_Array.isEmpty,
  concatAll: Stdlib_Array.concatAll,
  indexOfOpt: Stdlib_Array.indexOfOpt,
  lastIndexOfOpt: Stdlib_Array.lastIndexOfOpt,
  reduce: Stdlib_Array.reduce,
  reduceWithIndex: Stdlib_Array.reduceWithIndex,
  reduceRight: Stdlib_Array.reduceRight,
  reduceRightWithIndex: Stdlib_Array.reduceRightWithIndex,
  findIndexOpt: Stdlib_Array.findIndexOpt,
  findLastIndexOpt: Stdlib_Array.findLastIndexOpt,
  filterMap: Stdlib_Array.filterMap,
  filterMapWithIndex: Stdlib_Array.filterMapWithIndex,
  keepSome: Stdlib_Array.keepSome,
  toShuffled: Stdlib_Array.toShuffled,
  shuffle: Stdlib_Array.shuffle,
  findMap: Stdlib_Array.findMap,
  zip: Stdlib_Array.zip,
  zipBy: Stdlib_Array.zipBy,
  partition: Stdlib_Array.partition,
  unzip: Stdlib_Array.unzip,
  last: Stdlib_Array.last,
  f: f
};

let u = [Stdlib_String];

let hh = "x".length;

export {
  XX,
  u,
  hh,
}
/* hh Not a pure module */
