// Generated by ReScript, PLEASE EDIT WITH CARE


let j = 1;

let k = 1;

function upd() {
  k = 3;
}

if (k === 1) {
  upd();
  j = j + 2 | 0;
  console.log("correct");
} else {
  upd();
  j = j + 2 | 0;
  console.log("incorrect");
}

let j$1 = 0;

let k$1 = 0;

export {
  upd,
  j$1 as j,
  k$1 as k,
}
/*  Not a pure module */
