// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

let React = {};

let ReactDOM = {};

function Nojaf$Icon(props) {
  return <strong/>;
}

let Icon = {
  make: Nojaf$Icon
};

<div><h1>{"Hello, world!"}</h1><Nojaf$Icon/></div>;

export {
  React,
  ReactDOM,
  Icon,
}
/*  Not a pure module */
