// Generated by ReScript, PLEASE EDIT WITH CARE


function forget_write_covariant(v) {
  return v;
}

function open_source_covariant(o) {
  return o;
}

function closed_source_open_target(v) {
  return v;
}

function open_source_promote_same_type(o) {
  return o;
}

function open_row_write(o) {
  o.x = 1;
}

function read_x(obj) {
  return obj.x;
}

function read_from_settable() {
  return settableObj.x;
}

function read_from_readonly() {
  return readonlyObj.x;
}

function open_source_setter_narrower(o) {
  return o;
}

function unrelated_setter_type(o) {
  o.x = "hello";
  return o.x;
}

function run_unrelated_setter() {
  return unrelated_setter_type(plainIntObj);
}

export {
  forget_write_covariant,
  open_source_covariant,
  closed_source_open_target,
  open_source_promote_same_type,
  open_row_write,
  read_x,
  read_from_settable,
  read_from_readonly,
  open_source_setter_narrower,
  unrelated_setter_type,
  run_unrelated_setter,
}
/* No side effect */
