// Generated by ReScript, PLEASE EDIT WITH CARE


function use_poly(o) {
  return [
    o.id(1),
    o.id("x")
  ];
}

function forget_extra(o) {
  return o;
}

function use_open(o) {
  return [
    o.id(1),
    o.id("x")
  ];
}

let value = ({id: x => x});

let pair = use_poly(value);

function write_poly(o) {
  o.id = x => x;
  return [
    o.id(1),
    o.id("x")
  ];
}

export {
  use_poly,
  forget_extra,
  use_open,
  value,
  pair,
  write_poly,
}
/* value Not a pure module */
