// Generated by ReScript, PLEASE EDIT WITH CARE


function forget_write_covariant(v) {
  return v;
}

function open_source_covariant(o) {
  return o;
}

function closed_source_open_target(v) {
  return v;
}

function open_source_promote_same_type(o) {
  return o;
}

function open_row_write(o) {
  o.x = 1;
}

function read_x(obj) {
  return obj.x;
}

function read_from_settable() {
  return settableObj.x;
}

function read_from_readonly() {
  return readonlyObj.x;
}

function set_x(o, v) {
  o.x = v;
}

function set_at_int() {
  intTarget.x = 1;
}

function set_at_string() {
  stringTarget.x = "s";
}

function closed_immutable_covariant(v) {
  return v;
}

let PrivateRowForgetsSet = {};

function write_private_settable(o) {
  o.x = 1;
}

export {
  forget_write_covariant,
  open_source_covariant,
  closed_source_open_target,
  open_source_promote_same_type,
  open_row_write,
  read_x,
  read_from_settable,
  read_from_readonly,
  set_x,
  set_at_int,
  set_at_string,
  closed_immutable_covariant,
  PrivateRowForgetsSet,
  write_private_settable,
}
/* No side effect */
