// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

let suites = {
  contents: /* [] */0
};

let test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

function make(s, b, i, param) {
  let tmp = {};
  if (s !== undefined) {
    tmp.s = s;
  }
  if (b !== undefined) {
    tmp.b = b;
  }
  if (i !== undefined) {
    tmp.i = i;
  }
  return tmp;
}

let tmp = {};

if ("" !== undefined) {
  tmp.s = "";
}

tmp.b = false;

tmp.i = 0;

let hh = tmp;

eq("File \"optional_regression_test.res\", line 16, characters 3-10", hh.s, "");

eq("File \"optional_regression_test.res\", line 17, characters 3-10", hh.b, false);

eq("File \"optional_regression_test.res\", line 18, characters 3-10", hh.i, 0);

console.log(hh);

Mt.from_pair_suites("Optional_regression_test", suites.contents);

export {
  suites,
  test_id,
  eq,
  make,
  hh,
}
/*  Not a pure module */
