// Generated by ReScript, PLEASE EDIT WITH CARE


let match = {};

let emptyDictPatternShouldCompile;

emptyDictPatternShouldCompile = typeof match === "object" && match !== null && !Array.isArray(match);

export {
  emptyDictPatternShouldCompile,
}
/* emptyDictPatternShouldCompile Not a pure module */
