// Generated by ReScript, PLEASE EDIT WITH CARE


function decodeGroup(group) {
  let id = group.id;
  if (typeof id !== "string") {
    return [
      "e",
      "f"
    ];
  }
  let name = group.name;
  if (typeof name === "string") {
    return [
      id,
      name
    ];
  } else {
    return [
      "e",
      "f"
    ];
  }
}

function decodeNull(x) {
  let match = x.field;
  if (match === null) {
    return "yes it's null";
  } else {
    return "no";
  }
}

function decodeUndefined(x) {
  return "no";
}

export {
  decodeGroup,
  decodeNull,
  decodeUndefined,
}
/* No side effect */
