// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function handleBC(x) {
  if (x === "C") {
    return "c";
  } else {
    return "b";
  }
}

function narrowBasic(x) {
  if (x === "A") {
    return "a";
  } else {
    return handleBC(x);
  }
}

function handleCD(x) {
  if (x === "D") {
    return 4;
  } else {
    return 3;
  }
}

function narrowOrPattern(x) {
  if (x === "B" || x === "A") {
    return 1;
  } else {
    return handleCD(x);
  }
}

function handleYZ(x) {
  if (x === "Z") {
    return 20;
  } else {
    return 10;
  }
}

function narrowWithAlias(x) {
  if (x === "X") {
    return 0;
  } else {
    return handleYZ(x) + handleYZ(x) | 0;
  }
}

function handlePQR(x) {
  if (x === "Q") {
    return 200;
  } else if (x === "R") {
    return 300;
  } else {
    return 100;
  }
}

function narrowGuardedArm(x, cond) {
  if (x === "P" && cond) {
    return 1;
  } else {
    return handlePQR(x);
  }
}

function handleBarBaz(x) {
  if (x === "Baz") {
    return 22;
  } else {
    return 11;
  }
}

function narrowNested(r) {
  if (r.TAG === "Ok") {
    return r._0;
  }
  let rest = r._0;
  if (rest === "Foo") {
    return 0;
  } else {
    return handleBarBaz(rest);
  }
}

function narrowOpenRow(x) {
  if (x === "A") {
    return "a";
  } else {
    return handleBC(x);
  }
}

function narrowOpenAnnotated(x) {
  if (x === "A") {
    return "a";
  } else {
    return handleBC(x);
  }
}

function narrowRecordField(w) {
  let rest = w.inner;
  if (rest === "A") {
    return "a";
  } else {
    return handleBC(rest);
  }
}

function narrowTupleSibling(p) {
  if (p[0] === 0 && p[1] === "A") {
    return "zero-a";
  }
  let rest = p[1];
  if (rest === "A") {
    return "nonzero-a";
  } else {
    return handleBC(rest);
  }
}

function handleXY(x) {
  if (x === "Y") {
    return "y";
  } else {
    return "x";
  }
}

function narrowMultiConstructor(e) {
  if (e.TAG === "First") {
    let rest = e._0;
    if (rest === "A") {
      return "first-a";
    } else {
      return handleBC(rest);
    }
  }
  let rest$1 = e._0;
  if (rest$1 === "Z") {
    return "second-z";
  } else {
    return handleXY(rest$1);
  }
}

function narrowRestWithGuard(x, skip) {
  if (x === "A") {
    return 1;
  } else if (skip) {
    return 99;
  } else if (handleBC(x) === "b") {
    return 2;
  } else {
    return 3;
  }
}

function handleInnerBC(x) {
  if (x === "InnerC") {
    return "ic";
  } else {
    return "ib";
  }
}

function narrowVariantInVariant(x) {
  let rest = x.VAL;
  if (rest === "InnerA") {
    return "ia";
  } else {
    return handleInnerBC(rest);
  }
}

function handleOpenBC(x) {
  if (x === "B") {
    return "b";
  } else if (x === "C") {
    return "c";
  } else {
    return "other";
  }
}

function narrowFixedRow(x) {
  if (x === "A") {
    return "a";
  } else {
    return handleOpenBC(x);
  }
}

Mocha.describe("poly variant narrow", () => {
  Mocha.test("basic single-tag subtraction", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 160, characters 7-14", narrowBasic("A"), "a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 161, characters 7-14", narrowBasic("B"), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 162, characters 7-14", narrowBasic("C"), "c");
  });
  Mocha.test("or-pattern subtracts both tags", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 166, characters 7-14", narrowOrPattern("A"), 1);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 167, characters 7-14", narrowOrPattern("B"), 1);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 168, characters 7-14", narrowOrPattern("C"), 3);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 169, characters 7-14", narrowOrPattern("D"), 4);
  });
  Mocha.test("...rest as r binds both names", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 173, characters 7-14", narrowWithAlias("X"), 0);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 174, characters 7-14", narrowWithAlias("Y"), 20);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 175, characters 7-14", narrowWithAlias("Z"), 40);
  });
  Mocha.test("guarded arms are not subtracted", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 179, characters 7-14", narrowGuardedArm("P", true), 1);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 180, characters 7-14", narrowGuardedArm("P", false), 100);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 181, characters 7-14", narrowGuardedArm("Q", true), 200);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 182, characters 7-14", narrowGuardedArm("R", false), 300);
  });
  Mocha.test("nested: ...rest inside Error(...)", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 186, characters 7-14", narrowNested({
      TAG: "Error",
      _0: "Foo"
    }), 0);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 187, characters 7-14", narrowNested({
      TAG: "Error",
      _0: "Bar"
    }), 11);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 188, characters 7-14", narrowNested({
      TAG: "Error",
      _0: "Baz"
    }), 22);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 189, characters 7-14", 42, 42);
  });
  Mocha.test("open row: residual stays open", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 193, characters 7-14", narrowOpenRow("A"), "a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 194, characters 7-14", narrowOpenRow("B"), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 195, characters 7-14", narrowOpenRow("C"), "c");
  });
  Mocha.test("explicit [> ...] annotation narrows", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 199, characters 7-14", narrowOpenAnnotated("A"), "a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 200, characters 7-14", narrowOpenAnnotated("B"), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 201, characters 7-14", narrowOpenAnnotated("C"), "c");
  });
  Mocha.test("record field nesting", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 205, characters 7-14", narrowRecordField({
      inner: "A"
    }), "a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 206, characters 7-14", narrowRecordField({
      inner: "B"
    }), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 207, characters 7-14", narrowRecordField({
      inner: "C"
    }), "c");
  });
  Mocha.test("tuple with permissive sibling", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 211, characters 7-14", narrowTupleSibling([
      0,
      "A"
    ]), "zero-a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 212, characters 7-14", narrowTupleSibling([
      1,
      "A"
    ]), "nonzero-a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 213, characters 7-14", narrowTupleSibling([
      0,
      "B"
    ]), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 214, characters 7-14", narrowTupleSibling([
      1,
      "C"
    ]), "c");
  });
  Mocha.test("multiple constructors at independent paths", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 218, characters 7-14", narrowMultiConstructor({
      TAG: "First",
      _0: "A"
    }), "first-a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 219, characters 7-14", narrowMultiConstructor({
      TAG: "First",
      _0: "B"
    }), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 220, characters 7-14", narrowMultiConstructor({
      TAG: "First",
      _0: "C"
    }), "c");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 221, characters 7-14", narrowMultiConstructor({
      TAG: "Second",
      _0: "X"
    }), "x");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 222, characters 7-14", narrowMultiConstructor({
      TAG: "Second",
      _0: "Y"
    }), "y");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 223, characters 7-14", narrowMultiConstructor({
      TAG: "Second",
      _0: "Z"
    }), "second-z");
  });
  Mocha.test("guard on the ...rest arm itself", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 227, characters 7-14", narrowRestWithGuard("A", true), 1);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 228, characters 7-14", narrowRestWithGuard("B", true), 99);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 229, characters 7-14", narrowRestWithGuard("B", false), 2);
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 230, characters 7-14", narrowRestWithGuard("C", false), 3);
  });
  Mocha.test("variant within variant", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 234, characters 7-14", narrowVariantInVariant({
      NAME: "Outer",
      VAL: "InnerA"
    }), "ia");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 235, characters 7-14", narrowVariantInVariant({
      NAME: "Outer",
      VAL: "InnerB"
    }), "ib");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 236, characters 7-14", narrowVariantInVariant({
      NAME: "Outer",
      VAL: "InnerC"
    }), "ic");
  });
  Mocha.test("prenex-quantified row (row_fixed) still narrows", () => {
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 240, characters 7-14", narrowFixedRow("A"), "a");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 241, characters 7-14", narrowFixedRow("B"), "b");
    Test_utils.eq("File \"poly_variant_narrow_test.res\", line 242, characters 7-14", narrowFixedRow("C"), "c");
  });
});

export {
  handleBC,
  narrowBasic,
  handleCD,
  narrowOrPattern,
  handleYZ,
  narrowWithAlias,
  handlePQR,
  narrowGuardedArm,
  handleBarBaz,
  narrowNested,
  narrowOpenRow,
  narrowOpenAnnotated,
  narrowRecordField,
  narrowTupleSibling,
  handleXY,
  narrowMultiConstructor,
  narrowRestWithGuard,
  handleInnerBC,
  narrowVariantInVariant,
  handleOpenBC,
  narrowFixedRow,
}
/*  Not a pure module */
