// Generated by ReScript, PLEASE EDIT WITH CARE


function mk(fn) {
  return fn();
}

(((_)=> console.log('should works'))());

console.log(1);

var issue6236 = `${"hello"}`;
;

export {
  mk,
}
/*  Not a pure module */
