// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function even(n) {
  if (n === 0) {
    return true;
  } else if (n === 1) {
    return false;
  } else {
    return B.odd(n - 1 | 0);
  }
}

let A = {
  even: even
};

function odd(n) {
  if (n === 1) {
    return true;
  } else if (n === 0) {
    return false;
  } else {
    return A.even(n - 1 | 0);
  }
}

let B = {
  odd: odd
};

function even$1(n) {
  if (n === 0) {
    return true;
  } else if (n === 1) {
    return false;
  } else {
    return BB.odd(n - 1 | 0);
  }
}

function x() {
  return BB.y() + 3 | 0;
}

let AA = {
  even: even$1,
  x: x
};

function odd$1(n) {
  if (n === 1) {
    return true;
  } else if (n === 0) {
    return false;
  } else {
    return even$1(n - 1 | 0);
  }
}

function y() {
  return 32;
}

let BB = {
  odd: odd$1,
  y: y
};

let Even = {};

let Odd = {};

Mocha.describe("Rec_module_test", () => {
  Mocha.test("test1", () => Test_utils.eq("File \"rec_module_test.res\", line 71, characters 7-14", [
    true,
    true,
    false,
    false
  ], [
    A.even(2),
    even$1(4),
    B.odd(2),
    odd$1(4)
  ]));
  Mocha.test("test2", () => Test_utils.eq("File \"rec_module_test.res\", line 75, characters 7-14", y(), 32));
  Mocha.test("test3", () => Test_utils.eq("File \"rec_module_test.res\", line 79, characters 7-14", x(), 35));
  Mocha.test("test4 - A.even", () => Test_utils.eq("File \"rec_module_test.res\", line 83, characters 7-14", true, A.even(2)));
  Mocha.test("test4 - AA.even", () => Test_utils.eq("File \"rec_module_test.res\", line 87, characters 7-14", true, even$1(4)));
  Mocha.test("test5", () => Test_utils.eq("File \"rec_module_test.res\", line 91, characters 7-14", false, B.odd(2)));
});

export {
  A,
  B,
  AA,
  BB,
  Even,
  Odd,
}
/*  Not a pure module */
