// Generated by ReScript, PLEASE EDIT WITH CARE


let rest = ((({name, ...__rest}) => __rest))({
  name: "test",
  version: "1.0",
  debug: true
});

function describe(c) {
  let rest = ((({name, ...__rest}) => __rest))(c);
  return [
    c.name,
    rest
  ];
}

function getName(param) {
  return param.name;
}

function extractClassName(param) {
  return ((({className, ...__rest}) => __rest))(param);
}

let intRest = ((({id, ...__rest}) => __rest))({
  id: "1",
  value: 42
});

function getValue(param) {
  return ((({id, ...__rest}) => __rest))(param);
}

let name = "test";

let id = "1";

export {
  rest,
  name,
  describe,
  getName,
  extractClassName,
  intRest,
  id,
  getValue,
}
/* No side effect */
