// Generated by ReScript, PLEASE EDIT WITH CARE


let rest = ((({name, ...__rest}) => __rest))({
  name: "test",
  version: "1.0",
  debug: true
});

function describe(c) {
  let rest = ((({name, ...__rest}) => __rest))(c);
  return [
    c.name,
    rest
  ];
}

function getName(param) {
  return param.name;
}

function extractClassName(param) {
  return ((({className, ...__rest}) => __rest))(param);
}

let intRest = ((({id, ...__rest}) => __rest))({
  id: "1",
  value: 42
});

function getValue(param) {
  return ((({id, ...__rest}) => __rest))(param);
}

function getTupleRest(param) {
  return ((({name, ...__rest}) => __rest))(param[0]);
}

let tupleRest = getTupleRest([
  {
    name: "tuple",
    version: "2.0",
    debug: false
  },
  1
]);

function getWrappedRest(wrapped) {
  return ((({name, ...__rest}) => __rest))(wrapped._0);
}

let wrappedRest = getWrappedRest({
  TAG: "Wrap",
  _0: {
    name: "wrapped",
    version: "3.0",
    debug: true
  }
});

let name = "test";

let id = "1";

export {
  rest,
  name,
  describe,
  getName,
  extractClassName,
  intRest,
  id,
  getValue,
  getTupleRest,
  tupleRest,
  getWrappedRest,
  wrappedRest,
}
/* tupleRest Not a pure module */
