// Generated by ReScript, PLEASE EDIT WITH CARE


function getA(x) {
  return x.A;
}

let Renamed_v = {
  A: 1,
  b: 2
};

let Renamed = {
  v: Renamed_v,
  getA: getA
};

export {
  Renamed,
}
/* No side effect */
