// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(param) {
  return React.createElement(make, {
    foo: param.foo
  });
}

let Recursive_react_component = make;

let make$1 = Recursive_react_component;

export {
  make$1 as make,
}
/* react Not a pure module */
