// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(param) {
  return React.createElement(make, {
    foo: param.foo
  });
}

let Recursive_react_component = make;

function Recursive_react_component$ShadowedSelfReference$make(props) {
  return React.createElement(props.make, {
    foo: props.foo
  });
}

let ShadowedSelfReference = {
  make: Recursive_react_component$ShadowedSelfReference$make
};

function Recursive_react_component$Leaf$make(props) {
  return props.foo;
}

let Leaf = {
  make: Recursive_react_component$Leaf$make
};

function Recursive_react_component$ShadowedByLocalLet$make(props) {
  return React.createElement(Recursive_react_component$Leaf$make, {
    foo: props.foo
  });
}

let ShadowedByLocalLet = {
  make: Recursive_react_component$ShadowedByLocalLet$make
};

function Recursive_react_component$ShadowedByNestedParameter$make(props) {
  return React.createElement(Recursive_react_component$Leaf$make, {
    foo: props.foo
  });
}

let ShadowedByNestedParameter = {
  make: Recursive_react_component$ShadowedByNestedParameter$make
};

let make$1 = Recursive_react_component;

export {
  make$1 as make,
  ShadowedSelfReference,
  Leaf,
  ShadowedByLocalLet,
  ShadowedByNestedParameter,
  Recursive_react_component$ShadowedSelfReference$make,
  Recursive_react_component$Leaf$make,
  Recursive_react_component$ShadowedByLocalLet$make,
  Recursive_react_component$ShadowedByNestedParameter$make,
}
/* react Not a pure module */
