// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function make() {
  return /a/g;
}

Mocha.describe("Regexp_literal_test", () => {
  Mocha.test("fresh instances and independent lastIndex", () => {
    let first = make();
    let second = make();
    Test_utils.eq("File \"regexp_literal_test.res\", line 10, characters 7-14", first === second, false);
    Test_utils.eq("File \"regexp_literal_test.res\", line 11, characters 7-14", first.test("aa"), true);
    Test_utils.eq("File \"regexp_literal_test.res\", line 12, characters 7-14", first.lastIndex, 1);
    Test_utils.eq("File \"regexp_literal_test.res\", line 13, characters 7-14", second.lastIndex, 0);
    Test_utils.eq("File \"regexp_literal_test.res\", line 14, characters 7-14", first.test("aa"), true);
    Test_utils.eq("File \"regexp_literal_test.res\", line 15, characters 7-14", first.test("aa"), false);
    Test_utils.eq("File \"regexp_literal_test.res\", line 16, characters 7-14", first.lastIndex, 0);
  });
  Mocha.test("escapes and flags survive lowering", () => {
    Test_utils.eq("File \"regexp_literal_test.res\", line 19, characters 7-14", /a\/b\d/i.test("A/b2"), true);
    Test_utils.eq("File \"regexp_literal_test.res\", line 20, characters 7-14", /[/]/.test("/"), true);
    Test_utils.eq("File \"regexp_literal_test.res\", line 21, characters 7-14", /世界/u.test("世界"), true);
  });
});

export {
  make,
}
/*  Not a pure module */
