// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function paramCollision(x, x$1) {
  let x$2 = x$1(x);
  let y = x$1(2);
  return x$2 + y | 0;
}

function laterBinding(x) {
  let x$1 = x + 1 | 0;
  let x$1$1 = x$1 * 10 | 0;
  return [
    x$1,
    x$1$1,
    x$1,
    x$1$1
  ];
}

function earlierBinding(x) {
  let x$1 = x * 10 | 0;
  let x$2 = x + 1 | 0;
  return [
    x$2,
    x$1,
    x$2,
    x$1
  ];
}

function nested(x) {
  let inner = () => {
    let x$1 = x + 1 | 0;
    let x$1$1 = x$1 * 10 | 0;
    return [
      x$1,
      x$1$1,
      x$1,
      x$1$1
    ];
  };
  let x$1 = x + 2 | 0;
  return [
    x$1,
    inner(),
    x$1
  ];
}

Mocha.describe("Shadow_dollar_test", () => {
  Mocha.test("shadowed names do not collide with $ identifiers", () => {
    Test_utils.eq("File \"shadow_dollar_test.res\", line 37, characters 7-14", paramCollision(1, v => v * 10 | 0), 30);
    Test_utils.eq("File \"shadow_dollar_test.res\", line 38, characters 7-14", laterBinding(1), [
      2,
      20,
      2,
      20
    ]);
    Test_utils.eq("File \"shadow_dollar_test.res\", line 39, characters 7-14", earlierBinding(1), [
      2,
      10,
      2,
      10
    ]);
    Test_utils.eq("File \"shadow_dollar_test.res\", line 40, characters 7-14", nested(1), [
      3,
      [
        2,
        20,
        2,
        20
      ],
      3
    ]);
  });
});

export {
  paramCollision,
  laterBinding,
  earlierBinding,
  nested,
}
/*  Not a pure module */
