// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let counter = {
  contents: 0
};

function chain0(x) {
  return ((x * 3 | 0) + (x * x | 0) | 0) + 1 | 0;
}

function chain1(x) {
  return ((chain0(x) * 3 | 0) + chain0(x + 1 | 0) | 0) - (x << 1) | 0;
}

function chain2(x) {
  return ((chain1(x) * 3 | 0) + chain1(x + 1 | 0) | 0) - (x << 1) | 0;
}

function chainEnd(x) {
  return chain2(x) + chain2(x + 1 | 0) | 0;
}

function effectHelper(x) {
  return (((x * x | 0) * 7 | 0) + (x * 3 | 0) | 0) + 5 | 0;
}

function bump(x) {
  counter.contents = counter.contents + effectHelper(x) | 0;
  return counter.contents;
}

bump(1);

function statementHelper(x) {
  return (((x * x | 0) * 5 | 0) + (x * 11 | 0) | 0) + 2 | 0;
}

counter.contents = counter.contents + statementHelper(2) | 0;

Mocha.describe("File \"shake_liveness_test.res\", line 36, characters 9-16", () => {
  Mocha.test("kept bindings work", () => {
    Test_utils.eq("File \"shake_liveness_test.res\", line 39, characters 7-14", counter.contents, 59);
    Test_utils.eq("File \"shake_liveness_test.res\", line 40, characters 7-14", chainEnd(1), 338);
  });
});

export {
  counter,
  chainEnd,
}
/*  Not a pure module */
