// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";

function localPair() {
  let pair_left = 10;
  let pair_right = 20;
  pair_left = pair_left + 1 | 0;
  pair_right = pair_left + pair_right | 0;
  return pair_left + pair_right | 0;
}

function capturedPair() {
  let pair_left = 10;
  let pair_right = 20;
  let bumpLeft = () => {
    pair_left = pair_left + 1 | 0;
  };
  bumpLeft();
  bumpLeft();
  return pair_left + pair_right | 0;
}

function initializationOrder() {
  let seen = /* [] */0;
  let initialize = value => {
    seen = {
      hd: value,
      tl: seen
    };
    return value;
  };
  let pair_left = initialize(1);
  let pair_right = initialize(2);
  pair_left = pair_left + 1 | 0;
  return [
    pair_left + pair_right | 0,
    Stdlib_List.toArray(Stdlib_List.reverse(seen))
  ];
}

function consumePair(pair) {
  return pair.left + pair.right | 0;
}

function escapedPair() {
  return consumePair({
    left: 10,
    right: 20
  });
}

Mocha.describe("Sroa_test", () => {
  Mocha.test("scalarizes a local mutable record", () => Test_utils.eq("File \"sroa_test.res\", line 44, characters 53-60", 42, localPair()));
  Mocha.test("shares scalar fields with closures", () => Test_utils.eq("File \"sroa_test.res\", line 45, characters 54-61", 32, capturedPair()));
  Mocha.test("preserves initializer order", () => Test_utils.eq("File \"sroa_test.res\", line 46, characters 47-54", [
    4,
    [
      1,
      2
    ]
  ], initializationOrder()));
  Mocha.test("retains an escaping record", () => Test_utils.eq("File \"sroa_test.res\", line 47, characters 46-53", 30, consumePair({
    left: 10,
    right: 20
  })));
});

export {
  localPair,
  capturedPair,
  initializationOrder,
  consumePair,
  escapedPair,
}
/*  Not a pure module */
