// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";

function localPair() {
  let pair_left = 10;
  let pair_right = 20;
  pair_left = pair_left + 1 | 0;
  pair_right = pair_left + pair_right | 0;
  return pair_left + pair_right | 0;
}

function capturedPair() {
  let pair_left = 10;
  let pair_right = 20;
  let bumpLeft = () => {
    pair_left = pair_left + 1 | 0;
  };
  bumpLeft();
  bumpLeft();
  return pair_left + pair_right | 0;
}

function initializationOrder() {
  let seen = /* [] */0;
  let initialize = value => {
    seen = {
      hd: value,
      tl: seen
    };
    return value;
  };
  let pair_left = initialize(1);
  let pair_right = initialize(2);
  pair_left = pair_left + 1 | 0;
  return [
    pair_left + pair_right | 0,
    Stdlib_List.toArray(Stdlib_List.reverse(seen))
  ];
}

function consumePair(pair) {
  return pair.left + pair.right | 0;
}

function escapedPair() {
  return consumePair({
    left: 10,
    right: 20
  });
}

function fieldUseCleanup() {
  let effects = /* [] */0;
  let mark = value => {
    effects = {
      hd: value,
      tl: effects
    };
    return value;
  };
  let fields_live = 1;
  mark(2);
  mark(3);
  let fields_readOnly = mark(4);
  mark(5);
  mark(6);
  fields_live = fields_live + fields_readOnly | 0;
  return [
    fields_live,
    Stdlib_List.toArray(Stdlib_List.reverse(effects))
  ];
}

function overwrittenBeforeRead() {
  let effects = /* [] */0;
  let mark = value => {
    effects = {
      hd: value,
      tl: effects
    };
    return value;
  };
  let cell = mark(1);
  cell = mark(2);
  return [
    cell,
    Stdlib_List.toArray(Stdlib_List.reverse(effects))
  ];
}

function capturedWriteOnly() {
  let effects = /* [] */0;
  let mark = value => {
    effects = {
      hd: value,
      tl: effects
    };
    return value;
  };
  mark(1);
  mark(2);
  return Stdlib_List.toArray(Stdlib_List.reverse(effects));
}

function uncalledWriteOnlyClosure() {
  let effects = /* [] */0;
  let mark = value => {
    effects = {
      hd: value,
      tl: effects
    };
    return value;
  };
  mark(1);
  return Stdlib_List.toArray(Stdlib_List.reverse(effects));
}

function readOnlyFieldSnapshotsInitializer() {
  let source = 1;
  let cell = source;
  source = 2;
  return cell;
}

Mocha.describe("Sroa_test", () => {
  Mocha.test("scalarizes a local mutable record", () => Test_utils.eq("File \"sroa_test.res\", line 115, characters 53-60", 42, localPair()));
  Mocha.test("shares scalar fields with closures", () => Test_utils.eq("File \"sroa_test.res\", line 116, characters 54-61", 32, capturedPair()));
  Mocha.test("preserves initializer order", () => Test_utils.eq("File \"sroa_test.res\", line 117, characters 47-54", [
    4,
    [
      1,
      2
    ]
  ], initializationOrder()));
  Mocha.test("retains an escaping record", () => Test_utils.eq("File \"sroa_test.res\", line 118, characters 46-53", 30, consumePair({
    left: 10,
    right: 20
  })));
  Mocha.test("cleans up fields according to their uses", () => Test_utils.eq("File \"sroa_test.res\", line 120, characters 7-14", [
    5,
    [
      2,
      3,
      4,
      5,
      6
    ]
  ], fieldUseCleanup()));
  Mocha.test("preserves overwritten initializer effects", () => Test_utils.eq("File \"sroa_test.res\", line 123, characters 7-14", [
    2,
    [
      1,
      2
    ]
  ], overwrittenBeforeRead()));
  Mocha.test("removes write-only fields captured by closures", () => Test_utils.eq("File \"sroa_test.res\", line 126, characters 7-14", [
    1,
    2
  ], capturedWriteOnly()));
  Mocha.test("does not evaluate writes in uncalled closures", () => Test_utils.eq("File \"sroa_test.res\", line 129, characters 7-14", [1], uncalledWriteOnlyClosure()));
  Mocha.test("read-only fields snapshot their initializer", () => Test_utils.eq("File \"sroa_test.res\", line 132, characters 7-14", 1, readOnlyFieldSnapshotsInitializer()));
});

export {
  localPair,
  capturedPair,
  initializationOrder,
  consumePair,
  escapedPair,
  fieldUseCleanup,
  overwrittenBeforeRead,
  capturedWriteOnly,
  uncalledWriteOnlyClosure,
  readOnlyFieldSnapshotsInitializer,
}
/*  Not a pure module */
