// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

console.log("你好");

console.log(`你好`);

console.log("你好");

function f(x) {
  if (x !== 333) {
    if (x >= 256) {
      return 3;
    } else {
      return 0;
    }
  } else {
    return 2;
  }
}

function spanningSurrogateBlock(x) {
  if (x > 57345 || x < 55294) {
    return 0;
  } else {
    return 1;
  }
}

Mocha.describe("String_unicode_test", () => {
  Mocha.test("switch", () => {
    Test_utils.eq("File \"string_unicode_test.res\", line 25, characters 7-14", f(/* '{' */123), 0);
    Test_utils.eq("File \"string_unicode_test.res\", line 26, characters 7-14", f(/* 'ō' */333), 2);
    Test_utils.eq("File \"string_unicode_test.res\", line 27, characters 7-14", f(/* 'Ƽ' */444), 3);
    Test_utils.eq("File \"string_unicode_test.res\", line 28, characters 7-14", spanningSurrogateBlock(/* '퟾' */55294), 1);
    Test_utils.eq("File \"string_unicode_test.res\", line 29, characters 7-14", spanningSurrogateBlock(/* '' */57345), 1);
  });
});

export {
  f,
  spanningSurrogateBlock,
}
/*  Not a pure module */
