// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Nodepath from "node:path";
import * as Test_utils from "./test_utils.mjs";

let escaped = "abc";

let namedEscapes = "\b\f\n\r\t\x0b\0";

let continued = "ab";

let surrogatePair = "😀";

let concatenated = "ab";

let interpolated = `\x61b\u0063`;

function polymorphicTemplatePair_0(value) {
  return value;
}

let polymorphicTemplatePair = [
  polymorphicTemplatePair_0,
  `literal`
];

let polymorphicTemplateIdentity = polymorphicTemplatePair_0;

let polymorphicTemplateInt = polymorphicTemplateIdentity(1);

let polymorphicTemplateString = polymorphicTemplateIdentity("value");

function constantSwitch() {
  return 1;
}

const rawBridgeProgramValue = '\\n';
;

let rawBridgeExpression = '\\n';

let rawBridgeFunction = (() => '\\n');

let rawBridgeRegex = /\\n/;

Mocha.describe("String_literal_normalization_test", () => {
  Mocha.test("attribute payloads use semantic strings", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 44, characters 59-66", Math.max(1, 2), 2));
  Mocha.test("scope and module payloads use semantic strings", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 47, characters 7-14", Math.max(1, 2), 2);
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 48, characters 7-14", Nodepath.basename("/a/b"), "b");
  });
  Mocha.test("ordinary escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 51, characters 69-76", escaped, "abc"));
  Mocha.test("named escapes and line continuations have JavaScript semantics", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 54, characters 7-14", namedEscapes, "\b\f\n\r\t\x0b\0");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 55, characters 7-14", continued, "ab");
  });
  Mocha.test("surrogate-pair escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 59, characters 7-14", surrogatePair, "😀"));
  Mocha.test("ordinary literals participate in constant folding", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 63, characters 7-14", concatenated, "ab");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 64, characters 7-14", 1, 1);
  });
  Mocha.test("template segments survive the ast0 bridge", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 67, characters 61-68", interpolated, "abc"));
  Mocha.test("constant templates preserve value generalization", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 70, characters 7-14", polymorphicTemplateInt, 1);
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 71, characters 7-14", polymorphicTemplateString, "value");
  });
  Mocha.test("raw extension payloads preserve source spelling through ast0", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 75, characters 7-14", rawBridgeExpression, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 76, characters 7-14", rawBridgeFunction(), "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 77, characters 7-14", rawBridgeProgramValue, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 78, characters 7-14", rawBridgeRegex.test("\\n"), true);
  });
});

export {
  escaped,
  namedEscapes,
  continued,
  surrogatePair,
  concatenated,
  interpolated,
  polymorphicTemplatePair,
  polymorphicTemplateIdentity,
  polymorphicTemplateInt,
  polymorphicTemplateString,
  constantSwitch,
  rawBridgeExpression,
  rawBridgeFunction,
  rawBridgeRegex,
}
/* polymorphicTemplateInt Not a pure module */
