// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let escaped = "\x61\u0062\u{63}";

let namedEscapes = "\b\f\n\r\t\v\0";

let continued = "a\
b";

let concatenated = "\x61\u0062";

let interpolated = `\x61` + "b" + `\u0063`;

function constantSwitch() {
  return 4;
}

const rawBridgeProgramValue = '\\n';
;

let rawBridgeExpression = '\\n';

let rawBridgeFunction = (() => '\\n');

let rawBridgeRegex = /\\n/;

Mocha.describe("String_literal_normalization_test", () => {
  Mocha.test("ordinary escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 30, characters 69-76", escaped, "abc"));
  Mocha.test("named escapes and line continuations have JavaScript semantics", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 33, characters 7-14", namedEscapes, "\b\f\n\r\t\v\0");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 34, characters 7-14", continued, "ab");
  });
  Mocha.test("ordinary literals participate in constant folding", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 38, characters 7-14", concatenated, "ab");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 41, characters 7-14", constantSwitch(), 4);
  });
  Mocha.test("template segments survive the ast0 bridge", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 44, characters 61-68", interpolated, "abc"));
  Mocha.test("raw extension payloads preserve source spelling through ast0", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 47, characters 7-14", rawBridgeExpression, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 48, characters 7-14", rawBridgeFunction(), "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 49, characters 7-14", rawBridgeProgramValue, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 50, characters 7-14", rawBridgeRegex.test("\\n"), true);
  });
});

export {
  escaped,
  namedEscapes,
  continued,
  concatenated,
  interpolated,
  constantSwitch,
  rawBridgeExpression,
  rawBridgeFunction,
  rawBridgeRegex,
}
/*  Not a pure module */
