// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let escaped = "abc";

let surrogatePair = "😀";

let concatenated = "ab";

let interpolated = `\x61` + "b" + `\u0063`;

function constantSwitch() {
  return 1;
}

Mocha.describe("String_literal_normalization_test", () => {
  Mocha.test("ordinary escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 20, characters 69-76", escaped, "abc"));
  Mocha.test("surrogate-pair escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 23, characters 7-14", surrogatePair, "😀"));
  Mocha.test("ordinary literals participate in constant folding", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 27, characters 7-14", concatenated, "ab");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 28, characters 7-14", constantSwitch(), 1);
  });
  Mocha.test("template segments survive the ast0 bridge", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 31, characters 61-68", interpolated, "abc"));
});

export {
  escaped,
  surrogatePair,
  concatenated,
  interpolated,
  constantSwitch,
}
/*  Not a pure module */
