// Generated by ReScript, PLEASE EDIT WITH CARE


function improves_when_merged(value) {
  if (value > 3 || value < 1) {
    return 99;
  } else {
    return 20;
  }
}

function effect(s) {
  console.log(s);
}

function regresses_when_merged(x) {
  if (x > 4 || x < 1) {
    if (x !== 5) {
      console.log("s");
    } else {
      console.log("r");
    }
  } else if (x >= 4) {
    console.log("q");
  } else {
    console.log("d");
  }
}

export {
  improves_when_merged,
  effect,
  regresses_when_merged,
}
/* No side effect */
