// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tagged_template_libJs from "./tagged_template_lib.js";

function makeSql(prim) {
  return Tagged_template_libJs.makeSql(prim);
}

let sql = Tagged_template_libJs.makeSql("X: ");

export {
  makeSql,
  sql,
}
/* sql Not a pure module */
