// Generated by ReScript, PLEASE EDIT WITH CARE


function asResponse(x) {
  return x;
}

function decode(x) {
  if (x.kind === 202 || x.kind === 200) {
    if (x.kind === 202) {
      return x.code + 1 | 0;
    } else {
      return x.code + 3 | 0;
    }
  } else {
    return x.kind + 2 | 0;
  }
}

function decodePartial(x) {
  if (x.kind === 202 || x.kind === 200) {
    if (x.kind === 202) {
      return x.code + 1 | 0;
    } else {
      return 999;
    }
  } else {
    return x.kind + 2 | 0;
  }
}

let ok202 = ({kind: 202, code: 1});

let ok200 = ({kind: 200, code: 2});

let other404 = ({kind: 404, body: "x"});

function asT(x) {
  return x;
}

function classify(x) {
  if (x.k === 200 || x.k === "ok") {
    if (x.k === 200) {
      return "num200";
    } else {
      return "strok";
    }
  } else if (typeof x.k === "number" && x.k !== 200) {
    return "num:" + x.k.toString();
  } else {
    return "str:" + x.k;
  }
}

function classifyPartial(x) {
  if (x.k === 200 || x.k === "ok") {
    return "lit";
  } else if (typeof x.k === "number" && x.k !== 200) {
    return "num:" + x.k.toString();
  } else {
    return "str:" + x.k;
  }
}

let num200 = ({k: 200, v: 1});

let strOk = ({k: "ok", msg: "m"});

let otherNum = ({k: 404, x: 1});

let otherStr = ({k: "else", s: "s"});

let NumAndStrCatchAll_num200Constructed = {
  k: 200,
  v: 1
};

let NumAndStrCatchAll_strOkConstructed = {
  k: "ok",
  msg: "ok"
};

let NumAndStrCatchAll = {
  asT: asT,
  num200Constructed: NumAndStrCatchAll_num200Constructed,
  strOkConstructed: NumAndStrCatchAll_strOkConstructed,
  classify: classify,
  classifyPartial: classifyPartial,
  num200: num200,
  strOk: strOk,
  otherNum: otherNum,
  otherStr: otherStr
};

function asT$1(x) {
  return x;
}

function sum(x) {
  if (x.k !== 1 && x.k !== 3 && x.k !== 2) {
    return x.k + x.y | 0;
  }
  switch (x.k) {
    case 1 :
      return x.x + 10 | 0;
    case 2 :
      return x.x + 20 | 0;
    case 3 :
      return x.x + 30 | 0;
  }
}

function sumPartial(x) {
  if (typeof x.k === "number" && x.k !== 2 && x.k !== 1 && x.k !== 3) {
    return x.k + x.y | 0;
  } else {
    return 0;
  }
}

let one = ({k: 1, x: 1});

let two = ({k: 2, x: 2});

let three = ({k: 3, x: 3});

let other = ({k: 42, y: 1});

let ManyNumLiteralsWithCatchAll_oneConstructed = {
  k: 1,
  x: 1
};

let ManyNumLiteralsWithCatchAll_twoConstructed = {
  k: 2,
  x: 2
};

let ManyNumLiteralsWithCatchAll_threeConstructed = {
  k: 3,
  x: 3
};

let ManyNumLiteralsWithCatchAll = {
  asT: asT$1,
  oneConstructed: ManyNumLiteralsWithCatchAll_oneConstructed,
  twoConstructed: ManyNumLiteralsWithCatchAll_twoConstructed,
  threeConstructed: ManyNumLiteralsWithCatchAll_threeConstructed,
  sum: sum,
  sumPartial: sumPartial,
  one: one,
  two: two,
  three: three,
  other: other
};

function asT$2(x) {
  return x;
}

function classify$1(x) {
  if (typeof x === "object" && x !== null) {
    return 2;
  } else {
    return 1;
  }
}

let okResult = classify$1("ok");

let otherOkResult = classify$1(({kind: "ok", value: 1}));

let NullaryStringAndCatchAll = {
  asT: asT$2,
  okConstructed: "ok",
  classify: classify$1,
  okResult: okResult,
  otherOkResult: otherOkResult
};

function asT$3(x) {
  return x;
}

function classify$2(x) {
  if (x.kind === "ok") {
    return x.value;
  } else {
    return x.value + 10 | 0;
  }
}

let okResult$1 = classify$2(({kind: "ok", value: 1}));

let otherResult = classify$2(({kind: "else", value: 2}));

let NoExposedDiscriminantField_okConstructed = {
  kind: "ok",
  value: 1
};

let NoExposedDiscriminantField = {
  asT: asT$3,
  okConstructed: NoExposedDiscriminantField_okConstructed,
  classify: classify$2,
  okResult: okResult$1,
  otherResult: otherResult
};

function asT$4(x) {
  return x;
}

function classify$3(x) {
  if (typeof x === "object" && x !== null) {
    return 20;
  } else {
    return 10;
  }
}

let nilResult = classify$3(null);

let otherResult$1 = classify$3(({kind: "else", value: 1}));

let NullaryNullAndCatchAll_nilConstructed = null;

let NullaryNullAndCatchAll = {
  asT: asT$4,
  nilConstructed: NullaryNullAndCatchAll_nilConstructed,
  classify: classify$3,
  nilResult: nilResult,
  otherResult: otherResult$1
};

let constructedOk202 = {
  kind: 202,
  code: 10
};

let constructedOk200 = {
  kind: 200,
  code: 20
};

export {
  asResponse,
  constructedOk202,
  constructedOk200,
  decode,
  decodePartial,
  ok202,
  ok200,
  other404,
  NumAndStrCatchAll,
  ManyNumLiteralsWithCatchAll,
  NullaryStringAndCatchAll,
  NoExposedDiscriminantField,
  NullaryNullAndCatchAll,
}
/* okResult Not a pure module */
