// Generated by ReScript, PLEASE EDIT WITH CARE


function test(x) {
  if (x.kind === 200 || x.kind === 202) {
    if (x.kind === 202) {
      return x.code + 1 | 0;
    } else {
      return x.code + 3 | 0;
    }
  } else {
    return x.kind + 2 | 0;
  }
}

function classify(x) {
  if (x.k === "ok" || x.k === 200) {
    if (x.k === 200) {
      return "num200";
    } else {
      return "strok";
    }
  } else if (typeof x.k === "number") {
    return "num:" + String(x.k);
  } else {
    return "str:" + x.k;
  }
}

function classifyPartial(x) {
  if (x.k === "ok" || x.k === 200) {
    return "lit";
  } else if (typeof x.k === "number") {
    return "num:" + String(x.k);
  } else {
    return "str:" + x.k;
  }
}

let NumAndStrCatchAll_a = {
  k: 200,
  v: 1
};

let NumAndStrCatchAll_b = {
  k: "ok",
  msg: "m"
};

let NumAndStrCatchAll_c = {
  k: 404,
  x: 1
};

let NumAndStrCatchAll_d = {
  k: "else",
  s: "s"
};

let NumAndStrCatchAll = {
  classify: classify,
  classifyPartial: classifyPartial,
  a: NumAndStrCatchAll_a,
  b: NumAndStrCatchAll_b,
  c: NumAndStrCatchAll_c,
  d: NumAndStrCatchAll_d
};

function route(x) {
  if (x.k === "warn" || x.k === 201) {
    if (x.k === 201) {
      return "n201";
    } else {
      return "warn";
    }
  } else if (typeof x.k === "number") {
    return "n:" + String(x.k);
  } else {
    return "s:" + x.k;
  }
}

function routePartial(x) {
  if (x.k === "warn" || x.k === 201) {
    return "lit";
  } else if (typeof x.k === "number") {
    return "n:" + String(x.k);
  } else {
    return "s:" + x.k;
  }
}

let NumAndStrLitsAndCatchAlls_n = {
  k: 201,
  v: 1
};

let NumAndStrLitsAndCatchAlls_w = {
  k: "warn",
  level: 2
};

let NumAndStrLitsAndCatchAlls_on = {
  k: 451,
  payload: 0
};

let NumAndStrLitsAndCatchAlls_os = {
  k: "other",
  payload: ""
};

let NumAndStrLitsAndCatchAlls = {
  route: route,
  routePartial: routePartial,
  n: NumAndStrLitsAndCatchAlls_n,
  w: NumAndStrLitsAndCatchAlls_w,
  on: NumAndStrLitsAndCatchAlls_on,
  os: NumAndStrLitsAndCatchAlls_os
};

function sum(x) {
  if (x.k !== 3 && x.k !== 1 && x.k !== 2) {
    return x.k + x.y | 0;
  }
  switch (x.k) {
    case 1 :
      return x.x + 10 | 0;
    case 2 :
      return x.x + 20 | 0;
    case 3 :
      return x.x + 30 | 0;
  }
}

let ManyNumLiteralsWithCatchAll_a = {
  k: 1,
  x: 1
};

let ManyNumLiteralsWithCatchAll_b = {
  k: 2,
  x: 2
};

let ManyNumLiteralsWithCatchAll_c = {
  k: 3,
  x: 3
};

let ManyNumLiteralsWithCatchAll_d = {
  k: 42,
  y: 1
};

let ManyNumLiteralsWithCatchAll = {
  sum: sum,
  a: ManyNumLiteralsWithCatchAll_a,
  b: ManyNumLiteralsWithCatchAll_b,
  c: ManyNumLiteralsWithCatchAll_c,
  d: ManyNumLiteralsWithCatchAll_d
};

export {
  test,
  NumAndStrCatchAll,
  NumAndStrLitsAndCatchAlls,
  ManyNumLiteralsWithCatchAll,
}
/* No side effect */
