// Generated by ReScript, PLEASE EDIT WITH CARE


function caml_is_printable(c) {
  let code = c.charCodeAt(0);
  if (code > 31) {
    return code < 127;
  } else {
    return false;
  }
}

export {
  caml_is_printable,
}
/* No side effect */
