// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";

let v = {
  contents: 0
};

function f() {
  let arr = Stdlib_Array.make(10, param => {});
  for (let i = 0; i <= 9; ++i) {
    arr[i] = param => {
      v.contents = v.contents + i | 0;
    };
  }
  return arr;
}

let u = f();

u.forEach(x => x());

if (v.contents !== 45) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "test_closure.res",
      52,
      2
    ],
    Error: new Error()
  };
}

export {
  v,
  f,
}
/* u Not a pure module */
