// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "@rescript/belt/src/Belt_MapString.mjs";

let v = Belt_MapString.isEmpty(undefined);

export {
  v,
}
/* v Not a pure module */
