// Generated by ReScript, PLEASE EDIT WITH CARE


function for_(x) {
  for (let i = 0, i_finish = (console.log("hi"), x.length); i <= i_finish; ++i) {
    console.log(x[i]);
  }
}

function for_2(x) {
  for (let i = 0, i_finish = x.length; i <= i_finish; ++i) {
    console.log(x[i]);
  }
}

function for_3(x) {
  let v = 0;
  let arr = x.map(param => (() => {}));
  for (let i = 0, i_finish = x.length; i <= i_finish; ++i) {
    let j = (i << 1);
    arr[i] = () => {
      v = v + j | 0;
    };
  }
  arr.forEach(x => x());
  return v;
}

function for_4(x) {
  let v = 0;
  let arr = x.map(param => (() => {}));
  for (let i = 0, i_finish = x.length; i <= i_finish; ++i) {
    let j = (i << 1);
    let k = (j << 1);
    arr[i] = () => {
      v = v + k | 0;
    };
  }
  arr.forEach(x => x());
  return v;
}

function for_5(x, u) {
  let v = 0;
  let arr = x.map(param => (() => {}));
  for (let i = 0, i_finish = x.length; i <= i_finish; ++i) {
    let k = (u << 1) * u | 0;
    arr[i] = () => {
      v = v + k | 0;
    };
  }
  arr.forEach(x => x());
  return v;
}

function for_6(x, u) {
  let v = 0;
  let arr = x.map(param => (() => {}));
  let v4 = 0;
  let v5 = 0;
  v4 = v4 + 1 | 0;
  for (let j = 0; j <= 1; ++j) {
    v5 = v5 + 1 | 0;
    let v2 = 0;
    for (let i = 0, i_finish = x.length; i <= i_finish; ++i) {
      let k = (u << 1) * u | 0;
      let h = (v5 << 1);
      v2 = v2 + 1 | 0;
      arr[i] = () => {
        v = (((((v + k | 0) + v2 | 0) + u | 0) + v4 | 0) + v5 | 0) + h | 0;
      };
    }
  }
  arr.forEach(x => x());
  return v;
}

export {
  for_,
  for_2,
  for_3,
  for_4,
  for_5,
  for_6,
}
/* No side effect */
