// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "U";
import * as VV from "VV";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.mjs";

function f(x, y) {
  return x + y | 0;
}

function f1(x, y) {
  return x + y | 0;
}

function f3(g, x) {
  return g(x);
}

function f2(extra) {
  return 3 + extra | 0;
}

function ff(extra) {
  return U.test_primit(3, extra);
}

let fff = VV.test_primit2(3);

function length_aux(_len, _x) {
  while (true) {
    let x = _x;
    let len = _len;
    if (x === 0) {
      return len;
    }
    _x = x.tl;
    _len = len + 1 | 0;
    continue;
  };
}

let g = 7;

let length = Stdlib_List.length;

let size = Stdlib_List.size;

let head = Stdlib_List.head;

let headExn = Stdlib_List.headExn;

let headOrThrow = Stdlib_List.headOrThrow;

let tail = Stdlib_List.tail;

let tailExn = Stdlib_List.tailExn;

let tailOrThrow = Stdlib_List.tailOrThrow;

let add = Stdlib_List.add;

let get = Stdlib_List.get;

let getExn = Stdlib_List.getExn;

let getOrThrow = Stdlib_List.getOrThrow;

let make = Stdlib_List.make;

let fromInitializer = Stdlib_List.fromInitializer;

let shuffle = Stdlib_List.shuffle;

let toShuffled = Stdlib_List.toShuffled;

let drop = Stdlib_List.drop;

let take = Stdlib_List.take;

let splitAt = Stdlib_List.splitAt;

let concat = Stdlib_List.concat;

let concatMany = Stdlib_List.concatMany;

let reverseConcat = Stdlib_List.reverseConcat;

let flat = Stdlib_List.flat;

let map = Stdlib_List.map;

let zip = Stdlib_List.zip;

let zipBy = Stdlib_List.zipBy;

let mapWithIndex = Stdlib_List.mapWithIndex;

let fromArray = Stdlib_List.fromArray;

let toArray = Stdlib_List.toArray;

let reverse = Stdlib_List.reverse;

let mapReverse = Stdlib_List.mapReverse;

let forEach = Stdlib_List.forEach;

let forEachWithIndex = Stdlib_List.forEachWithIndex;

let reduce = Stdlib_List.reduce;

let reduceWithIndex = Stdlib_List.reduceWithIndex;

let reduceReverse = Stdlib_List.reduceReverse;

let mapReverse2 = Stdlib_List.mapReverse2;

let forEach2 = Stdlib_List.forEach2;

let reduce2 = Stdlib_List.reduce2;

let reduceReverse2 = Stdlib_List.reduceReverse2;

let every = Stdlib_List.every;

let some = Stdlib_List.some;

let every2 = Stdlib_List.every2;

let some2 = Stdlib_List.some2;

let compareLength = Stdlib_List.compareLength;

let compare = Stdlib_List.compare;

let equal = Stdlib_List.equal;

let has = Stdlib_List.has;

let includes = Stdlib_List.includes;

let find = Stdlib_List.find;

let filter = Stdlib_List.filter;

let filterWithIndex = Stdlib_List.filterWithIndex;

let filterMap = Stdlib_List.filterMap;

let partition = Stdlib_List.partition;

let unzip = Stdlib_List.unzip;

let getAssoc = Stdlib_List.getAssoc;

let hasAssoc = Stdlib_List.hasAssoc;

let removeAssoc = Stdlib_List.removeAssoc;

let setAssoc = Stdlib_List.setAssoc;

let sort = Stdlib_List.sort;

export {
  f,
  f1,
  f3,
  f2,
  g,
  ff,
  fff,
  length_aux,
  length,
  size,
  head,
  headExn,
  headOrThrow,
  tail,
  tailExn,
  tailOrThrow,
  add,
  get,
  getExn,
  getOrThrow,
  make,
  fromInitializer,
  shuffle,
  toShuffled,
  drop,
  take,
  splitAt,
  concat,
  concatMany,
  reverseConcat,
  flat,
  map,
  zip,
  zipBy,
  mapWithIndex,
  fromArray,
  toArray,
  reverse,
  mapReverse,
  forEach,
  forEachWithIndex,
  reduce,
  reduceWithIndex,
  reduceReverse,
  mapReverse2,
  forEach2,
  reduce2,
  reduceReverse2,
  every,
  some,
  every2,
  some2,
  compareLength,
  compare,
  equal,
  has,
  includes,
  find,
  filter,
  filterWithIndex,
  filterMap,
  partition,
  unzip,
  getAssoc,
  hasAssoc,
  removeAssoc,
  setAssoc,
  sort,
}
/* fff Not a pure module */
