// Generated by ReScript, PLEASE EDIT WITH CARE


function some(x) {
  return x;
}

function some2(x) {
  return x;
}

let h = [
  3,
  2,
  2
];

export {
  some,
  some2,
  h,
}
/* No side effect */
