// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeos from "node:os";

let match = Nodeos.platform();

let version;

switch (match) {
  case "darwin" :
    version = 2;
    break;
  case "linux" :
    version = 1;
    break;
  default:
    version = 3;
}

function classifyEquivalentEscape(value, selectedCase) {
  switch (value) {
    case "\u0061" :
      if (selectedCase === 2) {
        return 2;
      } else {
        return 5;
      }
    case "\u{61}" :
      if (selectedCase === 3) {
        return 3;
      } else {
        return 5;
      }
    case "\x61" :
      if (selectedCase === 1) {
        return 1;
      } else {
        return 4;
      }
    case "a" :
      if (selectedCase === 0) {
        return 0;
      } else {
        return 5;
      }
    default:
      return 5;
  }
}

export {
  version,
  classifyEquivalentEscape,
}
/* match Not a pure module */
