// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Map from "@rescript/runtime/lib/es6/Stdlib_Map.mjs";

let v = Stdlib_Map.isEmpty(new Map());

export {
  v,
}
/* v Not a pure module */
