// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";

function f(a, b, param) {
  return a + b | 0;
}

function f2(a) {
  return extra => a + 1 | 0;
}

let a = (3).toString();

let arr = Stdlib_Array.fromInitializer(2, param => 0);

for (let i = 0; i <= 1; ++i) {
  arr[i] = i + 1 | 0;
}

console.log([
  a,
  101,
  arr
]);

let b = 101;

let c = arr;

export {
  f,
  f2,
  a,
  b,
  c,
}
/* a Not a pure module */
