// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function ff(v) {
  return v.toString();
}

function f(v) {
  return v.toString();
}

Mocha.describe("To_string_test", () => {
  Mocha.test("infinity to string", () => Test_utils.eq("File \"to_string_test.res\", line 8, characters 38-45", Number.POSITIVE_INFINITY.toString(), "Infinity"));
  Mocha.test("neg_infinity to string", () => Test_utils.eq("File \"to_string_test.res\", line 10, characters 7-14", Number.NEGATIVE_INFINITY.toString(), "-Infinity"));
});

export {
  ff,
  f,
}
/*  Not a pure module */
