// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function colorName(v) {
  if (v === "primary" || v === "secondary") {
    return "not Color";
  } else {
    return v;
  }
}

function numberName(v) {
  if (v === 1) {
    return "one";
  } else {
    return "number";
  }
}

function pureName(v) {
  if (typeof v === "number") {
    return "int";
  } else {
    return "string";
  }
}

function optName(v) {
  if (v == null) {
    if (v === null) {
      return "null";
    } else {
      return "undef";
    }
  } else {
    return "obj";
  }
}

function flagName(v) {
  if (v === true) {
    return "yes";
  } else {
    return "str";
  }
}

function numName(v) {
  if (v === 1) {
    return "one";
  } else {
    return "float";
  }
}

function recName(v) {
  if (v === "empty") {
    return "empty";
  } else {
    return "rec";
  }
}

function pick(v) {
  if (v === "a" || v === "b") {
    return "lit";
  } else {
    return v;
  }
}

function outerName(v) {
  if (v === "x") {
    return "x";
  } else {
    return "w";
  }
}

function boxedName(v) {
  if (typeof v !== "object") {
    return "not Color";
  } else {
    return v._0;
  }
}

function id(x) {
  return x;
}

Mocha.describe("Unboxed_variant_fold_test", () => {
  Mocha.test("folding agrees with runtime dispatch", () => {
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 105, characters 7-14", "not Color", colorName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 106, characters 7-14", "not Color", colorName(id("secondary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 107, characters 7-14", "blue", colorName(id("blue")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 108, characters 7-14", "not Color", colorName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 109, characters 7-14", "one", numberName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 110, characters 7-14", "number", numberName(id(2)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 111, characters 7-14", "one", numberName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 112, characters 7-14", "int", pureName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 113, characters 7-14", "string", pureName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 114, characters 7-14", "obj", optName(id({
      x: 1
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 115, characters 7-14", "null", optName(id(null)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 116, characters 7-14", "undef", optName(id(undefined)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 117, characters 7-14", "str", flagName(id("true")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 118, characters 7-14", "yes", flagName(id(true)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 119, characters 7-14", "one", numName(id(1.0)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 120, characters 7-14", "float", numName(id(2.5)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 121, characters 7-14", "one", numName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 122, characters 7-14", "rec", recName(id({
      y: 1
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 123, characters 7-14", "empty", recName(id("empty")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 124, characters 7-14", "lit", pick(id("a")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 125, characters 7-14", "z", pick(id("z")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 126, characters 7-14", "lit", pick(id("a")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 127, characters 7-14", "w", outerName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 128, characters 7-14", "x", outerName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 129, characters 7-14", "x", outerName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 130, characters 7-14", "primary", boxedName(id({
      TAG: "BoxedColor",
      _0: "primary"
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 131, characters 7-14", "not Color", boxedName(id("primary")));
  });
  Mocha.test("the folded answers themselves are correct", () => {
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 135, characters 7-14", "not Color", "not Color");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 136, characters 7-14", "blue", "blue");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 137, characters 7-14", "one", "one");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 138, characters 7-14", "number", "number");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 139, characters 7-14", "int", "int");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 140, characters 7-14", "one", "one");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 141, characters 7-14", "lit", "lit");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 142, characters 7-14", "x", "x");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 143, characters 7-14", "primary", "primary");
  });
});

export {
  colorName,
  numberName,
  pureName,
  optName,
  flagName,
  numName,
  recName,
  pick,
  outerName,
  boxedName,
  id,
}
/*  Not a pure module */
