// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function colorName(v) {
  if (v === "primary" || v === "secondary") {
    return "not Color";
  } else {
    return v;
  }
}

function numberName(v) {
  if (v === 1) {
    return "one";
  } else {
    return "number";
  }
}

function pureName(v) {
  if (typeof v === "number") {
    return "int";
  } else {
    return "string";
  }
}

function optName(v) {
  if (v == null) {
    if (v === null) {
      return "null";
    } else {
      return "undef";
    }
  } else {
    return "obj";
  }
}

function flagName(v) {
  if (v === true) {
    return "yes";
  } else {
    return "str";
  }
}

function numName(v) {
  if (v === 1) {
    return "one";
  } else {
    return "float";
  }
}

function recName(v) {
  if (v === "empty") {
    return "empty";
  } else {
    return "rec";
  }
}

function pick(v) {
  if (v === "a" || v === "b") {
    return "lit";
  } else {
    return v;
  }
}

function outerName(v) {
  if (v === "x") {
    return "x";
  } else {
    return "w";
  }
}

function boxedName(v) {
  if (typeof v !== "object") {
    return "not Color";
  } else {
    return v._0;
  }
}

function objectName(value) {
  if (Array.isArray(value)) {
    return "tuple";
  } else {
    return "record";
  }
}

function listName(value) {
  if (value === 0) {
    return "zero";
  } else {
    return "list";
  }
}

function bigintName(value) {
  if (value === 10n) {
    return "one";
  } else {
    return "wrapped";
  }
}

function wideName(value) {
  if (value === 1) {
    return "one";
  } else {
    return "int";
  }
}

function id(x) {
  return x;
}

Mocha.describe("Unboxed_variant_fold_test", () => {
  Mocha.test("folding agrees with runtime dispatch", () => {
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 138, characters 7-14", "not Color", colorName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 139, characters 7-14", "not Color", colorName(id("secondary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 140, characters 7-14", "blue", colorName(id("blue")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 141, characters 7-14", "not Color", colorName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 142, characters 7-14", "one", numberName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 143, characters 7-14", "number", numberName(id(2)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 144, characters 7-14", "one", numberName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 145, characters 7-14", "int", pureName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 146, characters 7-14", "string", pureName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 147, characters 7-14", "obj", optName(id({
      x: 1
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 148, characters 7-14", "null", optName(id(null)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 149, characters 7-14", "undef", optName(id(undefined)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 150, characters 7-14", "str", flagName(id("true")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 151, characters 7-14", "yes", flagName(id(true)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 152, characters 7-14", "one", numName(id(1.0)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 153, characters 7-14", "float", numName(id(2.5)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 154, characters 7-14", "one", numName(id(1)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 155, characters 7-14", "rec", recName(id({
      y: 1
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 156, characters 7-14", "empty", recName(id("empty")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 157, characters 7-14", "lit", pick(id("a")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 158, characters 7-14", "z", pick(id("z")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 159, characters 7-14", "lit", pick(id("a")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 160, characters 7-14", "w", outerName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 161, characters 7-14", "x", outerName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 162, characters 7-14", "x", outerName(id("x")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 163, characters 7-14", "primary", boxedName(id({
      TAG: "BoxedColor",
      _0: "primary"
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 164, characters 7-14", "not Color", boxedName(id("primary")));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 165, characters 7-14", "tuple", objectName(id([
      1,
      2
    ])));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 166, characters 7-14", "record", objectName(id({
      x: 1
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 167, characters 7-14", "zero", listName(id(/* [] */0)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 168, characters 7-14", "list", listName(id({
      hd: 1,
      tl: /* [] */0
    })));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 169, characters 7-14", bigintName(10n), bigintName(id(10n)));
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 170, characters 7-14", "one", wideName(id(1)));
  });
  Mocha.test("the folded answers themselves are correct", () => {
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 174, characters 7-14", "not Color", "not Color");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 175, characters 7-14", "blue", "blue");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 176, characters 7-14", "one", "one");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 177, characters 7-14", "number", "number");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 178, characters 7-14", "int", "int");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 179, characters 7-14", "one", "one");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 180, characters 7-14", "lit", "lit");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 181, characters 7-14", "x", "x");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 182, characters 7-14", "primary", "primary");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 183, characters 7-14", "tuple", "tuple");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 184, characters 7-14", "zero", "zero");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 185, characters 7-14", bigintName(10n), "one");
    Test_utils.eq("File \"unboxed_variant_fold_test.res\", line 186, characters 7-14", "one", "one");
  });
});

export {
  colorName,
  numberName,
  pureName,
  optName,
  flagName,
  numName,
  recName,
  pick,
  outerName,
  boxedName,
  objectName,
  listName,
  bigintName,
  wideName,
  id,
}
/*  Not a pure module */
