// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function colorName(value) {
  if (value === "primary" || value === "secondary") {
    return "not Color";
  } else {
    return value;
  }
}

function isPrimary(value) {
  return value === "primary";
}

function numberName(value) {
  if (value === 1) {
    return "one";
  } else {
    return "number";
  }
}

let foldedPrimary = colorName("primary");

let foldedSecondary = colorName("secondary");

let foldedBlue = colorName("blue");

let foldedDefault = isPrimary("primary");

let foldedNumber = numberName(1);

let foldedOtherNumber = numberName(2);

let runtimeColorName = colorName;

let runtimeNumberName = numberName;

let primary = "primary";

let throughBinding = colorName(primary);

function boxedName(value) {
  if (typeof value !== "object") {
    return "not Color";
  } else {
    return value._0;
  }
}

let foldedBoxed = "primary";

Mocha.describe("Unboxed_variant_overlap_test", () => {
  Mocha.test("unboxed variant folding agrees with runtime literal dispatch", () => {
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 59, characters 7-14", foldedPrimary, "not Color");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 60, characters 7-14", foldedSecondary, "not Color");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 61, characters 7-14", foldedBlue, "blue");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 62, characters 7-14", foldedDefault, true);
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 63, characters 7-14", foldedNumber, "one");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 64, characters 7-14", foldedOtherNumber, "number");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 65, characters 7-14", foldedPrimary, runtimeColorName("primary"));
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 66, characters 7-14", foldedNumber, runtimeNumberName(1));
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 67, characters 7-14", throughBinding, "not Color");
    Test_utils.eq("File \"unboxed_variant_overlap_test.res\", line 68, characters 7-14", foldedBoxed, "primary");
  });
});

export {
  colorName,
  isPrimary,
  numberName,
  foldedPrimary,
  foldedSecondary,
  foldedBlue,
  foldedDefault,
  foldedNumber,
  foldedOtherNumber,
  runtimeColorName,
  runtimeNumberName,
  primary,
  throughBinding,
  boxedName,
  foldedBoxed,
}
/* foldedPrimary Not a pure module */
