// Generated by ReScript, PLEASE EDIT WITH CARE


function add(x, y) {
  return x + y | 0;
}

function addC(x, y) {
  return x + y | 0;
}

function unary(x) {
  return x + 1 | 0;
}

let StandardNotation = {
  add: add,
  addC: addC,
  v7: 7,
  v17: 17,
  v27: 27,
  v37: 37,
  unary: unary
};

let v7 = 7;

let v17 = 17;

let v27 = 27;

let v37 = 37;

let v100 = 100;

export {
  StandardNotation,
  v7,
  v17,
  v27,
  v37,
  v100,
}
/* No side effect */
