// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function f(obj) {
  if (typeof obj === "function") {
    return;
  }
  let size = obj.length;
  if (size !== undefined) {
    console.log(Primitive_option.valFromOption(size));
    return;
  }
  
}

export {
  f,
}
/* No side effect */
