// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mt from "./mt.mjs";

let suites = {
  contents: /* [] */0
};

let test_id = {
  contents: 0
};

function eq(loc, x, y) {
  Mt.eq_suites(test_id, suites, loc, x, y);
}

function f_01() {
  return hi(x => {
    if (x === undefined) {
      console.log("x");
      return;
    }
    
  });
}

function u(x) {
  if (x > 3) {
    return 1;
  } else if (x < 2) {
    return 2;
  } else if (x > 4) {
    return 0;
  } else {
    return 3;
  }
}

function fx() {
  
}

function u0(x) {
  return x;
}

let u1;

function u2(x) {
  return x;
}

let u3;

eq("File \"unit_undefined_test.res\", line 41, characters 3-10", undefined, undefined);

eq("File \"unit_undefined_test.res\", line 42, characters 3-10", u1, undefined);

eq("File \"unit_undefined_test.res\", line 43, characters 3-10", undefined, undefined);

eq("File \"unit_undefined_test.res\", line 44, characters 3-10", u3, undefined);

eq("File \"unit_undefined_test.res\", line 45, characters 3-10", undefined, undefined);

Mt.from_pair_suites("unit_undefined_test.res", suites.contents);

let u4;

export {
  suites,
  test_id,
  eq,
  f_01,
  u,
  fx,
  u0,
  u1,
  u2,
  u3,
  u4,
}
/*  Not a pure module */
