name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, macos-arm]
        ocaml_compiler: [4.14.0]

    runs-on: ${{matrix.os}}

    env:
      BS_TRAVIS_CI: 1
      OCAMLRUNPARAM: b

    steps:
    - name: "Windows: Set git to use LF"
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use OCaml ${{matrix.ocaml_compiler}}
      if: runner.name != 'macos-arm'
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{matrix.ocaml_compiler}}
        opam-pin: false
        opam-depext: false

    - name: Use OCaml ${{matrix.ocaml_compiler}}
      if: runner.name == 'macos-arm'
      uses: AbstractMachinesLab/setup-ocaml@arm-support
      with:
        ocaml-compiler: ${{matrix.ocaml_compiler}}
        opam-pin: false
        opam-depext: false

    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16

    - name: ci-install
      run: opam exec -- npm ci

    - name: Run tests (macOS)
      if: matrix.os == 'macos-latest'
      run: opam exec -- node scripts/ciTest.js -all

    - name: Run tests (macos-arm)
      if: matrix.os == 'macos-arm'
      run: opam exec -- node scripts/ciTest.js -all
    
    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: opam exec -- node scripts/ciTest.js -all
    
    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      run: opam exec -- node scripts/ciTest.js -mocha -theme

    - name: Get artifact info
      id: get_artifact_info
      run: node .github/workflows/get_artifact_info.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.get_artifact_info.outputs.artifact_name }}
        path: ${{ steps.get_artifact_info.outputs.artifact_path }}
